using Microsoft.EntityFrameworkCore;
using SaintJudeHospital.Data.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace SaintJudeHospital.Data.Seed
{
    public class AppDbContextInitializer
    {
        private static ModelBuilder _builder;

        public static void Load(ModelBuilder builder)
        {
            _builder = builder;

            UsersRole();
            Users();
            Immunizes();
            Symtoms();
            Brands();
            Inscriptions();
            Generics();
            Medicines();
        }

        private static void UsersRole()
        {
            _builder.Entity<Role>().HasData(
                new Role { RoleId = 1, Name = "Administrator" },
                new Role { RoleId = 2, Name = "StandardUser"});
        }

        private static void Users()
        {
            _builder.Entity<User>().HasData(
                new User { FirstName = "Carl", LastName = "Tanilon", Password = "1234", RoleId = 1, Username = "carl" , UserId = 1});
        }

        private static void Immunizes()
        {
            _builder.Entity<Immunize>().HasData(
                new Immunize { Id = 1, Name = "HEXA", Amount = 3000 },
                new Immunize { Id = 2, Name = "PCV 10", Amount = 3200 },
                new Immunize { Id = 3, Name = "MEASLES", Amount = 750 },
                new Immunize { Id = 4, Name = "HIB", Amount = 1300 },
                new Immunize { Id = 5, Name = "MENINGO", Amount = 4000 },
                new Immunize { Id = 6, Name = "TYPHOID", Amount = 1300 },
                new Immunize { Id = 7, Name = "HEP A", Amount = 1800 },
                new Immunize { Id = 8, Name = "HEP B", Amount = 700 },
                new Immunize { Id = 9, Name = "TETRAXIM", Amount = 1600 },
                new Immunize { Id = 10, Name = "MMR", Amount = 1200 },
                new Immunize { Id = 11, Name = "CHICKEN POX", Amount = 2200 },
                new Immunize { Id = 12, Name = "PENTA", Amount = 2500 },
                new Immunize { Id = 13, Name = "BCG-1", Amount = 900 },
                new Immunize { Id = 14, Name = "MMR-V", Amount = 3000 },
                new Immunize { Id = 15, Name = "PNEUMO-23", Amount = 1700 },
                new Immunize { Id = 16, Name = "RABIES", Amount = 1700 },
                new Immunize { Id = 17, Name = "ROTARIX", Amount = 3000 },
                new Immunize { Id = 18, Name = "ROTATEQ", Amount = 2200 },
                new Immunize { Id = 19, Name = "FLU", Amount = 1000 },
                new Immunize { Id = 20, Name = "PCV", Amount = 4000 },
                new Immunize { Id = 21, Name = "BCG-2", Amount = 0 });
        }

        private static void Symtoms()
        {
            _builder.Entity<Symtom>().HasData(
                new Symtom { Id = 1, Name = "Bleeding"},
                new Symtom { Id = 2, Name = "Bruise"},
                new Symtom { Id = 3, Name = "Cough"},
                new Symtom { Id = 4, Name = "Bites"},
                new Symtom { Id = 5, Name = "Fever"},
                new Symtom { Id = 6, Name = "Cold"},
                new Symtom { Id = 7, Name = "Difficulty in swallowing" },
                new Symtom { Id = 8, Name = "Ear discharge"},
                new Symtom { Id = 9, Name = "Ear ache/pain"},
                new Symtom { Id = 10, Name = "Constipation"},
                new Symtom { Id = 11, Name = "Diarrhea"},
                new Symtom { Id = 12, Name = "Hair fall"},
                new Symtom { Id = 13, Name = "Abdominal pain"},
                new Symtom { Id = 14, Name = "Deformity"},
                new Symtom { Id = 15, Name = "Headache"},
                new Symtom { Id = 16, Name = "Infected wounds"},
                new Symtom { Id = 17, Name = "Itchness"},
                new Symtom { Id = 18, Name = "Loss of consciousness"},
                new Symtom { Id = 19, Name = "Mass"},
                new Symtom { Id = 20, Name = "Joint pain"},
                new Symtom { Id = 21, Name = "Muscle pain"},
                new Symtom { Id = 22, Name = "Skin lesions"},
                new Symtom { Id = 23, Name = "Trauma"},
                new Symtom { Id = 24, Name = "Pain urination"},
                new Symtom { Id = 25, Name = "Rushes"},
                new Symtom { Id = 26, Name = "Less appetite"},
                new Symtom { Id = 27, Name = "LBM"},
                new Symtom { Id = 28, Name = "Vomiting"},
                new Symtom { Id = 29, Name = "Dysuria"},
                new Symtom { Id = 30, Name = "Rashes"},
                new Symtom { Id = 31, Name = "Dysphagia"},
                new Symtom { Id = 32, Name = "Vaginal Discharge"},
                new Symtom { Id = 33, Name = "Urticarial rash"},
                new Symtom { Id = 34, Name = "Eye discharge"},
                new Symtom { Id = 35, Name = "Chest gurgling"},
                new Symtom { Id = 36, Name = "Epistaxis"},
                new Symtom { Id = 37, Name = "Pustules"},
                new Symtom { Id = 38, Name = "Nasal congestion"});
        }

        private static void Brands()
        {
            _builder.Entity<Brand>().HasData(
                new Brand { Id = 1, Name = "Activent" },
                new Brand { Id = 2, Name = "Advil" },
                new Brand { Id = 3, Name = "Allerkid" },
                new Brand { Id = 4, Name = "Alloxygen" },
                new Brand { Id = 5, Name = "Alnix" },
                new Brand { Id = 6, Name = "Alvedon" },
                new Brand { Id = 7, Name = "Ambrolex" },
                new Brand { Id = 8, Name = "Amoclav" },
                new Brand { Id = 9, Name = "Amoxil" },
                new Brand { Id = 10, Name = "Ampicin" },
                new Brand { Id = 11, Name = "Ansimar" },
                new Brand { Id = 12, Name = "Antiox" },
                new Brand { Id = 13, Name = "Asfrenon" },
                new Brand { Id = 14, Name = "Asfrenon Expt" },
                new Brand { Id = 15, Name = "Asmalin" },
                new Brand { Id = 16, Name = "Asmalin Broncho" },
                new Brand { Id = 17, Name = "Augmentin" },
                new Brand { Id = 18, Name = "Avamys" },
                new Brand { Id = 19, Name = "Azith" },
                new Brand { Id = 20, Name = "Bacidal" },
                new Brand { Id = 21, Name = "Bactroban" },
                new Brand { Id = 22, Name = "Bambec"},
                new Brand { Id = 23, Name = "Bioclauid" },
                new Brand { Id = 24, Name = "Biogesic" },
                new Brand { Id = 25, Name = "Bricanyl" },
                new Brand { Id = 26, Name = "Broncaire Expt" },
                new Brand { Id = 27, Name = "Bronchofen" },
                new Brand { Id = 28, Name = "Calmoseptine" },
                new Brand { Id = 29, Name = "Calpol" },
                new Brand { Id = 30, Name = "Ceclor" },
                new Brand { Id = 31, Name = "Cefalin" },
                new Brand { Id = 32, Name = "Ceporex" },
                new Brand { Id = 33, Name = "Cherifer" },
                new Brand { Id = 34, Name = "Chloromycetin" },
                new Brand { Id = 35, Name = "Clariget" },
                new Brand { Id = 36, Name = "Clarithro-Natrapharm Klaryz" },
                new Brand { Id = 37, Name = "Clarithro-natrapharm" },
                new Brand { Id = 38, Name = "Clarithrocid" },
                new Brand { Id = 39, Name = "Clotrasone" },
                new Brand { Id = 40, Name = "Combantrin" },
                new Brand { Id = 41, Name = "Combivent" },
                new Brand { Id = 42, Name = "Daktarin" },
                new Brand { Id = 43, Name = "Dalacin C" },
                new Brand { Id = 44, Name = "Dg" },
                new Brand { Id = 45, Name = "Dilatair" },
                new Brand { Id = 46, Name = "Dimetapp" },
                new Brand { Id = 47, Name = "Disudrin" },
                new Brand { Id = 48, Name = "Dolan" },
                new Brand { Id = 49, Name = "Dolfenal" },
                new Brand { Id = 50, Name = "Duavent" },
                new Brand { Id = 51, Name = "E Zinc" },
                new Brand { Id = 52, Name = "Elica" },
                new Brand { Id = 53, Name = "Erceflora" },
                new Brand { Id = 54, Name = "Ercefuryl" },
                new Brand { Id = 55, Name = "Essentiale Forte" },
                new Brand { Id = 56, Name = "Expel" },
                new Brand { Id = 57, Name = "Faspic" },
                new Brand { Id = 58, Name = "Flagyl" },
                new Brand { Id = 59, Name = "Flanax" },
                new Brand { Id = 60, Name = "Fluimucil" },
                new Brand { Id = 61, Name = "Fucidin" },
                new Brand { Id = 62, Name = "Fucidin-h" },
                new Brand { Id = 63, Name = "Fucithalmic" },
                new Brand { Id = 64, Name = "Furoxone" },
                new Brand { Id = 65, Name = "Garamycin" },
                new Brand { Id = 66, Name = "Gardan" },
                new Brand { Id = 67, Name = "Heraclene" },
                new Brand { Id = 68, Name = "Himox" },
                new Brand { Id = 69, Name = "Hisdec" },
                new Brand { Id = 70, Name = "Hydrite" },
                new Brand { Id = 71, Name = "Ilosone" },
                new Brand { Id = 72, Name = "Immunosine" },
                new Brand { Id = 73, Name = "Iterax" },
                new Brand { Id = 74, Name = "Jetepar" },
                new Brand { Id = 75, Name = "Kastair" },
                new Brand { Id = 76, Name = "Katrex" },
                new Brand { Id = 77, Name = "Klarizid" },
                new Brand { Id = 78, Name = "Klaz" },
                new Brand { Id = 79, Name = "Locetar" },
                new Brand { Id = 80, Name = "Loviscol" },
                new Brand { Id = 81, Name = "Maalox" },
                new Brand { Id = 82, Name = "Medicol" },
                new Brand { Id = 83, Name = "Meptin" },
                new Brand { Id = 84, Name = "Montemax" },
                new Brand { Id = 85, Name = "Montiget" },
                new Brand { Id = 86, Name = "Motilium" },
                new Brand { Id = 87, Name = "Movelax" },
                new Brand { Id = 88, Name = "Muconase" },
                new Brand { Id = 89, Name = "Mucosolvan" },
                new Brand { Id = 90, Name = "Myonal" },
                new Brand { Id = 91, Name = "Myremol" },
                new Brand { Id = 92, Name = "Napran" },
                new Brand { Id = 93, Name = "Naprex" },
                new Brand { Id = 94, Name = "Nasatapp" },
                new Brand { Id = 95, Name = "Nasathera" },
                new Brand { Id = 96, Name = "Nasoclear" },
                new Brand { Id = 97, Name = "Natravox" },
                new Brand { Id = 98, Name = "Neozep" },
                new Brand { Id = 99, Name = "Nuelin" },
                new Brand { Id = 100, Name = "Omepron" },
                new Brand { Id = 101, Name = "Opigesic" },
                new Brand { Id = 102, Name = "Optipred" },
                new Brand { Id = 103, Name = "Orastin" },
                new Brand { Id = 104, Name = "Pediachlor" },
                new Brand { Id = 105, Name = "Pediamox" },
                new Brand { Id = 106, Name = "Pediatapp" },
                new Brand { Id = 107, Name = "Penachlor" },
                new Brand { Id = 108, Name = "Pharex" },
                new Brand { Id = 109, Name = "Physiogel" },
                new Brand { Id = 110, Name = "Polypen" },
                new Brand { Id = 111, Name = "Ponstan" },
                new Brand { Id = 112, Name = "Poro" },
                new Brand { Id = 113, Name = "Pred 10" },
                new Brand { Id = 114, Name = "Pred 20" },
                new Brand { Id = 115, Name = "Propan Tlc" },
                new Brand { Id = 116, Name = "Prostaphlin-A" },
                new Brand { Id = 117, Name = "Provexcel" },
                new Brand { Id = 118, Name = "Prox-S" },
                new Brand { Id = 119, Name = "Pulmodual" },
                new Brand { Id = 120, Name = "Pulmoxcel" },
                new Brand { Id = 121, Name = "Restime" },
                new Brand { Id = 122, Name = "Ritemed" },
                new Brand { Id = 123, Name = "Rodazid" },
                new Brand { Id = 124, Name = "Romamed" },
                new Brand { Id = 125, Name = "Rotocin" },
                new Brand { Id = 126, Name = "Salinase" },
                new Brand { Id = 127, Name = "Sangobion" },
                new Brand { Id = 128, Name = "Selzef" },
                new Brand { Id = 129, Name = "Seretide" },
                new Brand { Id = 130, Name = "Singulair" },
                new Brand { Id = 131, Name = "Skelan" },
                new Brand { Id = 132, Name = "Solmux"},
                new Brand { Id = 133, Name = "Solmux Broncho" },
                new Brand { Id = 134, Name = "Stafloxin" },
                new Brand { Id = 135, Name = "Sumapen" },
                new Brand { Id = 136, Name = "Tempra" },
                new Brand { Id = 137, Name = "Tergecet" },
                new Brand { Id = 138, Name = "Trizole" },
                new Brand { Id = 139, Name = "Ultraxime" },
                new Brand { Id = 140, Name = "Ventolin" },
                new Brand { Id = 141, Name = "Ventolin Expt" },
                new Brand { Id = 142, Name = "Virlix" },
                new Brand { Id = 143, Name = "Vometa" },
                new Brand { Id = 144, Name = "Xelent" },
                new Brand { Id = 145, Name = "Xinflex" },
                new Brand { Id = 146, Name = "Xyzal" },
                new Brand { Id = 147, Name = "Zeditapp" },
                new Brand { Id = 148, Name = "Zegen" },
                new Brand { Id = 149, Name = "Zenith" },
                new Brand { Id = 150, Name = "Zinnat" },
                new Brand { Id = 151, Name = "Zithromax" },
                new Brand { Id = 152, Name = "Zovirax" },
                new Brand { Id = 153, Name = "Zyrtec" });
        }

        private static void Inscriptions()
        {
            _builder.Entity<Inscription>().HasData(
                new Inscription { Id = 1, Name = "Ai Lotion" },
                new Inscription { Id = 2, Name = "Amp" },
                new Inscription { Id = 3, Name = "Campsuele" },
                new Inscription { Id = 4, Name = "Cream" },
                new Inscription { Id = 5, Name = "Drops" },
                new Inscription { Id = 6, Name = "Eyedrops" },
                new Inscription { Id = 7, Name = "Granules" },
                new Inscription { Id = 8, Name = "Lotion" },
                new Inscription { Id = 9, Name = "MDI" },
                new Inscription { Id = 10, Name = "Nail Lacquer" },
                new Inscription { Id = 11, Name = "Nasal Drops" },
                new Inscription { Id = 12, Name = "Nebule" },
                new Inscription { Id = 13, Name = "Ointment" },
                new Inscription { Id = 14, Name = "Oral Gel" },
                new Inscription { Id = 15, Name = "Oral Solution" },
                new Inscription { Id = 16, Name = "Pediatric Capsule" },
                new Inscription { Id = 17, Name = "Pediatric Suppository" },
                new Inscription { Id = 18, Name = "Sachet" },
                new Inscription { Id = 19, Name = "Skin Cleanser" },
                new Inscription { Id = 20, Name = "Solution" },
                new Inscription { Id = 21, Name = "Suppository" },
                new Inscription { Id = 22, Name = "Suspension" },
                new Inscription { Id = 23, Name = "Syrup" },
                new Inscription { Id = 24, Name = "Tablet" },
                new Inscription { Id = 25, Name = "Tube" },
                new Inscription { Id = 26, Name = "Bottle" },
                new Inscription { Id = 27, Name = "Nasal Spray" },
                new Inscription { Id = 28, Name = "Can" });
        }

        private static void Generics()
        {
            _builder.Entity<Generic>().HasData(
                new Generic { Id = 1, Name = "Acetylcysteine" },
                new Generic { Id = 2, Name = "Acyclovir" },
                new Generic { Id = 3, Name = "Aluminum Magnesium Hydroxide" },
                new Generic { Id = 4, Name = "Ambroxol" },
                new Generic { Id = 5, Name = "Amorolfine" },
                new Generic { Id = 6, Name = "Amoxicillin" },
                new Generic { Id = 7, Name = "Ampicillin IV" },
                new Generic { Id = 8, Name = "Azithromycin" },
                new Generic { Id = 9, Name = "Bacillus Clausii" },
                new Generic { Id = 10, Name = "Bambuterol" },
                new Generic { Id = 11, Name = "Betaine Glucuronate Plus" },
                new Generic { Id = 12, Name = "Brompheniramine Maleate + Phenylephrine" },
                new Generic { Id = 13, Name = "Brompheniramine Maleate + Phenylpropanolamine" },
                new Generic { Id = 14, Name = "Broncho Vaxom" },
                new Generic { Id = 15, Name = "Calmoseptine" },
                new Generic { Id = 16, Name = "Carbocisteine" },
                new Generic { Id = 17, Name = "Cefaclor" },
                new Generic { Id = 18, Name = "Cefaclor + Guaifenesin" },
                new Generic { Id = 19, Name = "Cefalexin" },
                new Generic { Id = 20, Name = "Cefixime" },
                new Generic { Id = 21, Name = "Cefuroxime" },
                new Generic { Id = 22, Name = "Cetirizine" },
                new Generic { Id = 23, Name = "Chloramphenicol" },
                new Generic { Id = 24, Name = "Clarithromycin" },
                new Generic { Id = 25, Name = "Clindamycin" },
                new Generic { Id = 26, Name = "Clotrimazole + Betamethasone" },
                new Generic { Id = 27, Name = "Cloxacillin" },
                new Generic { Id = 28, Name = "Co Amoxiclav" },
                new Generic { Id = 29, Name = "Cotrimoxazole" },
                new Generic { Id = 30, Name = "Dg Milk" },
                new Generic { Id = 31, Name = "Dibencozide" },
                new Generic { Id = 32, Name = "Domperidone" },
                new Generic { Id = 33, Name = "Doxofylline" },
                new Generic { Id = 34, Name = "Eperisone HCI" },
                new Generic { Id = 35, Name = "Erythromycin" },
                new Generic { Id = 36, Name = "Ferrous Gluconate" },
                new Generic { Id = 37, Name = "Fluocloxacillin" },
                new Generic { Id = 38, Name = "Fluticasone Furoate" },
                new Generic { Id = 39, Name = "Fucidic Acid" },
                new Generic { Id = 40, Name = "Fucidic Acid + Hydrocortisone" },
                new Generic { Id = 41, Name = "Furazolidone" },
                new Generic { Id = 42, Name = "Fusidate Sodium" },
                new Generic { Id = 43, Name = "Gentamicin IV" },
                new Generic { Id = 44, Name = "Gentamycin" },
                new Generic { Id = 45, Name = "Glycerin" },
                new Generic { Id = 46, Name = "Hydroxyzine diHCI" },
                new Generic { Id = 47, Name = "Ibuprofen" },
                new Generic { Id = 48, Name = "Inosiplex" },
                new Generic { Id = 49, Name = "Lactulose" },
                new Generic { Id = 50, Name = "Levocetirizine Diltci" },
                new Generic { Id = 51, Name = "Mebendazole" },
                new Generic { Id = 52, Name = "Mefenamic Acid" },
                new Generic { Id = 53, Name = "Metronidazole" },
                new Generic { Id = 54, Name = "Miconazole" },
                new Generic { Id = 55, Name = "Mometasone Furoate" },
                new Generic { Id = 56, Name = "Montelukast" },
                new Generic { Id = 57, Name = "Multivitamins" },
                new Generic { Id = 58, Name = "Mupirocin" },
                new Generic { Id = 59, Name = "Naproxen Sodium" },
                new Generic { Id = 60, Name = "Nifuroxazide" },
                new Generic { Id = 61, Name = "Nystatin" },
                new Generic { Id = 62, Name = "Omeprazole" },
                new Generic { Id = 63, Name = "Oral Rehydration Solution" },
                new Generic { Id = 64, Name = "Paracetamol" },
                new Generic { Id = 65, Name = "Paracetamol + Phenylpropanolamine" },
                new Generic { Id = 66, Name = "Phenoxymethylpenicillin K" },
                new Generic { Id = 67, Name = "Phenylephrine Hcl + Chlorpheniramine Maleate" },
                new Generic { Id = 68, Name = "Phenylpropanolamine" },
                new Generic { Id = 69, Name = "Phospholipids" },
                new Generic { Id = 70, Name = "Physiogel" },
                new Generic { Id = 71, Name = "Prednisolone" },
                new Generic { Id = 72, Name = "Prednisone" },
                new Generic { Id = 73, Name = "Procaterol" },
                new Generic { Id = 74, Name = "Pyrantel Pamoate" },
                new Generic { Id = 75, Name = "Salbutamol" },
                new Generic { Id = 76, Name = "Salbutamol + Guaifenesin" },
                new Generic { Id = 77, Name = "Salbutamol + Ipratropium Bromide" },
                new Generic { Id = 78, Name = "Salmeterol + Fluticasone Propionate" },
                new Generic { Id = 79, Name = "Simethicone" },
                new Generic { Id = 80, Name = "Sodium Chloride" },
                new Generic { Id = 81, Name = "Terbutaline" },
                new Generic { Id = 82, Name = "Theophylline" },
                new Generic { Id = 83, Name = "Zinc Sulfate" });
        }

        private static void Medicines()
        {
            _builder.Entity<Medicine>().HasData(
                new Medicine { Id = 1, GenericId = 22, InscriptionId = 24, Description = "10mg", BrandId = null },
                new Medicine { Id = 2, GenericId = 6, InscriptionId = 3, Description = "500mg", BrandId = null },
                new Medicine { Id = 3, GenericId = 6, InscriptionId = 3, Description = "250mg", BrandId = null },
                new Medicine { Id = 4, GenericId = 28, InscriptionId = 24, Description = "375mg", BrandId = null },
                new Medicine { Id = 5, GenericId = 71, InscriptionId = 24, Description = "30mg", BrandId = null },
                new Medicine { Id = 6, GenericId = 71, InscriptionId = 24, Description = "20mg", BrandId = null },
                new Medicine { Id = 7, GenericId = 71, InscriptionId = 24, Description = "5mg", BrandId = null },
                new Medicine { Id = 8, GenericId = 43, InscriptionId = 2, Description = "80mg/5ml", BrandId = null },
                new Medicine { Id = 9, GenericId = 43, InscriptionId = 2, Description = "40mg/5ml", BrandId = null },
                new Medicine { Id = 10, GenericId = 14, InscriptionId = 16, Description = null, BrandId = null },
                new Medicine { Id = 11, GenericId = 45, InscriptionId = 17, Description = null, BrandId = null },
                new Medicine { Id = 12, GenericId = 75, InscriptionId = 24, Description = "2mg", BrandId = 1 },
                new Medicine { Id = 13, GenericId = 75, InscriptionId = 23, Description = "2mg/5ml", BrandId = 1 },
                new Medicine { Id = 14, GenericId = 47, InscriptionId = 22, Description = "100mg/5ml", BrandId = 2 },
                new Medicine { Id = 15, GenericId = 47, InscriptionId = 22, Description = "200mg/5ml", BrandId = 2 },
                new Medicine { Id = 16, GenericId = 47, InscriptionId = 3, Description = "200mg", BrandId = 2 },
                new Medicine { Id = 17, GenericId = 47, InscriptionId = 5, Description = "100mg/2.5ml", BrandId = 2 },
                new Medicine { Id = 18, GenericId = 22, InscriptionId = 23, Description = "5mg/5ml", BrandId = 3 },
                new Medicine { Id = 19, GenericId = 22, InscriptionId = 5, Description = "2.5mg/ml", BrandId = 3 },
                new Medicine { Id = 20, GenericId = 81, InscriptionId = 23, Description = "1.5mg/5ml", BrandId = null },
                new Medicine { Id = 21, GenericId = 22, InscriptionId = 24, Description = "10mg", BrandId = 4 },
                new Medicine { Id = 22, GenericId = 22, InscriptionId = 23, Description = "5mg/5ml", BrandId = 4 },
                new Medicine { Id = 23, GenericId = 22, InscriptionId = 5, Description = "2.5mg/ml", BrandId = 5 },
                new Medicine { Id = 24, GenericId = 64, InscriptionId = 24, Description = "250mg", BrandId = 5 },
                new Medicine { Id = 25, GenericId = 64, InscriptionId = 24, Description = "325mg", BrandId = 5 },
                new Medicine { Id = 26, GenericId = 64, InscriptionId = 24, Description = "500mg", BrandId = 5 },
                new Medicine { Id = 27, GenericId = 64, InscriptionId = 23, Description = "120mg/5ml", BrandId = 6 },
                new Medicine { Id = 28, GenericId = 64, InscriptionId = 5, Description = "100ml", BrandId = 6 },
                new Medicine { Id = 29, GenericId = 4, InscriptionId = 24, Description = "30mg", BrandId = 7 },
                new Medicine { Id = 30, GenericId = 4, InscriptionId = 23, Description = "30mg/3ml", BrandId = 7 },
                new Medicine { Id = 31, GenericId = 4, InscriptionId = 23, Description = "15mg/5ml", BrandId = 7 },
                new Medicine { Id = 32, GenericId = 4, InscriptionId = 5, Description = "7.5mg/ml", BrandId = 7 },
                new Medicine { Id = 33, GenericId = 28, InscriptionId = 22, Description = "457mg/5ml", BrandId = 8 },
                new Medicine { Id = 34, GenericId = 28, InscriptionId = 22, Description = "228mg/5ml", BrandId = 8 },
                new Medicine { Id = 35, GenericId = 28, InscriptionId = 22, Description = "156mg/5ml", BrandId = 8 },
                new Medicine { Id = 36, GenericId = 28, InscriptionId = 22, Description = "312mg/5ml", BrandId = 8 },
                new Medicine { Id = 37, GenericId = 6, InscriptionId = 22, Description = "250mg/5ml", BrandId = 9 },
                new Medicine { Id = 38, GenericId = 6, InscriptionId = 5, Description = "100mg/ml", BrandId = 9 },
                new Medicine { Id = 39, GenericId = 6, InscriptionId = 22, Description = "125mg/ml", BrandId = 9 },
                new Medicine { Id = 40, GenericId = 7, InscriptionId = null, Description = "1mg", BrandId = 10 },
                new Medicine { Id = 41, GenericId = 7, InscriptionId = null, Description = "500mg", BrandId = 10 },
                new Medicine { Id = 42, GenericId = 7, InscriptionId = null, Description = "750mg", BrandId = 10 },
                new Medicine { Id = 43, GenericId = 7, InscriptionId = null, Description = "250mg", BrandId = 10 },
                new Medicine { Id = 44, GenericId = 33, InscriptionId = 24, Description = "100mg", BrandId = 11 },
                new Medicine { Id = 45, GenericId = 33, InscriptionId = 23, Description = "100mg/5ml", BrandId = 11 },
                new Medicine { Id = 46, GenericId = 51, InscriptionId = 24, Description = "100mg", BrandId = 12 },
                new Medicine { Id = 47, GenericId = 51, InscriptionId = 22, Description = "20mg/ml", BrandId = 12 },
                new Medicine { Id = 48, GenericId = 51, InscriptionId = 24, Description = "500mg", BrandId = 12 },
                new Medicine { Id = 49, GenericId = 51, InscriptionId = 22, Description = "50mg/ml", BrandId = 12 },
                new Medicine { Id = 50, GenericId = 75, InscriptionId = 23, Description = "2mg/5ml", BrandId = 13 },
                new Medicine { Id = 51, GenericId = 76, InscriptionId = 23, Description = null, BrandId = 14 },
                new Medicine { Id = 52, GenericId = 75, InscriptionId = 9, Description = "100mgm/Inhalation", BrandId = 15 },
                new Medicine { Id = 53, GenericId = 75, InscriptionId = 12, Description = "2.5mg/2.5ml", BrandId = 15 },
                new Medicine { Id = 54, GenericId = 75, InscriptionId = 24, Description = "2mg", BrandId = 15 },
                new Medicine { Id = 55, GenericId = 75, InscriptionId = 23, Description = "2mg/5ml", BrandId = 15 },
                new Medicine { Id = 56, GenericId = 76, InscriptionId = 23, Description = null, BrandId = 16 },
                new Medicine { Id = 57, GenericId = 28, InscriptionId = 24, Description = "625mg", BrandId = 17 },
                new Medicine { Id = 58, GenericId = 28, InscriptionId = 22, Description = "156mg/5ml", BrandId = 17 },
                new Medicine { Id = 59, GenericId = 28, InscriptionId = 22, Description = "457mg/5ml", BrandId = 17 },
                new Medicine { Id = 60, GenericId = 28, InscriptionId = 22, Description = "228mg/5ml", BrandId = 17 },
                new Medicine { Id = 61, GenericId = 28, InscriptionId = 22, Description = "312mg/5ml", BrandId = 17 },                        
                new Medicine { Id = 62, GenericId = 38, InscriptionId = 27, Description = "27.5mgm/spray", BrandId = 18 },
                new Medicine { Id = 63, GenericId = 8, InscriptionId = 24, Description = "500mg", BrandId = 19 },
                new Medicine { Id = 64, GenericId = 8, InscriptionId = 24, Description = "250mg", BrandId = 19 },
                new Medicine { Id = 65, GenericId = 8, InscriptionId = 22, Description = "200mg/5ml", BrandId = 19 },
                new Medicine { Id = 66, GenericId = 29, InscriptionId = 24, Description = "4oomg/80mg", BrandId = 20 },
                new Medicine { Id = 67, GenericId = 58, InscriptionId = 25, Description = "Cream", BrandId = 21 },
                new Medicine { Id = 68, GenericId = 10, InscriptionId = 23, Description = "1mg/1ml", BrandId = 22 },
                new Medicine { Id = 69, GenericId = 10, InscriptionId = 24, Description = "10mg", BrandId = 22 },
                new Medicine { Id = 70, GenericId = 28, InscriptionId = 22, Description = "125mg/5ml", BrandId = 23 },
                new Medicine { Id = 71, GenericId = 28, InscriptionId = 22, Description = "250mg/5ml", BrandId = 23 },
                new Medicine { Id = 72, GenericId = 64, InscriptionId = 22, Description = "120mg/5ml", BrandId = 24 },
                new Medicine { Id = 73, GenericId = 64, InscriptionId = 24, Description = "500mg", BrandId = 24 },
                new Medicine { Id = 74, GenericId = 64, InscriptionId = 23, Description = "250mg/5ml", BrandId = 24 },
                new Medicine { Id = 75, GenericId = 64, InscriptionId = 24, Description = "250mg", BrandId = 24 },
                new Medicine { Id = 76, GenericId = 64, InscriptionId = 24, Description = "325mg", BrandId = 24 },
                new Medicine { Id = 77, GenericId = 64, InscriptionId = 5, Description = "100mg/ml", BrandId = 24 },
                new Medicine { Id = 78, GenericId = 81, InscriptionId = 23, Description = "1.5mg/5ml", BrandId = 25 },
                new Medicine { Id = 79, GenericId = 76, InscriptionId = 23, Description = null, BrandId = 26 },
                new Medicine { Id = 80, GenericId = 67, InscriptionId = 23, Description = "5mg/1mg/5ml", BrandId = 27 },
                new Medicine { Id = 81, GenericId = 67, InscriptionId = 23, Description = null, BrandId = 27 },
                new Medicine { Id = 82, GenericId = 67, InscriptionId = 5, Description = null, BrandId = 27 },
                new Medicine { Id = 83, GenericId = 15, InscriptionId = 13, Description = "Sachet", BrandId = 28 },
                new Medicine { Id = 84, GenericId = 64, InscriptionId = 22, Description = "250mg/5ml", BrandId = 29 },
                new Medicine { Id = 85, GenericId = 64, InscriptionId = 24, Description = "250mg", BrandId = 29 },
                new Medicine { Id = 86, GenericId = 64, InscriptionId = 24, Description = "500mg", BrandId = 29 },
                new Medicine { Id = 87, GenericId = 64, InscriptionId = 24, Description = "325mg", BrandId = 29 },
                new Medicine { Id = 88, GenericId = 64, InscriptionId = 23, Description = "120mg/5ml", BrandId = 29 },
                new Medicine { Id = 89, GenericId = 64, InscriptionId = 5, Description = "100mg/ml", BrandId = 29 },
                new Medicine { Id = 90, GenericId = 17, InscriptionId = 22, Description = "250mg/5ml", BrandId = 30 },
                new Medicine { Id = 91, GenericId = 17, InscriptionId = 22, Description = "125mg/5ml", BrandId = 30 },
                new Medicine { Id = 92, GenericId = 18, InscriptionId = 5, Description = "50mg/ml", BrandId = 30 },
                new Medicine { Id = 93, GenericId = 19, InscriptionId = 3, Description = "500mg", BrandId = 31 },
                new Medicine { Id = 94, GenericId = 19, InscriptionId = 22, Description = "250mg/5ml", BrandId = 31 },
                new Medicine { Id = 95, GenericId = 19, InscriptionId = 22, Description = "125mg/5ml", BrandId = 31 },
                new Medicine { Id = 96, GenericId = 19, InscriptionId = 5, Description = "100mg/ml", BrandId = 31 },
                new Medicine { Id = 97, GenericId = 19, InscriptionId = 22, Description = "250mg/5ml", BrandId = 32 },
                new Medicine { Id = 98, GenericId = 19, InscriptionId = 22, Description = "125mg/5ml", BrandId = 32 },
                new Medicine { Id = 99, GenericId = 19, InscriptionId = 5, Description = "100mg/ml", BrandId = 32 },
                new Medicine { Id = 100, GenericId = 57, InscriptionId = 5, Description = null, BrandId = 33 },
                new Medicine { Id = 101, GenericId = 23, InscriptionId = 3, Description = "500mg", BrandId = 34 },
                new Medicine { Id = 102, GenericId = 23, InscriptionId = 22, Description = "125mg/5ml", BrandId = 34 },
                new Medicine { Id = 103, GenericId = 23, InscriptionId = 3, Description = "250mg", BrandId = 34 },
                new Medicine { Id = 104, GenericId = 24, InscriptionId = 22, Description = "125mg/5ml", BrandId = 35 },
                new Medicine { Id = 105, GenericId = 24, InscriptionId = 24, Description = "125mg/5ml", BrandId = 36 },
                new Medicine { Id = 106, GenericId = 24, InscriptionId = 24, Description = "500mg", BrandId = 36 },
                new Medicine { Id = 107, GenericId = 24, InscriptionId = 22, Description = "250mg/5ml", BrandId = 36 },
                new Medicine { Id = 108, GenericId = 24, InscriptionId = 22, Description = "125mg/5ml", BrandId = 37 },
                new Medicine { Id = 109, GenericId = 24, InscriptionId = 24, Description = "250mg", BrandId = 38 },
                new Medicine { Id = 110, GenericId = 24, InscriptionId = 24, Description = "500mg", BrandId = 38 },
                new Medicine { Id = 111, GenericId = 24, InscriptionId = 22, Description = "250mg/5ml", BrandId = 38 },
                new Medicine { Id = 112, GenericId = 24, InscriptionId = 22, Description = "125mg/5ml", BrandId = 38 },
                new Medicine { Id = 113, GenericId = 26, InscriptionId = 4, Description = "Tube", BrandId = 39 },
                new Medicine { Id = 114, GenericId = 74, InscriptionId = 24, Description = "125mg", BrandId = 40 },
                new Medicine { Id = 115, GenericId = 74, InscriptionId = 22, Description = "125mg/5ml", BrandId = 40 },
                new Medicine { Id = 116, GenericId = 77, InscriptionId = 12, Description = null, BrandId = 41 },
                new Medicine { Id = 117, GenericId = 54, InscriptionId = 14, Description = "Tube", BrandId = 42 },
                new Medicine { Id = 118, GenericId = 25, InscriptionId = 22, Description = "75mg/5ml", BrandId = 43 },
                new Medicine { Id = 119, GenericId = 30, InscriptionId = 28, Description = "400mg", BrandId = 44 },
                new Medicine { Id = 120, GenericId = 33, InscriptionId = 23, Description = "100mg/5ml", BrandId = 45 },
                new Medicine { Id = 121, GenericId = 33, InscriptionId = 24, Description = "100mg", BrandId = 45 },
                new Medicine { Id = 122, GenericId = 13, InscriptionId = 5, Description = null, BrandId = 46},
                new Medicine { Id = 123, GenericId = 13, InscriptionId = 23, Description = null, BrandId = 46 },
                new Medicine { Id = 124, GenericId = 68, InscriptionId = 23, Description = null, BrandId = 47 },
                new Medicine { Id = 125, GenericId = 68, InscriptionId = 5, Description = null, BrandId = 47 },
                new Medicine { Id = 126, GenericId = 47, InscriptionId = 22, Description = "200mg/5ml", BrandId = 48 },
                new Medicine { Id = 127, GenericId = 47, InscriptionId = 22, Description = "100mg/5ml", BrandId = 48 },
                new Medicine { Id = 128, GenericId = 47, InscriptionId = 5, Description = "100mg/2.5ml", BrandId = 48 },
                new Medicine { Id = 129, GenericId = 52, InscriptionId = 3, Description = "250mg", BrandId = 49 },
                new Medicine { Id = 130, GenericId = 52, InscriptionId = 3, Description = "500mg", BrandId = 49 },
                new Medicine { Id = 131, GenericId = 77, InscriptionId = 12, Description = null, BrandId = 50 },
                new Medicine { Id = 132, GenericId = 83, InscriptionId = 23, Description = null, BrandId = 51 },
                new Medicine { Id = 133, GenericId = 83, InscriptionId = 5, Description = null, BrandId = 51 },
                new Medicine { Id = 134, GenericId = 55, InscriptionId = 8, Description = null, BrandId = 52 },
                new Medicine { Id = 135, GenericId = 55, InscriptionId = 4, Description = null, BrandId = 52 },
                new Medicine { Id = 136, GenericId = 9, InscriptionId = 15, Description = null, BrandId = 53 },
                new Medicine { Id = 137, GenericId = 60, InscriptionId = 22, Description = "218mg/5ml", BrandId = 54 },
                new Medicine { Id = 138, GenericId = 60, InscriptionId = 3, Description = "200mg", BrandId = 54 },            
                new Medicine { Id = 139, GenericId = 69, InscriptionId = 3, Description = "300mg", BrandId = 55 },
                new Medicine { Id = 140, GenericId = 4, InscriptionId = 24, Description = "300mg", BrandId = 56 },
                new Medicine { Id = 141, GenericId = 4, InscriptionId = 23, Description = "30mg/5ml", BrandId = 56 },
                new Medicine { Id = 142, GenericId = 4, InscriptionId = 5, Description = "7.5mg/5ml", BrandId = 56 },
                new Medicine { Id = 143, GenericId = 4, InscriptionId = 23, Description = "15mg/2.5ml", BrandId = 56 },
                new Medicine { Id = 144, GenericId = 47, InscriptionId = 3, Description = "400mg", BrandId = 57 },
                new Medicine { Id = 145, GenericId = 47, InscriptionId = 3, Description = "200mg", BrandId = 57 },
                new Medicine { Id = 146, GenericId = 53, InscriptionId = 24, Description = "500mg", BrandId = 58 },
                new Medicine { Id = 147, GenericId = 53, InscriptionId = 23, Description = "25mg/1ml", BrandId = 58 },
                new Medicine { Id = 148, GenericId = 53, InscriptionId = null, Description = null, BrandId = 58 },
                new Medicine { Id = 149, GenericId = 59, InscriptionId = 24, Description = "550mg", BrandId = 59 },
                new Medicine { Id = 150, GenericId = 59, InscriptionId = 24, Description = "275mg", BrandId = 59 },
                new Medicine { Id = 151, GenericId = 1, InscriptionId = 18, Description = "1000mg", BrandId = 60 },
                new Medicine { Id = 152, GenericId = 1, InscriptionId = 23, Description = "100mg/5ml", BrandId = 60 },
                new Medicine { Id = 153, GenericId = 1, InscriptionId = 18, Description = "200mg", BrandId = 60 },
                new Medicine { Id = 154, GenericId = 42, InscriptionId = 13, Description = "Tube", BrandId = 61 },
                new Medicine { Id = 155, GenericId = 40, InscriptionId = 13, Description = "Tube", BrandId = 62 },
                new Medicine { Id = 156, GenericId = 39, InscriptionId = 6, Description = "Tube", BrandId = 63 },
                new Medicine { Id = 157, GenericId = 41, InscriptionId = 24, Description = "100mg", BrandId = 64 },
                new Medicine { Id = 158, GenericId = 41, InscriptionId = 22, Description = "16.7mg/5ml", BrandId = 64 },
                new Medicine { Id = 159, GenericId = 44, InscriptionId = 6, Description = null, BrandId = 65 },
                new Medicine { Id = 160, GenericId = 52, InscriptionId = 3, Description = "500mg", BrandId = 66 },
                new Medicine { Id = 161, GenericId = 52, InscriptionId = 3, Description = "250mg", BrandId = 66 },
                new Medicine { Id = 162, GenericId = 31, InscriptionId = 3, Description = "1mg/1ml", BrandId = 67 },
                new Medicine { Id = 163, GenericId = 6, InscriptionId = 3, Description = "500mg", BrandId = 68 },
                new Medicine { Id = 164, GenericId = 6, InscriptionId = 22, Description = "250mg/5ml", BrandId = 68 },
                new Medicine { Id = 165, GenericId = 6, InscriptionId = 5, Description = "100mg/ml", BrandId = 68 },
                new Medicine { Id = 166, GenericId = 13, InscriptionId = 23, Description = null, BrandId = 69 },
                new Medicine { Id = 167, GenericId = 13, InscriptionId = 5, Description = null, BrandId = 69 },
                new Medicine { Id = 168, GenericId = 63, InscriptionId = 18, Description = null, BrandId = 70 },
                new Medicine { Id = 169, GenericId = 35, InscriptionId = 22, Description = "250mg/5ml", BrandId = 71 },
                new Medicine { Id = 170, GenericId = 35, InscriptionId = 5, Description = "100mg/ml", BrandId = 71 },
                new Medicine { Id = 171, GenericId = 48, InscriptionId = 23, Description = "Bot", BrandId = 72 },
                new Medicine { Id = 172, GenericId = 46, InscriptionId = 24, Description = "25mg", BrandId = 73 },
                new Medicine { Id = 173, GenericId = 46, InscriptionId = 23, Description = "2mg/ml", BrandId = 73 },
                new Medicine { Id = 174, GenericId = 46, InscriptionId = 24, Description = "10mg", BrandId = 73 },
                new Medicine { Id = 175, GenericId = 11, InscriptionId = 23, Description = null, BrandId = 74 },
                new Medicine { Id = 176, GenericId = 11, InscriptionId = 3, Description = null, BrandId = 74 },
                new Medicine { Id = 177, GenericId = 56, InscriptionId = 24, Description = "4mg", BrandId = 75 },
                new Medicine { Id = 178, GenericId = 56, InscriptionId = 24, Description = "10mg", BrandId = 75 },
                new Medicine { Id = 179, GenericId = 56, InscriptionId = 24, Description = "5mg", BrandId = 75 },
                new Medicine { Id = 180, GenericId = 29, InscriptionId = 26, Description = "200mg/40mg/5ml", BrandId = 76 },
                new Medicine { Id = 181, GenericId = 24, InscriptionId = 24, Description = "500mg", BrandId = 77 },
                new Medicine { Id = 182, GenericId = 24, InscriptionId = 22, Description = "125mg/5ml", BrandId = 77 },
                new Medicine { Id = 183, GenericId = 24, InscriptionId = 24, Description = "250mg", BrandId = 77 },
                new Medicine { Id = 184, GenericId = 24, InscriptionId = 22, Description = "250mg/5ml", BrandId = 77 },
                new Medicine { Id = 185, GenericId = 24, InscriptionId = 24, Description = "500mg", BrandId = 78 },
                new Medicine { Id = 186, GenericId = 24, InscriptionId = 22, Description = "250mg/5ml", BrandId = 78 },
                new Medicine { Id = 187, GenericId = 24, InscriptionId = 22, Description = "125mg/5ml", BrandId = 78 },
                new Medicine { Id = 188, GenericId = 24, InscriptionId = 24, Description = "250mg", BrandId = 78 },
                new Medicine { Id = 189, GenericId = 5, InscriptionId = 10, Description = null, BrandId = 79 },
                new Medicine { Id = 190, GenericId = 16, InscriptionId = 23, Description = "100mg/5ml", BrandId = 80 },
                new Medicine { Id = 191, GenericId = 16, InscriptionId = 5, Description = "50mg/ml", BrandId = 80 },
                new Medicine { Id = 192, GenericId = 3, InscriptionId = 24, Description = null, BrandId = 81 },
                new Medicine { Id = 193, GenericId = 3, InscriptionId = 22, Description = null, BrandId = 81 },
                new Medicine { Id = 194, GenericId = 47, InscriptionId = 3, Description = "200mg", BrandId = 82 },
                new Medicine { Id = 195, GenericId = 73, InscriptionId = 24, Description = "25mgm", BrandId = 83 },
                new Medicine { Id = 196, GenericId = 73, InscriptionId = 24, Description = "50mgm", BrandId = 83 },
                new Medicine { Id = 197, GenericId = 73, InscriptionId = 23, Description = "5mgm/ml", BrandId = 83 },
                new Medicine { Id = 198, GenericId = 56, InscriptionId = 24, Description = "5mg", BrandId = 84 },
                new Medicine { Id = 199, GenericId = 56, InscriptionId = 24, Description = "10mg", BrandId = 84 },
                new Medicine { Id = 200, GenericId = 56, InscriptionId = 24, Description = "4mg", BrandId = 84 },
                new Medicine { Id = 201, GenericId = 56, InscriptionId = 24, Description = "5mg", BrandId = 85 },
                new Medicine { Id = 202, GenericId = 56, InscriptionId = 24, Description = "10mg", BrandId = 85 },
                new Medicine { Id = 203, GenericId = 56, InscriptionId = 24, Description = "4mg", BrandId = 85 },
                new Medicine { Id = 204, GenericId = 56, InscriptionId = 7, Description = "4mg", BrandId = 85 },
                new Medicine { Id = 205, GenericId = 32, InscriptionId = 24, Description = "10mg", BrandId = 86 },
                new Medicine { Id = 206, GenericId = 49, InscriptionId = 23, Description = "3.3g/5ml", BrandId = 87 },
                new Medicine { Id = 207, GenericId = 80, InscriptionId = 11, Description = null, BrandId = 88 },
                new Medicine { Id = 208, GenericId = 80, InscriptionId = 27, Description = null, BrandId = 88 },
                new Medicine { Id = 209, GenericId = 4, InscriptionId = 5, Description = "7.5mg/ml", BrandId = 89 },
                new Medicine { Id = 210, GenericId = 34, InscriptionId = 24, Description = "50mg", BrandId = 90 },
                new Medicine { Id = 211, GenericId = 64, InscriptionId = 23, Description = "120mg/5ml", BrandId = 91 },
                new Medicine { Id = 212, GenericId = 64, InscriptionId = 23, Description = "250mg/5ml", BrandId = 91 },
                new Medicine { Id = 213, GenericId = 64, InscriptionId = 5, Description = "100ml", BrandId = 91 },
                new Medicine { Id = 214, GenericId = 64, InscriptionId = 5, Description = "100ml", BrandId = 92 },
                new Medicine { Id = 215, GenericId = 64, InscriptionId = 23, Description = "250mg/5ml", BrandId = 92 },
                new Medicine { Id = 216, GenericId = 64, InscriptionId = 23, Description = "250mg/5ml", BrandId = 93 },
                new Medicine { Id = 217, GenericId = 64, InscriptionId = 5, Description = "100mg/ml", BrandId = 93 },
                new Medicine { Id = 218, GenericId = 13, InscriptionId = 23, Description = null, BrandId = 94 },
                new Medicine { Id = 219, GenericId = 13, InscriptionId = 5, Description = null, BrandId = 94 },
                new Medicine { Id = 220, GenericId = 65, InscriptionId = 23, Description = "250mg/12.5mg", BrandId = 95 },
                new Medicine { Id = 221, GenericId = 65, InscriptionId = 3, Description = "325mg/25mg", BrandId = 95 },
                new Medicine { Id = 222, GenericId = 80, InscriptionId = 27, Description = null, BrandId = 96 },
                new Medicine { Id = 223, GenericId = 80, InscriptionId = 11, Description = null, BrandId = 96 },
                new Medicine { Id = 224, GenericId = 28, InscriptionId = 22, Description = "125mg/5ml", BrandId = 97 },
                new Medicine { Id = 225, GenericId = 28, InscriptionId = 22, Description = "250mg/5ml", BrandId = 97 },
                new Medicine { Id = 226, GenericId = 67, InscriptionId = 23, Description = null, BrandId = 98 },
                new Medicine { Id = 227, GenericId = 67, InscriptionId = 5, Description = null, BrandId = 98 },
                new Medicine { Id = 228, GenericId = 82, InscriptionId = 23, Description = "26.7mg/5ml", BrandId = 99 },
                new Medicine { Id = 229, GenericId = 62, InscriptionId = 3, Description = "20 Mg", BrandId = 100 },
                new Medicine { Id = 230, GenericId = 64, InscriptionId = 21, Description = "125mg", BrandId = 101 },
                new Medicine { Id = 231, GenericId = 64, InscriptionId = 21, Description = "250mg/5ml", BrandId = 101 },
                new Medicine { Id = 232, GenericId = 71, InscriptionId = 23, Description = "20mg/5ml", BrandId = 102 },
                new Medicine { Id = 233, GenericId = 61, InscriptionId = 22, Description = "100,000 Iu", BrandId = 103 },
                new Medicine { Id = 234, GenericId = 23, InscriptionId = 22, Description = "125mg/5ml", BrandId = 104 },
                new Medicine { Id = 235, GenericId = 23, InscriptionId = 3, Description = "250mg/5ml", BrandId = 104 },
                new Medicine { Id = 236, GenericId = 23, InscriptionId = 3, Description = "500mg", BrandId = 104 },
                new Medicine { Id = 237, GenericId = 6, InscriptionId = 22, Description = "250mg/5ml", BrandId = 105 },
                new Medicine { Id = 238, GenericId = 6, InscriptionId = 22, Description = "125mg/5ml", BrandId = 105 },
                new Medicine { Id = 239, GenericId = 6, InscriptionId = 5, Description = "100mg/ml", BrandId = 105 },
                new Medicine { Id = 240, GenericId = 13, InscriptionId = 23, Description = null, BrandId = 106 },
                new Medicine { Id = 241, GenericId = 13, InscriptionId = 5, Description = null, BrandId = 106 },
                new Medicine { Id = 242, GenericId = 23, InscriptionId = 23, Description = "125mg/5ml", BrandId = 107 },
                new Medicine { Id = 243, GenericId = 23, InscriptionId = 3, Description = "250mg", BrandId = 107 },
                new Medicine { Id = 244, GenericId = 23, InscriptionId = 3, Description = "500mg", BrandId = 107 },
                new Medicine { Id = 245, GenericId = 27, InscriptionId = 22, Description = "250mg/5ml", BrandId = 108 },
                new Medicine { Id = 246, GenericId = 27, InscriptionId = 22, Description = "250mg/5ml", BrandId = 108 },
                new Medicine { Id = 247, GenericId = 27, InscriptionId = 22, Description = "125mg/5ml", BrandId = 108 },
                new Medicine { Id = 248, GenericId = 70, InscriptionId = 19, Description = null, BrandId = 109 },
                new Medicine { Id = 249, GenericId = 70, InscriptionId = 1, Description = null, BrandId = 109 },
                new Medicine { Id = 250, GenericId = 7, InscriptionId = null, Description = "1gm", BrandId = 110 },
                new Medicine { Id = 251, GenericId = 7, InscriptionId = null, Description = "750mg", BrandId = 110 },
                new Medicine { Id = 252, GenericId = 7, InscriptionId = null, Description = "500mg", BrandId = 110 },
                new Medicine { Id = 253, GenericId = 7, InscriptionId = null, Description = "250mg", BrandId = 110 },
                new Medicine { Id = 254, GenericId = 52, InscriptionId = 3, Description = "500mg", BrandId = 111 },
                new Medicine { Id = 255, GenericId = 52, InscriptionId = 22, Description = "50mg/5ml", BrandId = 111 },
                new Medicine { Id = 256, GenericId = 52, InscriptionId = 3, Description = "250mg", BrandId = 111 },
                new Medicine { Id = 257, GenericId = 64, InscriptionId = 21, Description = "125mg", BrandId = 112 },
                new Medicine { Id = 258, GenericId = 64, InscriptionId = 21, Description = "250mg", BrandId = 112 },
                new Medicine { Id = 259, GenericId = 72, InscriptionId = null, Description = null, BrandId = 113 },
                new Medicine { Id = 260, GenericId = 72, InscriptionId = 23, Description = "10mg/5ml", BrandId = 113 },
                new Medicine { Id = 261, GenericId = 71, InscriptionId = 23, Description = "20mg/5ml", BrandId = 114 },
                new Medicine { Id = 262, GenericId = 57, InscriptionId = 23, Description = null, BrandId = 115 },
                new Medicine { Id = 263, GenericId = 27, InscriptionId = 22, Description = "250mg/5ml", BrandId = 116 },
                new Medicine { Id = 264, GenericId = 27, InscriptionId = 22, Description = "250mg/5ml", BrandId = 116 },
                new Medicine { Id = 265, GenericId = 27, InscriptionId = 22, Description = "125mg/5ml", BrandId = 116 },
                new Medicine { Id = 266, GenericId = 75, InscriptionId = 12, Description = "2.5mg/2.5ml", BrandId = 117 },
                new Medicine { Id = 267, GenericId = 75, InscriptionId = 24, Description = "2mg", BrandId = 118 },
                new Medicine { Id = 268, GenericId = 75, InscriptionId = 23, Description = "2mg/5ml", BrandId = 118 },
                new Medicine { Id = 269, GenericId = 77, InscriptionId = 12, Description = null, BrandId = 119 },
                new Medicine { Id = 270, GenericId = 81, InscriptionId = 23, Description = "1.5mg/5ml", BrandId = 120 },
                new Medicine { Id = 271, GenericId = 79, InscriptionId = 5, Description = null, BrandId = 121 },
                new Medicine { Id = 272, GenericId = 27, InscriptionId = 22, Description = "250mg/5ml", BrandId = 122 },
                new Medicine { Id = 273, GenericId = 27, InscriptionId = 22, Description = "250mg/5ml", BrandId = 122 },
                new Medicine { Id = 274, GenericId = 27, InscriptionId = 22, Description = "125mg/5ml", BrandId = 122 },
                new Medicine { Id = 275, GenericId = 51, InscriptionId = 23, Description = "125mg/5ml", BrandId = 123 },
                new Medicine { Id = 276, GenericId = 71, InscriptionId = 23, Description = "20mg/5ml", BrandId = 124 },
                new Medicine { Id = 277, GenericId = 7, InscriptionId = null, Description = "250mg", BrandId = 125 },
                new Medicine { Id = 278, GenericId = 7, InscriptionId = null, Description = "1gm", BrandId = 125 },
                new Medicine { Id = 279, GenericId = 7, InscriptionId = null, Description = "750mg", BrandId = 125 },
                new Medicine { Id = 280, GenericId = 7, InscriptionId = null, Description = "500mg", BrandId = 125 },
                new Medicine { Id = 281, GenericId = 80, InscriptionId = 27, Description = null, BrandId = 126 },
                new Medicine { Id = 282, GenericId = 80, InscriptionId = 11, Description = null, BrandId = 126 },
                new Medicine { Id = 283, GenericId = 36, InscriptionId = 23, Description = null, BrandId = 127 },
                new Medicine { Id = 284, GenericId = 19, InscriptionId = 22, Description = "250mg/5ml", BrandId = 128 },
                new Medicine { Id = 285, GenericId = 19, InscriptionId = 22, Description = "125mg/5ml", BrandId = 128 },
                new Medicine { Id = 286, GenericId = 19, InscriptionId = 5, Description = "100mg/ml", BrandId = 128 },
                new Medicine { Id = 287, GenericId = 78, InscriptionId = 9, Description = "25/250", BrandId = 129 },
                new Medicine { Id = 288, GenericId = 78, InscriptionId = 9, Description = "25/125", BrandId = 129 },
                new Medicine { Id = 289, GenericId = 78, InscriptionId = 9, Description = "25/50", BrandId = 129 },
                new Medicine { Id = 290, GenericId = 56, InscriptionId = 24, Description = "10mg", BrandId = 130 },
                new Medicine { Id = 291, GenericId = 56, InscriptionId = 24, Description = "5mg", BrandId = 130 },
                new Medicine { Id = 292, GenericId = 56, InscriptionId = 24, Description = "4mg", BrandId = 130 },
                new Medicine { Id = 293, GenericId = 56, InscriptionId = 7, Description = "4mg", BrandId = 130 },
                new Medicine { Id = 294, GenericId = 59, InscriptionId = 24, Description = "550mg", BrandId = 131 },
                new Medicine { Id = 295, GenericId = 59, InscriptionId = 24, Description = "275mg", BrandId = 131 },
                new Medicine { Id = 296, GenericId = 16, InscriptionId = 23, Description = "100mg/5ml", BrandId = 132 },
                new Medicine { Id = 297, GenericId = 16, InscriptionId = 5, Description = "50mg/ml", BrandId = 132 },
                new Medicine { Id = 298, GenericId = 76, InscriptionId = 23, Description = null, BrandId = 133 },
                new Medicine { Id = 299, GenericId = 37, InscriptionId = 3, Description = "500mg", BrandId = 134 },
                new Medicine { Id = 300, GenericId = 37, InscriptionId = 3, Description = "250mg", BrandId = 134 },
                new Medicine { Id = 301, GenericId = 37, InscriptionId = 22, Description = "125mg/5ml", BrandId = 134 },
                new Medicine { Id = 302, GenericId = 66, InscriptionId = 3, Description = "250mg", BrandId = 135 },
                new Medicine { Id = 303, GenericId = 66, InscriptionId = 3, Description = "500mg", BrandId = 135 },
                new Medicine { Id = 304, GenericId = 64, InscriptionId = 22, Description = "250mg/5ml", BrandId = 136 },
                new Medicine { Id = 305, GenericId = 64, InscriptionId = 23, Description = "120mg/5ml", BrandId = 136 },
                new Medicine { Id = 306, GenericId = 64, InscriptionId = 24, Description = "250mg", BrandId = 136 },
                new Medicine { Id = 307, GenericId = 64, InscriptionId = 23, Description = "250mg/5ml", BrandId = 136 },
                new Medicine { Id = 308, GenericId = 64, InscriptionId = 24, Description = "500mg", BrandId = 136 },
                new Medicine { Id = 309, GenericId = 64, InscriptionId = 24, Description = "325mg", BrandId = 136 },
                new Medicine { Id = 310, GenericId = 64, InscriptionId = 5, Description = "100mg/ml", BrandId = 136 },
                new Medicine { Id = 311, GenericId = 20, InscriptionId = 3, Description = "100mg", BrandId = 137 },
                new Medicine { Id = 312, GenericId = 20, InscriptionId = 22, Description = "100mg/5ml", BrandId = 137 },
                new Medicine { Id = 313, GenericId = 20, InscriptionId = 3, Description = "200mg", BrandId = 137 },
                new Medicine { Id = 314, GenericId = 20, InscriptionId = 5, Description = "20mg/ml", BrandId = 137 },
                new Medicine { Id = 315, GenericId = 29, InscriptionId = 22, Description = "400mg/80/5ml", BrandId = 138 },
                new Medicine { Id = 316, GenericId = 20, InscriptionId = 3, Description = "200mg", BrandId = 139 },
                new Medicine { Id = 317, GenericId = 20, InscriptionId = 5, Description = "20mg/ml", BrandId = 139 },
                new Medicine { Id = 318, GenericId = 20, InscriptionId = 5, Description = "100mg/5ml", BrandId = 139 },
                new Medicine { Id = 319, GenericId = 20, InscriptionId = 3, Description = "100mg", BrandId = 139 },
                new Medicine { Id = 320, GenericId = 75, InscriptionId = 12, Description = "2.5mg/2.5ml", BrandId = 140 },
                new Medicine { Id = 321, GenericId = 75, InscriptionId = 9, Description = "100mgm/Inhalation", BrandId = 140 },
                new Medicine { Id = 322, GenericId = 75, InscriptionId = 24, Description = "2mg", BrandId = 140 },
                new Medicine { Id = 323, GenericId = 76, InscriptionId = 23, Description = null, BrandId = 141 },
                new Medicine { Id = 324, GenericId = 22, InscriptionId = 5, Description = "10mg/ml", BrandId = 142 },
                new Medicine { Id = 325, GenericId = 22, InscriptionId = 20, Description = "1mg/ml", BrandId = 142 },
                new Medicine { Id = 326, GenericId = 32, InscriptionId = 5, Description = "5mg/ml", BrandId = 143 },
                new Medicine { Id = 327, GenericId = 32, InscriptionId = 23, Description = "5mg/5ml", BrandId = 143 },
                new Medicine { Id = 328, GenericId = 17, InscriptionId = 22, Description = "125mg/5ml", BrandId = 144 },
                new Medicine { Id = 329, GenericId = 17, InscriptionId = 22, Description = "250mg/5ml", BrandId = 144 },
                new Medicine { Id = 330, GenericId = 17, InscriptionId = 5, Description = "50mg/ml", BrandId = 144 },
                new Medicine { Id = 331, GenericId = 19, InscriptionId = 22, Description = "250mg/5ml", BrandId = 145 },
                new Medicine { Id = 332, GenericId = 19, InscriptionId = 22, Description = "125mg/5ml", BrandId = 145 },
                new Medicine { Id = 333, GenericId = 19, InscriptionId = 5, Description = "100mg/ml", BrandId = 145 },
                new Medicine { Id = 334, GenericId = 50, InscriptionId = 23, Description = "5mg/ml", BrandId = 146 },
                new Medicine { Id = 335, GenericId = 50, InscriptionId = 24, Description = "5mg", BrandId = 146 },
                new Medicine { Id = 336, GenericId = 50, InscriptionId = 5, Description = "5mg/ml", BrandId = 146 },
                new Medicine { Id = 337, GenericId = 13, InscriptionId = 5, Description = null, BrandId = 147 },
                new Medicine { Id = 338, GenericId = 13, InscriptionId = 23, Description = null, BrandId = 147 },
                new Medicine { Id = 339, GenericId = 21, InscriptionId = 3, Description = "250mg", BrandId = 148 },
                new Medicine { Id = 340, GenericId = 8, InscriptionId = 24, Description = "500mg", BrandId = 149 },
                new Medicine { Id = 341, GenericId = 8, InscriptionId = 24, Description = "250mg", BrandId = 149 },
                new Medicine { Id = 342, GenericId = 8, InscriptionId = 22, Description = "200mg/5ml", BrandId = 149 },
                new Medicine { Id = 343, GenericId = 21, InscriptionId = 22, Description = "250mg/5ml", BrandId = 150 },
                new Medicine { Id = 344, GenericId = 21, InscriptionId = 22, Description = "125mg/5ml", BrandId = 150 },
                new Medicine { Id = 345, GenericId = 8, InscriptionId = 24, Description = "500mg", BrandId = 151 },
                new Medicine { Id = 346, GenericId = 8, InscriptionId = 22, Description = "200mg/5ml", BrandId = 151 },
                new Medicine { Id = 347, GenericId = 8, InscriptionId = 24, Description = "250mg", BrandId = 152 },
                new Medicine { Id = 348, GenericId = 2, InscriptionId = 24, Description = "400mg", BrandId = 152 },
                new Medicine { Id = 349, GenericId = 2, InscriptionId = 24, Description = "200mg", BrandId = 152 },
                new Medicine { Id = 350, GenericId = 22, InscriptionId = 5, Description = "10mg/ml", BrandId = 153 },
                new Medicine { Id = 351, GenericId = 22, InscriptionId = 20, Description = "1mg/ml", BrandId = 153 },
                new Medicine { Id = 352, GenericId = 4, InscriptionId = 24, Description = "30mg", BrandId = 89 },
                new Medicine { Id = 353, GenericId = 4, InscriptionId = 23, Description = "30mg/5ml", BrandId = 89 },
                new Medicine { Id = 354, GenericId = 4, InscriptionId = 23, Description = "15mg/5ml", BrandId = 89 });
        }
    }
}
