using Microsoft.EntityFrameworkCore;
using SaintJudeHospital.Data.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace SaintJudeHospital.Data.Seed
{
    public class AppDbContextInitializer
    {
        private static ModelBuilder _builder;

        public static void Load(ModelBuilder builder)
        {
            _builder = builder;

            UsersRole();
            Users();
            Immunizes();
            Symtoms();
            Brands();
            Medicines();
        }

        private static void UsersRole()
        {
            _builder.Entity<Role>().HasData(
                new Role { RoleId = 1, Name = "Administrator" },
                new Role { RoleId = 2, Name = "StandardUser"});
        }

        private static void Users()
        {
            _builder.Entity<User>().HasData(
                new User { FirstName = "Carl", LastName = "Tanilon", Password = "1234", RoleId = 1, Username = "carl" , UserId = 1});
        }

        private static void Immunizes()
        {
            _builder.Entity<Immunize>().HasData(
                new Immunize { Id = 1, Name = "HEXA", Amount = 3000 },
                new Immunize { Id = 2, Name = "PCV 10", Amount = 3200 },
                new Immunize { Id = 3, Name = "MEASLES", Amount = 750 },
                new Immunize { Id = 4, Name = "HIB", Amount = 1300 },
                new Immunize { Id = 5, Name = "MENINGO", Amount = 4000 },
                new Immunize { Id = 6, Name = "TYPHOID", Amount = 1300 },
                new Immunize { Id = 7, Name = "HEP A", Amount = 1800 },
                new Immunize { Id = 8, Name = "HEP B", Amount = 700 },
                new Immunize { Id = 9, Name = "TETRAXIM", Amount = 1600 },
                new Immunize { Id = 10, Name = "MMR", Amount = 1200 },
                new Immunize { Id = 11, Name = "CHICKEN POX", Amount = 2200 },
                new Immunize { Id = 12, Name = "PENTA", Amount = 2500 },
                new Immunize { Id = 13, Name = "BCG-1", Amount = 900 },
                new Immunize { Id = 14, Name = "MMR-V", Amount = 3000 },
                new Immunize { Id = 15, Name = "PNEUMO-23", Amount = 1700 },
                new Immunize { Id = 16, Name = "RABIES", Amount = 1700 },
                new Immunize { Id = 17, Name = "ROTARIX", Amount = 3000 },
                new Immunize { Id = 18, Name = "ROTATEQ", Amount = 2200 },
                new Immunize { Id = 19, Name = "FLU", Amount = 1000 },
                new Immunize { Id = 20, Name = "PCV", Amount = 4000 },
                new Immunize { Id = 21, Name = "BCG-2", Amount = 0 });
        }

        private static void Symtoms()
        {
            _builder.Entity<Symtom>().HasData(
                new Symtom { Id = 1, Name = "Bleeding"},
                new Symtom { Id = 2, Name = "Bruise"},
                new Symtom { Id = 3, Name = "Cough"},
                new Symtom { Id = 4, Name = "Bites"},
                new Symtom { Id = 5, Name = "Fever"},
                new Symtom { Id = 6, Name = "Cold"},
                new Symtom { Id = 7, Name = "Difficulty in swallowing" },
                new Symtom { Id = 8, Name = "Ear discharge"},
                new Symtom { Id = 9, Name = "Ear ache/pain"},
                new Symtom { Id = 10, Name = "Constipation"},
                new Symtom { Id = 11, Name = "Diarrhea"},
                new Symtom { Id = 12, Name = "Hair fall"},
                new Symtom { Id = 13, Name = "Abdominal pain"},
                new Symtom { Id = 14, Name = "Deformity"},
                new Symtom { Id = 15, Name = "Headache"},
                new Symtom { Id = 16, Name = "Infected wounds"},
                new Symtom { Id = 17, Name = "Itchness"},
                new Symtom { Id = 18, Name = "Loss of consciousness"},
                new Symtom { Id = 19, Name = "Mass"},
                new Symtom { Id = 20, Name = "Joint pain"},
                new Symtom { Id = 21, Name = "Muscle pain"},
                new Symtom { Id = 22, Name = "Skin lesions"},
                new Symtom { Id = 23, Name = "Trauma"},
                new Symtom { Id = 24, Name = "Pain urination"},
                new Symtom { Id = 25, Name = "Rushes"},
                new Symtom { Id = 26, Name = "Less appetite"},
                new Symtom { Id = 27, Name = "LBM"},
                new Symtom { Id = 28, Name = "Vomiting"},
                new Symtom { Id = 29, Name = "Dysuria"},
                new Symtom { Id = 30, Name = "Rashes"},
                new Symtom { Id = 31, Name = "Dysphagia"},
                new Symtom { Id = 32, Name = "Vaginal Discharge"},
                new Symtom { Id = 33, Name = "Urticarial rash"},
                new Symtom { Id = 34, Name = "Eye discharge"},
                new Symtom { Id = 35, Name = "Chest gurgling"},
                new Symtom { Id = 36, Name = "Epistaxis"},
                new Symtom { Id = 37, Name = "Pustules"},
                new Symtom { Id = 38, Name = "Nasal congestion"});
        }

        private static void Brands()
        {
            _builder.Entity<Brand>().HasData(
                new Brand { Id = 1, Name = "Activent" },
                new Brand { Id = 2, Name = "Advil" },
                new Brand { Id = 3, Name = "Allerkid" },
                new Brand { Id = 4, Name = "Alloxygen" },
                new Brand { Id = 5, Name = "Alnix" },
                new Brand { Id = 6, Name = "Alvedon" },
                new Brand { Id = 7, Name = "Ambrolex" },
                new Brand { Id = 8, Name = "Amoclav" },
                new Brand { Id = 9, Name = "Amoxil" },
                new Brand { Id = 10, Name = "Ampicin" },
                new Brand { Id = 11, Name = "Ansimar" },
                new Brand { Id = 12, Name = "Antiox" },
                new Brand { Id = 13, Name = "Asfrenon" },
                new Brand { Id = 14, Name = "Asfrenon Expt" },
                new Brand { Id = 15, Name = "Asmalin" },
                new Brand { Id = 16, Name = "Asmalin Broncho" },
                new Brand { Id = 17, Name = "Augmentin" },
                new Brand { Id = 18, Name = "Avamys" },
                new Brand { Id = 19, Name = "Azith" },
                new Brand { Id = 20, Name = "Bacidal" },
                new Brand { Id = 21, Name = "Bactroban" },
                new Brand { Id = 22, Name = "Bambec"},
                new Brand { Id = 23, Name = "Bioclauid" },
                new Brand { Id = 24, Name = "Biogesic" },
                new Brand { Id = 25, Name = "Bricanyl" },
                new Brand { Id = 26, Name = "Broncaire Expt" },
                new Brand { Id = 27, Name = "Bronchofen" },
                new Brand { Id = 28, Name = "Calmoseptine" },
                new Brand { Id = 29, Name = "Calpol" },
                new Brand { Id = 30, Name = "Ceclor" },
                new Brand { Id = 31, Name = "Cefalin" },
                new Brand { Id = 32, Name = "Ceporex" },
                new Brand { Id = 33, Name = "Cherifer" },
                new Brand { Id = 34, Name = "Chloromycetin" },
                new Brand { Id = 35, Name = "Clariget" },
                new Brand { Id = 36, Name = "Clarithro-Natrapharm Klaryz" },
                new Brand { Id = 37, Name = "Clarithro-natrapharm" },
                new Brand { Id = 38, Name = "Clarithrocid" },
                new Brand { Id = 39, Name = "Clotrasone" },
                new Brand { Id = 40, Name = "Combantrin" },
                new Brand { Id = 41, Name = "Combivent" },
                new Brand { Id = 42, Name = "Daktarin" },
                new Brand { Id = 43, Name = "Dalacin C" },
                new Brand { Id = 44, Name = "Dg" },
                new Brand { Id = 45, Name = "Dilatair" },
                new Brand { Id = 46, Name = "Dimetapp" },
                new Brand { Id = 47, Name = "Disudrin" },
                new Brand { Id = 48, Name = "Dolan" },
                new Brand { Id = 49, Name = "Dolfenal" },
                new Brand { Id = 50, Name = "Duavent" },
                new Brand { Id = 51, Name = "E Zinc" },
                new Brand { Id = 52, Name = "Elica" },
                new Brand { Id = 53, Name = "Erceflora" },
                new Brand { Id = 54, Name = "Ercefuryl" },
                new Brand { Id = 55, Name = "Essentiale Forte" },
                new Brand { Id = 56, Name = "Expel" },
                new Brand { Id = 57, Name = "Faspic" },
                new Brand { Id = 58, Name = "Flagyl" },
                new Brand { Id = 59, Name = "Flanax" },
                new Brand { Id = 60, Name = "Fluimucil" },
                new Brand { Id = 61, Name = "Fucidin" },
                new Brand { Id = 62, Name = "Fucidin-h" },
                new Brand { Id = 63, Name = "Fucithalmic" },
                new Brand { Id = 64, Name = "Furoxone" },
                new Brand { Id = 65, Name = "Garamycin" },
                new Brand { Id = 66, Name = "Gardan" },
                new Brand { Id = 67, Name = "Heraclene" },
                new Brand { Id = 68, Name = "Himox" },
                new Brand { Id = 69, Name = "Hisdec" },
                new Brand { Id = 70, Name = "Hydrite" },
                new Brand { Id = 71, Name = "Ilosone" },
                new Brand { Id = 72, Name = "Immunosine" },
                new Brand { Id = 73, Name = "Iterax" },
                new Brand { Id = 74, Name = "Jetepar" },
                new Brand { Id = 75, Name = "Kastair" },
                new Brand { Id = 76, Name = "Katrex" },
                new Brand { Id = 77, Name = "Klarizid" },
                new Brand { Id = 78, Name = "Klaz" },
                new Brand { Id = 79, Name = "Locetar" },
                new Brand { Id = 80, Name = "Loviscol" },
                new Brand { Id = 81, Name = "Maalox" },
                new Brand { Id = 82, Name = "Medicol" },
                new Brand { Id = 83, Name = "Meptin" },
                new Brand { Id = 84, Name = "Montemax" },
                new Brand { Id = 85, Name = "Montiget" },
                new Brand { Id = 86, Name = "Motilium" },
                new Brand { Id = 87, Name = "Movelax" },
                new Brand { Id = 88, Name = "Muconase" },
                new Brand { Id = 89, Name = "Mucosolvan" },
                new Brand { Id = 90, Name = "Myonal" },
                new Brand { Id = 91, Name = "Myremol" },
                new Brand { Id = 92, Name = "Napran" },
                new Brand { Id = 93, Name = "Naprex" },
                new Brand { Id = 94, Name = "Nasatapp" },
                new Brand { Id = 95, Name = "Nasathera" },
                new Brand { Id = 96, Name = "Nasoclear" },
                new Brand { Id = 97, Name = "Natravox" },
                new Brand { Id = 98, Name = "Neozep" },
                new Brand { Id = 99, Name = "Nuelin" },
                new Brand { Id = 100, Name = "Omepron" },
                new Brand { Id = 101, Name = "Opigesic" },
                new Brand { Id = 102, Name = "Optipred" },
                new Brand { Id = 103, Name = "Orastin" },
                new Brand { Id = 104, Name = "Pediachlor" },
                new Brand { Id = 105, Name = "Pediamox" },
                new Brand { Id = 106, Name = "Pediatapp" },
                new Brand { Id = 107, Name = "Penachlor" },
                new Brand { Id = 108, Name = "Pharex" },
                new Brand { Id = 109, Name = "Physiogel" },
                new Brand { Id = 110, Name = "Polypen" },
                new Brand { Id = 111, Name = "Ponstan" },
                new Brand { Id = 112, Name = "Poro" },
                new Brand { Id = 113, Name = "Pred 10" },
                new Brand { Id = 114, Name = "Pred 20" },
                new Brand { Id = 115, Name = "Propan Tlc" },
                new Brand { Id = 116, Name = "Prostaphlin-A" },
                new Brand { Id = 117, Name = "Provexcel" },
                new Brand { Id = 118, Name = "Prox-S" },
                new Brand { Id = 119, Name = "Pulmodual" },
                new Brand { Id = 120, Name = "Pulmoxcel" },
                new Brand { Id = 121, Name = "Restime" },
                new Brand { Id = 122, Name = "Ritemed" },
                new Brand { Id = 123, Name = "Rodazid" },
                new Brand { Id = 124, Name = "Romamed" },
                new Brand { Id = 125, Name = "Rotocin" },
                new Brand { Id = 126, Name = "Salinase" },
                new Brand { Id = 127, Name = "Sangobion" },
                new Brand { Id = 128, Name = "Selzef" },
                new Brand { Id = 129, Name = "Seretide" },
                new Brand { Id = 130, Name = "Singulair" },
                new Brand { Id = 131, Name = "Skelan" },
                new Brand { Id = 132, Name = "Solmux"},
                new Brand { Id = 133, Name = "Solmux Broncho" },
                new Brand { Id = 134, Name = "Stafloxin" },
                new Brand { Id = 135, Name = "Sumapen" },
                new Brand { Id = 136, Name = "Tempra" },
                new Brand { Id = 137, Name = "Tergecet" },
                new Brand { Id = 138, Name = "Trizole" },
                new Brand { Id = 139, Name = "Ultraxime" },
                new Brand { Id = 140, Name = "Ventolin" },
                new Brand { Id = 141, Name = "Ventolin Expt" },
                new Brand { Id = 142, Name = "Virlix" },
                new Brand { Id = 143, Name = "Vometa" },
                new Brand { Id = 144, Name = "Xelent" },
                new Brand { Id = 145, Name = "Xinflex" },
                new Brand { Id = 146, Name = "Xyzal" },
                new Brand { Id = 147, Name = "Zeditapp" },
                new Brand { Id = 148, Name = "Zegen" },
                new Brand { Id = 149, Name = "Zenith" },
                new Brand { Id = 150, Name = "Zinnat" },
                new Brand { Id = 151, Name = "Zithromax" },
                new Brand { Id = 152, Name = "Zovirax" },
                new Brand { Id = 153, Name = "Zyrtec" });
        }

        private static void Medicines()
        {
            _builder.Entity<Medicine>().HasData(
                new Medicine { Id = 1, GenericName = "Cetirizine", Inscription = "Tab", Description = "10mg", BrandId = null },
                new Medicine { Id = 2, GenericName = "Amoxicillin", Inscription = "Cap", Description = "500mg", BrandId = null },
                new Medicine { Id = 3, GenericName = "Amoxicillin", Inscription = "Cap", Description = "250mg", BrandId = null },
                new Medicine { Id = 4, GenericName = "Co Amoxiclav", Inscription = "Tab", Description = "375mg", BrandId = null },
                new Medicine { Id = 5, GenericName = "Prednisolone", Inscription = "Tab", Description = "30mg", BrandId = null },
                new Medicine { Id = 6, GenericName = "Prednisolone", Inscription = "Tab", Description = "20mg", BrandId = null },
                new Medicine { Id = 7, GenericName = "Prednisolone", Inscription = "Tab", Description = "5mg", BrandId = null },
                new Medicine { Id = 8, GenericName = "Gentamicin IV", Inscription = "Amp", Description = "80mg/5ml", BrandId = null },
                new Medicine { Id = 9, GenericName = "Gentamicin IV", Inscription = "Amp", Description = "40mg/5ml", BrandId = null },
                new Medicine { Id = 10, GenericName = "Broncho Vaxom", Inscription = "Pedia Cap", Description = null, BrandId = null },
                new Medicine { Id = 11, GenericName = "Glycerin", Inscription = "Pediatric suppository", Description = null, BrandId = null },
                new Medicine { Id = 12, GenericName = "Glycerin", Inscription = "Pediatric suppository", Description = null, BrandId = null },
                new Medicine { Id = 13, GenericName = "Salbutamol", Inscription = "Tab", Description = "2mg", BrandId = 1 },
                new Medicine { Id = 14, GenericName = "Salbutamol", Inscription = "Syrup", Description = "2mg/5ml", BrandId = 1 },
                new Medicine { Id = 15, GenericName = "Ibuprofen", Inscription = "Susp", Description = "100mg/5ml", BrandId = 2 },
                new Medicine { Id = 16, GenericName = "Ibuprofen", Inscription = "Susp", Description = "200mg/5ml", BrandId = 2 },
                new Medicine { Id = 17, GenericName = "Ibuprofen", Inscription = "Cap", Description = "200mg", BrandId = 2 },
                new Medicine { Id = 18, GenericName = "Ibuprofen", Inscription = "Drops", Description = "100mg/2.5ml", BrandId = 2 },
                new Medicine { Id = 19, GenericName = "Cetirizine", Inscription = "Syrup", Description = "5mg/5ml", BrandId = 3 },
                new Medicine { Id = 20, GenericName = "Cetirizine", Inscription = "Drops", Description = "2.5mg/ml", BrandId = 3 },
                new Medicine { Id = 21, GenericName = "Terbutaline", Inscription = "Syrup", Description = "1.5mg/5ml", BrandId = null },
                new Medicine { Id = 22, GenericName = "Cetirizine", Inscription = "Tab", Description = "10mg", BrandId = 4 },
                new Medicine { Id = 23, GenericName = "Cetirizine", Inscription = "Syrup", Description = "5mg/5ml", BrandId = 4 },
                new Medicine { Id = 24, GenericName = "Cetirizine", Inscription = "Drops", Description = "2.5mg/ml", BrandId = 5 },
                new Medicine { Id = 25, GenericName = "Paracetamol", Inscription = "Tab", Description = "250mg", BrandId = 5 },
                new Medicine { Id = 26, GenericName = "Paracetamol", Inscription = "Tab", Description = "325mg", BrandId = 5 },
                new Medicine { Id = 27, GenericName = "Paracetamol", Inscription = "Tab", Description = "500mg", BrandId = 5 },
                new Medicine { Id = 28, GenericName = "Paracetamol", Inscription = "Syrup", Description = "120mg/5ml", BrandId = 6 },
                new Medicine { Id = 29, GenericName = "Paracetamol", Inscription = "Drops", Description = "100ml", BrandId = 6 },
                new Medicine { Id = 30, GenericName = "Ambroxol", Inscription = "Tab", Description = "30mg", BrandId = 7 },
                new Medicine { Id = 31, GenericName = "Ambroxol", Inscription = "Syrup", Description = "30mg/3ml", BrandId = 7 },
                new Medicine { Id = 32, GenericName = "Ambroxol", Inscription = "Syrup", Description = "15mg/5ml", BrandId = 7 },
                new Medicine { Id = 33, GenericName = "Ambroxol", Inscription = "Drops", Description = "7.5mg/ml", BrandId = 7 },
                new Medicine { Id = 34, GenericName = "Co Amoxiclav", Inscription = "Susp", Description = "457mg/5ml", BrandId = 8 },
                new Medicine { Id = 35, GenericName = "Co Amoxiclav", Inscription = "Susp", Description = "228mg/5ml", BrandId = 8 },
                new Medicine { Id = 36, GenericName = "Co Amoxiclav", Inscription = "Susp", Description = "156mg/5ml", BrandId = 8 },
                new Medicine { Id = 37, GenericName = "Co Amoxiclav", Inscription = "Susp", Description = "312mg/5ml", BrandId = 8 },
                new Medicine { Id = 38, GenericName = "Amoxicillin", Inscription = "Susp", Description = "250mg/5ml", BrandId = 9 },
                new Medicine { Id = 39, GenericName = "Amoxicillin", Inscription = "Drops", Description = "100mg/ml", BrandId = 9 },
                new Medicine { Id = 40, GenericName = "Amoxicillin", Inscription = "Susp", Description = "125mg/ml", BrandId = 9 },
                new Medicine { Id = 41, GenericName = "Ampicillin IV", Inscription = null, Description = "1mg", BrandId = 10 },
                new Medicine { Id = 42, GenericName = "Ampicillin IV", Inscription = null, Description = "500mg", BrandId = 10 },
                new Medicine { Id = 43, GenericName = "Ampicillin IV", Inscription = null, Description = "750mg", BrandId = 10 },
                new Medicine { Id = 44, GenericName = "Ampicillin IV", Inscription = null, Description = "250mg", BrandId = 10 },
                new Medicine { Id = 45, GenericName = "Doxofylline", Inscription = "Tab", Description = "100mg", BrandId = 11 },
                new Medicine { Id = 46, GenericName = "Doxofylline", Inscription = "Syrup", Description = "100mg/5ml", BrandId = 11 },
                new Medicine { Id = 47, GenericName = "Mebendazole", Inscription = "Tab", Description = "100mg", BrandId = 12 },
                new Medicine { Id = 48, GenericName = "Mebendazole", Inscription = "Susp", Description = "20mg/ml", BrandId = 12 },
                new Medicine { Id = 49, GenericName = "Mebendazole", Inscription = "Tab", Description = "500mg", BrandId = 12 },
                new Medicine { Id = 50, GenericName = "Mebendazole", Inscription = "Susp", Description = "50mg/ml", BrandId = 12 },
                new Medicine { Id = 51, GenericName = "Salbutamol", Inscription = "Syrup", Description = "2mg/5ml", BrandId = 13 },
                new Medicine { Id = 52, GenericName = "Salbutamol + Guaifenesin", Inscription = "Syrup", Description = null, BrandId = 14 },
                new Medicine { Id = 53, GenericName = "Salbutamol", Inscription = "MDI", Description = "100mgm/Inhalation", BrandId = 15 },
                new Medicine { Id = 54, GenericName = "Salbutamol", Inscription = "Nebule", Description = "2.5mg/2.5ml", BrandId = 15 },
                new Medicine { Id = 55, GenericName = "Salbutamol", Inscription = "Tab", Description = "2mg", BrandId = 15 },
                new Medicine { Id = 56, GenericName = "Salbutamol", Inscription = "Syrup", Description = "2mg/5ml", BrandId = 15 },
                new Medicine { Id = 57, GenericName = "Salbutamol + Guaifenesin", Inscription = "Syrup", Description = null, BrandId = 16 },
                new Medicine { Id = 58, GenericName = "Coamoxiclav", Inscription = "Tab", Description = "625mg", BrandId = 17 },
                new Medicine { Id = 59, GenericName = "Coamoxiclav", Inscription = "Susp", Description = "156mg/5ml", BrandId = 17 },
                new Medicine { Id = 60, GenericName = "Coamoxiclav", Inscription = "Susp", Description = "457mg/5ml", BrandId = 17 },
                new Medicine { Id = 61, GenericName = "Coamoxiclav", Inscription = "Susp", Description = "228mg/5ml", BrandId = 17 },
                new Medicine { Id = 62, GenericName = "Coamoxiclav", Inscription = "Susp", Description = "312mg/5ml", BrandId = 17 },                        
                new Medicine { Id = 63, GenericName = "Fluticasone Furoate", Inscription = "Nasal Spray", Description = "27.5mgm/spray", BrandId = 18 },
                new Medicine { Id = 64, GenericName = "Azithromycin", Inscription = "Tab", Description = "500mg", BrandId = 19 },
                new Medicine { Id = 65, GenericName = "Azithromycin", Inscription = "Tab", Description = "250mg", BrandId = 19 },
                new Medicine { Id = 66, GenericName = "Azithromycin", Inscription = "Susp", Description = "200mg/5ml", BrandId = 19 },
                new Medicine { Id = 67, GenericName = "Cotrimoxazole", Inscription = "Tab", Description = "4oomg/80mg", BrandId = 20 },
                new Medicine { Id = 68, GenericName = "Mupirocin", Inscription = "Tube", Description = "Cream", BrandId = 21 },
                new Medicine { Id = 69, GenericName = "Bambuterol", Inscription = "Syrup", Description = "1mg/1ml", BrandId = 22 },
                new Medicine { Id = 70, GenericName = "Bambuterol", Inscription = "Tab", Description = "10mg", BrandId = 22 },
                new Medicine { Id = 71, GenericName = "Co Amoxiclav", Inscription = "Susp", Description = "125mg/5ml", BrandId = 23 },
                new Medicine { Id = 72, GenericName = "Co Amoxiclav", Inscription = "Susp", Description = "250mg/5ml", BrandId = 23 },
                new Medicine { Id = 73, GenericName = "Paracetamol", Inscription = "Susp", Description = "120mg/5ml", BrandId = 24 },
                new Medicine { Id = 74, GenericName = "Paracetamol", Inscription = "Tab", Description = "500mg", BrandId = 24 },
                new Medicine { Id = 75, GenericName = "Paracetamol", Inscription = "Syrup", Description = "250mg/5ml", BrandId = 24 },
                new Medicine { Id = 76, GenericName = "Paracetamol", Inscription = "Tab", Description = "250mg", BrandId = 24 },
                new Medicine { Id = 77, GenericName = "Paracetamol", Inscription = "Tab", Description = "325mg", BrandId = 24 },
                new Medicine { Id = 78, GenericName = "Paracetamol", Inscription = "Drops", Description = "100mg/ml", BrandId = 24 },
                new Medicine { Id = 79, GenericName = "Terbutaline", Inscription = "Syrup", Description = "1.5mg/5ml", BrandId = 25 },
                new Medicine { Id = 80, GenericName = "Salbutamol + Guaifenesin", Inscription = "Syrup", Description = null, BrandId = 26 },
                new Medicine { Id = 81, GenericName = "Phenylephrine Hcl + Chlorpheniramine Maleate", Inscription = "Syrup", Description = "5mg///1mg/5ml", BrandId = 27 },
                new Medicine { Id = 82, GenericName = "Phenylephrine Hcl + Chlorpheniramine Maleate", Inscription = "Syrup", Description = null, BrandId = 27 },
                new Medicine { Id = 83, GenericName = "Phenylephrine Hcl + Chlorpheniramine Maleate", Inscription = "drops", Description = null, BrandId = 27 },
                new Medicine { Id = 84, GenericName = "Calmoseptine", Inscription = "Ointment", Description = "Sachet", BrandId = 28 },
                new Medicine { Id = 85, GenericName = "Paracetamol", Inscription = "Susp", Description = "250mg/5ml", BrandId = 29 },
                new Medicine { Id = 86, GenericName = "Paracetamol", Inscription = "Tab", Description = "250mg", BrandId = 29 },
                new Medicine { Id = 87, GenericName = "Paracetamol", Inscription = "Tab", Description = "500mg", BrandId = 29 },
                new Medicine { Id = 88, GenericName = "Paracetamol", Inscription = "Tab", Description = "325mg", BrandId = 29 },
                new Medicine { Id = 89, GenericName = "Paracetamol", Inscription = "Syrup", Description = "120mg/5ml", BrandId = 29 },
                new Medicine { Id = 90, GenericName = "Paracetamol", Inscription = "Drops", Description = "100mg/ml", BrandId = 29 },
                new Medicine { Id = 91, GenericName = "Cefaclor", Inscription = "Susp", Description = "250mg/5ml", BrandId = 30 },
                new Medicine { Id = 92, GenericName = "Cefaclor", Inscription = "Susp", Description = "125mg/5ml", BrandId = 30 },
                new Medicine { Id = 93, GenericName = "Cefaclor + Guaifenesin", Inscription = "Drops", Description = "50mg/ml", BrandId = 30 },
                new Medicine { Id = 94, GenericName = "Cefalexin", Inscription = "Cap", Description = "500mg", BrandId = 31 },
                new Medicine { Id = 95, GenericName = "Cefalexin", Inscription = "Susp", Description = "250mg/5ml", BrandId = 31 },
                new Medicine { Id = 96, GenericName = "Cefalexin", Inscription = "Susp", Description = "125mg/5ml", BrandId = 31 },
                new Medicine { Id = 97, GenericName = "Cefalexin", Inscription = "Drops", Description = "100mg/ml", BrandId = 31 },
                new Medicine { Id = 98, GenericName = "Cefalexin", Inscription = "Susp", Description = "250mg/5ml", BrandId = 32 },
                new Medicine { Id = 99, GenericName = "Cefalexin", Inscription = "Susp", Description = "125mg/5ml", BrandId = 32 },
                new Medicine { Id = 100, GenericName = "Cefalexin", Inscription = "Drops", Description = "100mg/ml", BrandId = 32 },
                new Medicine { Id = 101, GenericName = "Multivitamins", Inscription = "Drops", Description = null, BrandId = 33 },
                new Medicine { Id = 102, GenericName = "Chloramphenicol", Inscription = "Cap", Description = "500mg", BrandId = 34 },
                new Medicine { Id = 103, GenericName = "Chloramphenicol", Inscription = "Susp", Description = "125mg/5ml", BrandId = 34 },
                new Medicine { Id = 104, GenericName = "Chloramphenicol", Inscription = "Cap", Description = "250mg", BrandId = 34 },
                new Medicine { Id = 105, GenericName = "Clarithromycin", Inscription = "Susp", Description = "125mg/5ml", BrandId = 35 },
                new Medicine { Id = 106, GenericName = "Clarithromycin", Inscription = "Tab", Description = "125mg/5ml", BrandId = 36 },
                new Medicine { Id = 107, GenericName = "Clarithromycin", Inscription = "Tab", Description = "500mg", BrandId = 36 },
                new Medicine { Id = 108, GenericName = "Clarithromycin", Inscription = "Susp", Description = "250mg/5ml", BrandId = 36 },
                new Medicine { Id = 109, GenericName = "Clarithromycin", Inscription = "Susp", Description = "125mg/5ml", BrandId = 37 },
                new Medicine { Id = 110, GenericName = "Clarithromycin", Inscription = "Tab", Description = "250mg", BrandId = 38 },
                new Medicine { Id = 111, GenericName = "Clarithromycin", Inscription = "Tab", Description = "500mg", BrandId = 38 },
                new Medicine { Id = 112, GenericName = "Clarithromycin", Inscription = "Susp", Description = "250mg/5ml", BrandId = 38 },
                new Medicine { Id = 113, GenericName = "Clarithromycin", Inscription = "Susp", Description = "125mg/5ml", BrandId = 38 },
                new Medicine { Id = 114, GenericName = "Clotrimazole + Betamethasone", Inscription = "Cream", Description = "Tube", BrandId = 39 },
                new Medicine { Id = 115, GenericName = "Pyrantel Pamoate", Inscription = "Tab", Description = "125mg", BrandId = 40 },
                new Medicine { Id = 116, GenericName = "Pyrantel Pamoate", Inscription = "Susp", Description = "125mg/5ml", BrandId = 40 },
                new Medicine { Id = 117, GenericName = "Salbutamol + Ipratropium Bromide", Inscription = "Nebule", Description = null, BrandId = 41 },
                new Medicine { Id = 118, GenericName = "Miconazole", Inscription = "Oral Gel", Description = "Tube", BrandId = 42 },
                new Medicine { Id = 119, GenericName = "Clindamycin", Inscription = "Susp", Description = "75mg/5ml", BrandId = 43 },
                new Medicine { Id = 120, GenericName = "Dg Milk", Inscription = "Can", Description = "400mg", BrandId = 44 },
                new Medicine { Id = 121, GenericName = "Doxofylline", Inscription = "Syrup", Description = "100mg/5ml", BrandId = 45 },
                new Medicine { Id = 122, GenericName = "Doxofylline", Inscription = "Tab", Description = "100mg", BrandId = 45 },
                new Medicine { Id = 123, GenericName = "Brompheniramine Maleate + Phenylephrine", Inscription = "Drops", Description = null, BrandId = 46},
                new Medicine { Id = 124, GenericName = "Brompheniramine Maleate + Phenylephrine", Inscription = "Syrup", Description = null, BrandId = 46 },
                new Medicine { Id = 125, GenericName = "Phenylpropanolamine", Inscription = "Syrup", Description = null, BrandId = 47 },
                new Medicine { Id = 126, GenericName = "Phenylpropanolamine", Inscription = "Drops", Description = null, BrandId = 47 },
                new Medicine { Id = 127, GenericName = "Ibuprofen", Inscription = "Susp", Description = "200mg/5ml", BrandId = 48 },
                new Medicine { Id = 128, GenericName = "Ibuprofen", Inscription = "susp", Description = "100mg/5ml", BrandId = 48 },
                new Medicine { Id = 129, GenericName = "Ibuprofen", Inscription = "Drops", Description = "100mg/2.5ml", BrandId = 48 },
                new Medicine { Id = 130, GenericName = "Mefenamic Acid", Inscription = "Cap", Description = "250mg", BrandId = 49 },
                new Medicine { Id = 131, GenericName = "Mefenamic Acid", Inscription = "Cap", Description = "500mg", BrandId = 49 },
                new Medicine { Id = 132, GenericName = "Salbutamol + Ipratropium Bromide", Inscription = "Nebule", Description = null, BrandId = 50 },
                new Medicine { Id = 133, GenericName = "Zinc Sulfate", Inscription = "Syrup", Description = null, BrandId = 51 },
                new Medicine { Id = 134, GenericName = "Zinc Sulfate", Inscription = "Drops", Description = null, BrandId = 51 },
                new Medicine { Id = 135, GenericName = "Mometasone Furoate", Inscription = "Lotion", Description = null, BrandId = 52 },
                new Medicine { Id = 136, GenericName = "Mometasone Furoate", Inscription = "Cream", Description = null, BrandId = 52 },
                new Medicine { Id = 137, GenericName = "Bacillus Clausii", Inscription = "Oral Solution", Description = null, BrandId = 53 },
                new Medicine { Id = 138, GenericName = "Nifuroxazide", Inscription = "Susp", Description = "218mg/5ml", BrandId = 54 },
                new Medicine { Id = 139, GenericName = "Nifuroxazide", Inscription = "Cap", Description = "200mg", BrandId = 54 },            
                new Medicine { Id = 140, GenericName = "Phospholipids", Inscription = "Cap", Description = "300mg", BrandId = 55 },
                new Medicine { Id = 141, GenericName = "Ambroxol", Inscription = "Tab", Description = "300mg", BrandId = 56 },
                new Medicine { Id = 142, GenericName = "Ambroxol", Inscription = "Syrup", Description = "30mg/5ml", BrandId = 56 },
                new Medicine { Id = 143, GenericName = "Ambroxol", Inscription = "Drops", Description = "7.5mg/5ml", BrandId = 56 },
                new Medicine { Id = 144, GenericName = "Ambroxol", Inscription = "Syrup", Description = "15mg/2.5ml", BrandId = 56 },
                new Medicine { Id = 145, GenericName = "Ibuprofen", Inscription = "Cap", Description = "400mg", BrandId = 57 },
                new Medicine { Id = 146, GenericName = "Ibuprofen", Inscription = "Cap", Description = "200mg", BrandId = 57 },
                new Medicine { Id = 147, GenericName = "Metronidazole", Inscription = "Tab", Description = "500mg", BrandId = 58 },
                new Medicine { Id = 148, GenericName = "Metronidazole", Inscription = "Syrup", Description = "25mg/1ml", BrandId = 58 },
                new Medicine { Id = 149, GenericName = "Metronidazole", Inscription = null, Description = null, BrandId = 58 },
                new Medicine { Id = 150, GenericName = "Naproxen Sodium", Inscription = "Tab", Description = "550mg", BrandId = 59 },
                new Medicine { Id = 151, GenericName = "Naproxen Sodium", Inscription = "Tab", Description = "275mg", BrandId = 59 },
                new Medicine { Id = 152, GenericName = "Acetylcysteine", Inscription = "Sachet", Description = "1000mg", BrandId = 60 },
                new Medicine { Id = 153, GenericName = "Acetylcysteine", Inscription = "Syrup", Description = "100mg/5ml", BrandId = 60 },
                new Medicine { Id = 154, GenericName = "Acetylcysteine", Inscription = "Sachet", Description = "200mg", BrandId = 60 },
                new Medicine { Id = 155, GenericName = "Fusidate Sodium", Inscription = "Ointment", Description = "Tube", BrandId = 61 },
                new Medicine { Id = 156, GenericName = "Fucidic Acid + Hydrocortisone", Inscription = "Ointment", Description = "Tube", BrandId = 62 },
                new Medicine { Id = 157, GenericName = "Fucidic Acid", Inscription = "Eyedrops", Description = "Tube", BrandId = 63 },
                new Medicine { Id = 158, GenericName = "Furazolidone", Inscription = "Tab", Description = "100mg", BrandId = 64 },
                new Medicine { Id = 159, GenericName = "Furazolidone", Inscription = "Susp", Description = "16.7mg/5ml", BrandId = 64 },
                new Medicine { Id = 160, GenericName = "Gentamycin", Inscription = "Eyedrops", Description = null, BrandId = 65 },
                new Medicine { Id = 161, GenericName = "Mefenamic Acid", Inscription = "Cap", Description = "500mg", BrandId = 66 },
                new Medicine { Id = 162, GenericName = "Mefenamic Acid", Inscription = "Cap", Description = "250mg", BrandId = 66 },
                new Medicine { Id = 163, GenericName = "Dibencozide", Inscription = "Cap", Description = "1mg/1ml", BrandId = 67 },
                new Medicine { Id = 164, GenericName = "Amoxicillin", Inscription = "Cap", Description = "500mg", BrandId = 68 },
                new Medicine { Id = 165, GenericName = "Amoxicillin", Inscription = "Susp", Description = "250mg/5ml", BrandId = 68 },
                new Medicine { Id = 166, GenericName = "Amoxicillin", Inscription = "Susp", Description = "125mg/5ml", BrandId = 68 },
                new Medicine { Id = 167, GenericName = "Amoxicillin", Inscription = "Drops", Description = "100mg/ml", BrandId = 68 },
                new Medicine { Id = 168, GenericName = "Brompheniramine Maleate + Phenylpropanolamine", Inscription = "Syrup", Description = null, BrandId = 69 },
                new Medicine { Id = 169, GenericName = "Brompheniramine Maleate + Phenylpropanolamine", Inscription = "Drops", Description = null, BrandId = 69 },
                new Medicine { Id = 170, GenericName = "Oral Rehydration Solution", Inscription = "Sachet", Description = null, BrandId = 70 },
                new Medicine { Id = 171, GenericName = "Erythromycin", Inscription = "Susp", Description = "250mg/5ml", BrandId = 71 },
                new Medicine { Id = 172, GenericName = "Erythromycin", Inscription = "Drops", Description = "100mg/ml", BrandId = 71 },
                new Medicine { Id = 173, GenericName = "Inosiplex", Inscription = "Syrup", Description = "Bot", BrandId = 72 },
                new Medicine { Id = 174, GenericName = "Hydroxyzine diHCI", Inscription = "Tab", Description = "25mg", BrandId = 73 },
                new Medicine { Id = 175, GenericName = "Hydroxyzine diHCI", Inscription = "Syrup", Description = "2mg/ml", BrandId = 73 },
                new Medicine { Id = 176, GenericName = "Hydroxyzine diHCI", Inscription = "Tab", Description = "10mg", BrandId = 73 },
                new Medicine { Id = 177, GenericName = "Betaine Glucuronate Plus", Inscription = "Syrup", Description = null, BrandId = 74 },
                new Medicine { Id = 178, GenericName = "Betaine Glucuronate Plus", Inscription = "Cap", Description = null, BrandId = 74 },
                new Medicine { Id = 179, GenericName = "Montelukast", Inscription = "Tab", Description = "4mg", BrandId = 75 },
                new Medicine { Id = 180, GenericName = "Montelukast", Inscription = "Tab", Description = "10mg", BrandId = 75 },
                new Medicine { Id = 181, GenericName = "Montelukast", Inscription = "Tab", Description = "5mg", BrandId = 75 },
                new Medicine { Id = 182, GenericName = "Cotrimoxazole", Inscription = "Bot", Description = "200mg/40mg/5ml", BrandId = 76 },
                new Medicine { Id = 183, GenericName = "Clarithromycin", Inscription = "Tab", Description = "500mg", BrandId = 77 },
                new Medicine { Id = 184, GenericName = "Clarithromycin", Inscription = "Susp", Description = "125mg/5ml", BrandId = 77 },
                new Medicine { Id = 185, GenericName = "Clarithromycin", Inscription = "Tab", Description = "250mg", BrandId = 77 },
                new Medicine { Id = 186, GenericName = "Clarithromycin", Inscription = "Susp", Description = "250mg/5ml", BrandId = 77 },
                new Medicine { Id = 187, GenericName = "Clarithromycin", Inscription = "Tab", Description = "500mg", BrandId = 78 },
                new Medicine { Id = 188, GenericName = "Clarithromycin", Inscription = "Susp", Description = "250mg/5ml", BrandId = 78 },
                new Medicine { Id = 189, GenericName = "Clarithromycin", Inscription = "Susp", Description = "125mg/5ml", BrandId = 78 },
                new Medicine { Id = 190, GenericName = "Clarithromycin", Inscription = "Tab", Description = "250mg", BrandId = 78 },
                new Medicine { Id = 191, GenericName = "Amorolfine", Inscription = "Nail Lacquer", Description = null, BrandId = 79 },
                new Medicine { Id = 192, GenericName = "Carbocisteine", Inscription = "Syrup", Description = "100mg/5ml", BrandId = 80 },
                new Medicine { Id = 193, GenericName = "Carbocisteine", Inscription = "Drops", Description = "50mg/ml", BrandId = 80 },
                new Medicine { Id = 194, GenericName = "Aluminum Magnesium Hydroxide", Inscription = "Tab", Description = null, BrandId = 81 },
                new Medicine { Id = 195, GenericName = "Aluminum Magnesium Hydroxide", Inscription = "Susp", Description = null, BrandId = 81 },
                new Medicine { Id = 196, GenericName = "Ibuprofen", Inscription = "Cap", Description = "200mg", BrandId = 82 },
                new Medicine { Id = 197, GenericName = "Procaterol", Inscription = "Tab", Description = "25mgm", BrandId = 83 },
                new Medicine { Id = 198, GenericName = "Procaterol", Inscription = "Tab", Description = "50mgm", BrandId = 83 },
                new Medicine { Id = 199, GenericName = "Procaterol", Inscription = "Syrup", Description = "5mgm/ml", BrandId = 83 },
                new Medicine { Id = 200, GenericName = "Montelukast", Inscription = "Tab", Description = "5mg", BrandId = 84 },
                new Medicine { Id = 201, GenericName = "Montelukast", Inscription = "Tab", Description = "10mg", BrandId = 84 },
                new Medicine { Id = 202, GenericName = "Montelukast", Inscription = "Tab", Description = "4mg", BrandId = 84 },
                new Medicine { Id = 203, GenericName = "Montelukast", Inscription = "Tab", Description = "5mg", BrandId = 85 },
                new Medicine { Id = 204, GenericName = "Montelukast", Inscription = "Tab", Description = "10mg", BrandId = 85 },
                new Medicine { Id = 205, GenericName = "Montelukast", Inscription = "Tab", Description = "4mg", BrandId = 85 },
                new Medicine { Id = 206, GenericName = "Montelukast", Inscription = "Granules", Description = "4mg", BrandId = 85 },
                new Medicine { Id = 207, GenericName = "Domperidone", Inscription = "Tab", Description = "10mg", BrandId = 86 },
                new Medicine { Id = 208, GenericName = "Lactulose", Inscription = "Syrup", Description = "3.3g/5ml", BrandId = 87 },
                new Medicine { Id = 209, GenericName = "Sodium Chloride", Inscription = "Nasal drops", Description = null, BrandId = 88 },
                new Medicine { Id = 210, GenericName = "Sodium Chloride", Inscription = "Nasal spray", Description = null, BrandId = 88 },
                new Medicine { Id = 211, GenericName = "Ambroxol", Inscription = "Drops", Description = "7.5mg/ml", BrandId = 89 },
                new Medicine { Id = 212, GenericName = "Eperisone HCI", Inscription = "Tab", Description = "50mg", BrandId = 90 },
                new Medicine { Id = 213, GenericName = "Paracetamol", Inscription = "Syrup", Description = "120mg/5ml", BrandId = 91 },
                new Medicine { Id = 214, GenericName = "Paracetamol", Inscription = "Syrup", Description = "250mg/5ml", BrandId = 91 },
                new Medicine { Id = 215, GenericName = "Paracetamol", Inscription = "Drops", Description = "100ml", BrandId = 91 },
                new Medicine { Id = 216, GenericName = "Paracetamol", Inscription = "Drops", Description = "100ml", BrandId = 92 },
                new Medicine { Id = 217, GenericName = "Paracetamol", Inscription = "Syrup", Description = "250mg/5ml", BrandId = 92 },
                new Medicine { Id = 218, GenericName = "Paracetamol", Inscription = "Syrup", Description = "250mg/5ml", BrandId = 93 },
                new Medicine { Id = 219, GenericName = "Paracetamol", Inscription = "Drops", Description = "100mg/ml", BrandId = 93 },
                new Medicine { Id = 220, GenericName = "Brompheniramine Maleate + Phenylpropanolamine", Inscription = "Syrup", Description = null, BrandId = 94 },
                new Medicine { Id = 221, GenericName = "Brompheniramine Maleate + Phenylpropanolamine", Inscription = "Drops", Description = null, BrandId = 94 },
                new Medicine { Id = 222, GenericName = "Paracetamol + Phenylpropanolamine", Inscription = "Syrup", Description = "250mg/12.5mg", BrandId = 95 },
                new Medicine { Id = 223, GenericName = "Paracetamol + Phenylpropanolamine", Inscription = "Cap", Description = "325mg/25mg", BrandId = 95 },
                new Medicine { Id = 224, GenericName = "Sodium Chloride", Inscription = "Nasal spray", Description = null, BrandId = 96 },
                new Medicine { Id = 225, GenericName = "Sodium Chloride", Inscription = "Nasal drops", Description = null, BrandId = 96 },
                new Medicine { Id = 226, GenericName = "Co Amoxiclav", Inscription = "Susp", Description = "125mg/5ml", BrandId = 97 },
                new Medicine { Id = 227, GenericName = "Co Amoxiclav", Inscription = "Susp", Description = "250mg/5ml", BrandId = 97 },
                new Medicine { Id = 228, GenericName = "Phenylephrine Hcl + Chlorpheniramine Maleate", Inscription = "Syrup", Description = null, BrandId = 98 },
                new Medicine { Id = 229, GenericName = "Phenylephrine Hcl + Chlorpheniramine Maleate", Inscription = "Drops", Description = null, BrandId = 98 },
                new Medicine { Id = 230, GenericName = "Theophylline", Inscription = "Syrup", Description = "26.7mg/5ml", BrandId = 99 },
                new Medicine { Id = 231, GenericName = "Omeprazole", Inscription = "Cap", Description = "20 Mg", BrandId = 100 },
                new Medicine { Id = 232, GenericName = "Paracetamol", Inscription = "Suppository", Description = "125mg", BrandId = 101 },
                new Medicine { Id = 233, GenericName = "Paracetamol", Inscription = "Suppository", Description = "250mg/5ml", BrandId = 101 },
                new Medicine { Id = 234, GenericName = "Prednisolone", Inscription = "Syrup", Description = "20mg/5ml", BrandId = 102 },
                new Medicine { Id = 235, GenericName = "Nystatin", Inscription = "Susp", Description = "100,000 Iu", BrandId = 103 },
                new Medicine { Id = 236, GenericName = "Chloramphenicol", Inscription = "Susp", Description = "125mg/5ml", BrandId = 104 },
                new Medicine { Id = 237, GenericName = "Chloramphenicol", Inscription = "Cap", Description = "250mg/5ml", BrandId = 104 },
                new Medicine { Id = 238, GenericName = "Chloramphenicol", Inscription = "Cap", Description = "500mg", BrandId = 104 },
                new Medicine { Id = 239, GenericName = "Amoxicillin", Inscription = "Susp", Description = "250mg/5ml", BrandId = 105 },
                new Medicine { Id = 240, GenericName = "Amoxicillin", Inscription = "Susp", Description = "125mg/5ml", BrandId = 105 },
                new Medicine { Id = 241, GenericName = "Amoxicillin", Inscription = "Drops", Description = "100mg/ml", BrandId = 105 },
                new Medicine { Id = 242, GenericName = "Brompheniramine Maleate + Phenylpropanolamine", Inscription = "Syrup", Description = null, BrandId = 106 },
                new Medicine { Id = 243, GenericName = "Brompheniramine Maleate + Phenylpropanolamine", Inscription = "Drops", Description = null, BrandId = 106 },
                new Medicine { Id = 244, GenericName = "Chloramphenicol", Inscription = "Syrup", Description = "125mg/5ml", BrandId = 107 },
                new Medicine { Id = 245, GenericName = "Chloramphenicol", Inscription = "Cap", Description = "250mg", BrandId = 107 },
                new Medicine { Id = 246, GenericName = "Chloramphenicol", Inscription = "Cap", Description = "500mg", BrandId = 107 },
                new Medicine { Id = 247, GenericName = "Cloxacillin", Inscription = "Susp", Description = "250mg/5ml", BrandId = 108 },
                new Medicine { Id = 248, GenericName = "Cloxacillin", Inscription = "Susp", Description = "250mg/5ml", BrandId = 108 },
                new Medicine { Id = 249, GenericName = "Cloxacillin", Inscription = "Susp", Description = "125mg/5ml", BrandId = 108 },
                new Medicine { Id = 250, GenericName = "Physiogel ", Inscription = "Skin Cleanser", Description = null, BrandId = 109 },
                new Medicine { Id = 251, GenericName = "Physiogel ", Inscription = "Ai Lotion", Description = null, BrandId = 109 },
                new Medicine { Id = 252, GenericName = "Ampicillin IV", Inscription = null, Description = "1gm", BrandId = 110 },
                new Medicine { Id = 253, GenericName = "Ampicillin IV", Inscription = null, Description = "750mg", BrandId = 110 },
                new Medicine { Id = 254, GenericName = "Ampicillin IV", Inscription = null, Description = "500mg", BrandId = 110 },
                new Medicine { Id = 255, GenericName = "Ampicillin IV", Inscription = null, Description = "250mg", BrandId = 110 },
                new Medicine { Id = 256, GenericName = "Mefenamic Acid", Inscription = "Cap", Description = "500mg", BrandId = 111 },
                new Medicine { Id = 257, GenericName = "Mefenamic Acid", Inscription = "Susp", Description = "50mg/5ml", BrandId = 111 },
                new Medicine { Id = 258, GenericName = "Mefenamic Acid", Inscription = "Cap", Description = "250mg", BrandId = 111 },
                new Medicine { Id = 259, GenericName = "Paracetamol", Inscription = "Suppository", Description = "125mg", BrandId = 112 },
                new Medicine { Id = 260, GenericName = "Paracetamol", Inscription = "Suppository", Description = "250mg", BrandId = 112 },
                new Medicine { Id = 261, GenericName = "Prednisone", Inscription = null, Description = null, BrandId = 113 },
                new Medicine { Id = 262, GenericName = "Prednisone", Inscription = "Syrup", Description = "10mg/5ml", BrandId = 113 },
                new Medicine { Id = 263, GenericName = "Prednisolone", Inscription = "Syrup", Description = "20mg/5ml", BrandId = 114 },
                new Medicine { Id = 264, GenericName = "Multivitamins", Inscription = "Syrup", Description = null, BrandId = 115 },
                new Medicine { Id = 265, GenericName = "Cloxacillin", Inscription = "Susp", Description = "250mg/5ml", BrandId = 116 },
                new Medicine { Id = 266, GenericName = "Cloxacillin", Inscription = "Susp", Description = "250mg/5ml", BrandId = 116 },
                new Medicine { Id = 267, GenericName = "Cloxacillin", Inscription = "Susp", Description = "125mg/5ml", BrandId = 116 },
                new Medicine { Id = 268, GenericName = "Salbutamol", Inscription = "Nebule", Description = "2.5mg/2.5ml", BrandId = 117 },
                new Medicine { Id = 269, GenericName = "Salbutamol", Inscription = "Tab", Description = "2mg", BrandId = 118 },
                new Medicine { Id = 270, GenericName = "Salbutamol", Inscription = "Syrup", Description = "2mg/5ml", BrandId = 118 },
                new Medicine { Id = 271, GenericName = "Salbutamol + Ipratropium Bromide", Inscription = "Nebule", Description = null, BrandId = 119 },
                new Medicine { Id = 272, GenericName = "Terbutaline ", Inscription = "Syrup", Description = "1.5mg/5ml", BrandId = 120 },
                new Medicine { Id = 273, GenericName = "Simethicone", Inscription = "Drops", Description = null, BrandId = 121 },
                new Medicine { Id = 274, GenericName = "Cloxacillin", Inscription = "Susp", Description = "250mg/5ml", BrandId = 122 },
                new Medicine { Id = 275, GenericName = "Cloxacillin", Inscription = "Susp", Description = "250mg/5ml", BrandId = 122 },
                new Medicine { Id = 276, GenericName = "Cloxacillin", Inscription = "Susp", Description = "125mg/5ml", BrandId = 122 },
                new Medicine { Id = 277, GenericName = "Metronidazole", Inscription = "Syrup", Description = "125mg/5ml", BrandId = 123 },
                new Medicine { Id = 278, GenericName = "Prednisolone", Inscription = "Syrup", Description = "20mg/5ml", BrandId = 124 },
                new Medicine { Id = 279, GenericName = "Ampicillin IV", Inscription = null, Description = "250mg", BrandId = 125 },
                new Medicine { Id = 280, GenericName = "Ampicillin IV", Inscription = null, Description = "1gm", BrandId = 125 },
                new Medicine { Id = 281, GenericName = "Ampicillin IV", Inscription = null, Description = "750mg", BrandId = 125 },
                new Medicine { Id = 282, GenericName = "Ampicillin IV", Inscription = null, Description = "500mg", BrandId = 125 },
                new Medicine { Id = 283, GenericName = "Sodium Chloride", Inscription = "Nasal spray", Description = null, BrandId = 126 },
                new Medicine { Id = 284, GenericName = "Sodium Chloride", Inscription = "Nasal drops", Description = null, BrandId = 126 },
                new Medicine { Id = 285, GenericName = "Ferrous Gluconate", Inscription = "Syrup", Description = null, BrandId = 127 },
                new Medicine { Id = 286, GenericName = "Cefalexin", Inscription = "Susp", Description = "250mg/5ml", BrandId = 128 },
                new Medicine { Id = 287, GenericName = "Cefalexin", Inscription = "Susp", Description = "125mg/5ml", BrandId = 128 },
                new Medicine { Id = 288, GenericName = "Cefalexin", Inscription = "Drops", Description = "100mg/ml", BrandId = 128 },
                new Medicine { Id = 289, GenericName = "Salmeterol + Fluticasone Propionate", Inscription = "MDI", Description = "25/250", BrandId = 129 },
                new Medicine { Id = 290, GenericName = "Salmeterol + Fluticasone Propionate", Inscription = "MDI", Description = "25/125", BrandId = 129 },
                new Medicine { Id = 291, GenericName = "Salmeterol + Fluticasone Propionate", Inscription = "MDI", Description = "25/50", BrandId = 129 },
                new Medicine { Id = 292, GenericName = "Montelukast", Inscription = "Tab", Description = "10mg", BrandId = 130 },
                new Medicine { Id = 293, GenericName = "Montelukast", Inscription = "Tab", Description = "5mg", BrandId = 130 },
                new Medicine { Id = 294, GenericName = "Montelukast", Inscription = "Tab", Description = "4mg", BrandId = 130 },
                new Medicine { Id = 295, GenericName = "Montelukast", Inscription = "Glanules", Description = "4mg", BrandId = 130 },
                new Medicine { Id = 296, GenericName = "Naproxen Sodium", Inscription = "Tab", Description = "550mg", BrandId = 131 },
                new Medicine { Id = 297, GenericName = "Naproxen Sodium", Inscription = "Tab", Description = "275mg", BrandId = 131 },
                new Medicine { Id = 298, GenericName = "Carbocisteine", Inscription = "Syrup", Description = "100mg/5ml", BrandId = 132 },
                new Medicine { Id = 299, GenericName = "Carbocisteine", Inscription = "Drops", Description = "50mg/ml", BrandId = 132 },
                new Medicine { Id = 300, GenericName = "Salbutamol + Guaifenesin", Inscription = "Syrup", Description = null, BrandId = 133 },
                new Medicine { Id = 301, GenericName = "Fluocloxacillin", Inscription = "Cap", Description = "500mg", BrandId = 134 },
                new Medicine { Id = 302, GenericName = "Fluocloxacillin", Inscription = "Cap", Description = "250mg", BrandId = 134 },
                new Medicine { Id = 303, GenericName = "Fluocloxacillin", Inscription = "Susp", Description = "125mg/5ml", BrandId = 134 },
                new Medicine { Id = 304, GenericName = "Phenoxymethylpenicillin K", Inscription = "Cap", Description = "250mg", BrandId = 135 },
                new Medicine { Id = 305, GenericName = "Phenoxymethylpenicillin K", Inscription = "Cap", Description = "500mg", BrandId = 135 },
                new Medicine { Id = 306, GenericName = "Paracetamol", Inscription = "Susp", Description = "250mg/5ml", BrandId = 136 },
                new Medicine { Id = 307, GenericName = "Paracetamol", Inscription = "Syrup", Description = "120mg/5ml", BrandId = 136 },
                new Medicine { Id = 308, GenericName = "Paracetamol", Inscription = "Tab", Description = "250mg", BrandId = 136 },
                new Medicine { Id = 309, GenericName = "Paracetamol", Inscription = "Syrup", Description = "250mg/5ml", BrandId = 136 },
                new Medicine { Id = 310, GenericName = "Paracetamol", Inscription = "Tab", Description = "500mg", BrandId = 136 },
                new Medicine { Id = 311, GenericName = "Paracetamol", Inscription = "Tab", Description = "325mg", BrandId = 136 },
                new Medicine { Id = 312, GenericName = "Paracetamol", Inscription = "Drops", Description = "100mg/ml", BrandId = 136 },
                new Medicine { Id = 313, GenericName = "Cefixime", Inscription = "Cap", Description = "100mg", BrandId = 137 },
                new Medicine { Id = 314, GenericName = "Cefixime", Inscription = "Susp", Description = "100mg/5ml", BrandId = 137 },
                new Medicine { Id = 315, GenericName = "Cefixime", Inscription = "Cap", Description = "200mg", BrandId = 137 },
                new Medicine { Id = 316, GenericName = "Cefixime", Inscription = "Drops", Description = "20mg/ml", BrandId = 137 },
                new Medicine { Id = 317, GenericName = "Cotrimoxazole", Inscription = "Susp", Description = "400mg/80/5ml", BrandId = 138 },
                new Medicine { Id = 318, GenericName = "Cefixime", Inscription = "Cap", Description = "200mg", BrandId = 139 },
                new Medicine { Id = 319, GenericName = "Cefixime", Inscription = "Drops", Description = "20mg/ml", BrandId = 139 },
                new Medicine { Id = 320, GenericName = "Cefixime", Inscription = "Drops", Description = "100mg/5ml", BrandId = 139 },
                new Medicine { Id = 321, GenericName = "Cefixime", Inscription = "Cap", Description = "100mg", BrandId = 139 },
                new Medicine { Id = 322, GenericName = "Salbutamol", Inscription = "Nebule", Description = "2.5mg/2.5ml", BrandId = 140 },
                new Medicine { Id = 323, GenericName = "Salbutamol", Inscription = "MDI", Description = "100mgm/Inhalation", BrandId = 140 },
                new Medicine { Id = 324, GenericName = "Salbutamol", Inscription = "Tab", Description = "2mg", BrandId = 140 },
                new Medicine { Id = 325, GenericName = "Salbutamol + Guaifenesin", Inscription = "Syrup", Description = null, BrandId = 141 },
                new Medicine { Id = 326, GenericName = "Cetirizine", Inscription = "Drops", Description = "10mg/ml", BrandId = 142 },
                new Medicine { Id = 327, GenericName = "Cetirizine", Inscription = "Solution", Description = "1mg/ml", BrandId = 142 },
                new Medicine { Id = 328, GenericName = "Domperidone", Inscription = "Drops", Description = "5mg/ml", BrandId = 143 },
                new Medicine { Id = 329, GenericName = "Domperidone", Inscription = "Syrup", Description = "5mg/5ml", BrandId = 143 },
                new Medicine { Id = 330, GenericName = "Cefaclor", Inscription = "Susp", Description = "125mg/5ml", BrandId = 144 },
                new Medicine { Id = 331, GenericName = "Cefaclor", Inscription = "Susp", Description = "250mg/5ml", BrandId = 144 },
                new Medicine { Id = 332, GenericName = "Cefaclor", Inscription = "Drops", Description = "50mg/ml", BrandId = 144 },
                new Medicine { Id = 333, GenericName = "Cefalexin", Inscription = "Susp", Description = "250mg/5ml", BrandId = 145 },
                new Medicine { Id = 334, GenericName = "Cefalexin", Inscription = "Susp", Description = "125mg/5ml", BrandId = 145 },
                new Medicine { Id = 335, GenericName = "Cefalexin", Inscription = "Drops", Description = "100mg/ml", BrandId = 145 },
                new Medicine { Id = 336, GenericName = "Levocetirizine Diltci", Inscription = "Syrup", Description = "5mg/ml", BrandId = 146 },
                new Medicine { Id = 337, GenericName = "Levocetirizine Diltci", Inscription = "Tab", Description = "5mg", BrandId = 146 },
                new Medicine { Id = 338, GenericName = "Levocetirizine Diltci", Inscription = "Drops", Description = "5mg/ml", BrandId = 146 },
                new Medicine { Id = 339, GenericName = "Brompheniramine Maleate + Phenylpropanolamine", Inscription = "Drops", Description = null, BrandId = 147 },
                new Medicine { Id = 340, GenericName = "Brompheniramine Maleate + Phenylpropanolamine", Inscription = "Syrup", Description = null, BrandId = 147 },
                new Medicine { Id = 341, GenericName = "Cefuroxime", Inscription = "Cap", Description = "250mg", BrandId = 148 },
                new Medicine { Id = 342, GenericName = "Azithromycin", Inscription = "Tab", Description = "500mg", BrandId = 149 },
                new Medicine { Id = 343, GenericName = "Azithromycin", Inscription = "Tab", Description = "250mg", BrandId = 149 },
                new Medicine { Id = 344, GenericName = "Azithromycin", Inscription = "Susp", Description = "200mg/5ml", BrandId = 149 },
                new Medicine { Id = 345, GenericName = "Cefuroxime", Inscription = "Susp", Description = "250mg/5ml", BrandId = 150 },
                new Medicine { Id = 346, GenericName = "Cefuroxime", Inscription = "Susp", Description = "125mg/5ml", BrandId = 150 },
                new Medicine { Id = 347, GenericName = "Azithromycin", Inscription = "Tab", Description = "500mg", BrandId = 151 },
                new Medicine { Id = 348, GenericName = "Azithromycin", Inscription = "Susp", Description = "200mg/5ml", BrandId = 151 },
                new Medicine { Id = 349, GenericName = "Azithromycin", Inscription = "Tab", Description = "250mg", BrandId = 152 },
                new Medicine { Id = 350, GenericName = "Acyclovir", Inscription = "Tab", Description = "400mg", BrandId = 152 },
                new Medicine { Id = 351, GenericName = "Acyclovir", Inscription = "Tab", Description = "200mg", BrandId = 152 },
                new Medicine { Id = 352, GenericName = "Cetirizine", Inscription = "Drops", Description = "10mg/ml", BrandId = 153 },
                new Medicine { Id = 353, GenericName = "Cetirizine", Inscription = "Solution", Description = "1mg/ml", BrandId = 153 },
                new Medicine { Id = 354, GenericName = "Ambroxol", Inscription = "Tab", Description = "30mg", BrandId = 89 },
                new Medicine { Id = 355, GenericName = "Ambroxol", Inscription = "Syrup", Description = "30mg/5ml", BrandId = 89 },
                new Medicine { Id = 356, GenericName = "Ambroxol", Inscription = "Syrup", Description = "15mg/5ml", BrandId = 89 });
        }
    }
}
