using Microsoft.EntityFrameworkCore;
using SaintJudeHospital.Data.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace SaintJudeHospital.Data.Seed
{
    public class AppDbContextInitializer
    {
        private static ModelBuilder _builder;

        public static void Load(ModelBuilder builder)
        {
            _builder = builder;

            UsersRole();
            Users();
            Immunizes();
            Symtoms();
        }

        private static void UsersRole()
        {
            _builder.Entity<Role>().HasData(
                new Role { RoleId = 1, Name = "Administrator" },
                new Role { RoleId = 2, Name = "StandardUser"});
        }

        private static void Users()
        {
            _builder.Entity<User>().HasData(
                new User { FirstName = "Carl", LastName = "Tanilon", Password = "1234", RoleId = 1, Username = "carl" , UserId = 1});
        }

        private static void Immunizes()
        {
            _builder.Entity<Immunize>().HasData(
                new Immunize { Id = 1, Name = "HEXA", Amount = 3000 },
                new Immunize { Id = 2, Name = "PCV 10", Amount = 3200 },
                new Immunize { Id = 3, Name = "MEASLES", Amount = 750 },
                new Immunize { Id = 4, Name = "HIB", Amount = 1300 },
                new Immunize { Id = 5, Name = "MENINGO", Amount = 4000 },
                new Immunize { Id = 6, Name = "TYPHOID", Amount = 1300 },
                new Immunize { Id = 7, Name = "HEP A", Amount = 1800 },
                new Immunize { Id = 8, Name = "HEP B", Amount = 700 },
                new Immunize { Id = 9, Name = "TETRAXIM", Amount = 1600 },
                new Immunize { Id = 10, Name = "MMR", Amount = 1200 },
                new Immunize { Id = 11, Name = "CHICKEN POX", Amount = 2200 },
                new Immunize { Id = 12, Name = "PENTA", Amount = 2500 },
                new Immunize { Id = 13, Name = "BCG-1", Amount = 900 },
                new Immunize { Id = 14, Name = "MMR-V", Amount = 3000 },
                new Immunize { Id = 15, Name = "PNEUMO-23", Amount = 1700 },
                new Immunize { Id = 16, Name = "RABIES", Amount = 1700 },
                new Immunize { Id = 17, Name = "ROTARIX", Amount = 3000 },
                new Immunize { Id = 18, Name = "ROTATEQ", Amount = 2200 },
                new Immunize { Id = 19, Name = "FLU", Amount = 1000 },
                new Immunize { Id = 20, Name = "PCV", Amount = 4000 },
                new Immunize { Id = 21, Name = "BCG-2", Amount = 0 });
        }

        private static void Symtoms()
        {
            _builder.Entity<Symtom>().HasData(
                new Symtom { Id = 1, Name = "Bleeding"},
                new Symtom { Id = 2, Name = "Bruise"},
                new Symtom { Id = 3, Name = "Cough"},
                new Symtom { Id = 4, Name = "Bites"},
                new Symtom { Id = 5, Name = "Fever"},
                new Symtom { Id = 6, Name = "Cold"},
                new Symtom { Id = 7, Name = "Difficulty in swallowing" },
                new Symtom { Id = 8, Name = "Ear discharge"},
                new Symtom { Id = 9, Name = "Ear ache/pain"},
                new Symtom { Id = 10, Name = "Constipation"},
                new Symtom { Id = 11, Name = "Diarrhea"},
                new Symtom { Id = 12, Name = "Hair fall"},
                new Symtom { Id = 13, Name = "Abdominal pain"},
                new Symtom { Id = 14, Name = "Deformity"},
                new Symtom { Id = 15, Name = "Headache"},
                new Symtom { Id = 16, Name = "Infected wounds"},
                new Symtom { Id = 17, Name = "Itchness"},
                new Symtom { Id = 18, Name = "Loss of consciousness"},
                new Symtom { Id = 19, Name = "Mass"},
                new Symtom { Id = 20, Name = "Joint pain"},
                new Symtom { Id = 21, Name = "Muscle pain"},
                new Symtom { Id = 22, Name = "Skin lesions"},
                new Symtom { Id = 23, Name = "Trauma"},
                new Symtom { Id = 24, Name = "Pain urination"},
                new Symtom { Id = 25, Name = "Rushes"},
                new Symtom { Id = 26, Name = "Less appetite"},
                new Symtom { Id = 27, Name = "LBM"},
                new Symtom { Id = 28, Name = "Vomiting"},
                new Symtom { Id = 29, Name = "Dysuria"},
                new Symtom { Id = 30, Name = "Rashes"},
                new Symtom { Id = 31, Name = "Dysphagia"},
                new Symtom { Id = 32, Name = "Vaginal Discharge"},
                new Symtom { Id = 33, Name = "Urticarial rash"},
                new Symtom { Id = 34, Name = "Eye discharge"},
                new Symtom { Id = 35, Name = "Chest gurgling"},
                new Symtom { Id = 36, Name = "Epistaxis"},
                new Symtom { Id = 37, Name = "Pustules"},
                new Symtom { Id = 38, Name = "Nasal congestion"});
        }

        private static void Brands()
        {
            _builder.Entity<Brand>().HasData(
                new Brand { Id = 1, Name = "Activent" },
                new Brand { Id = 2, Name = "Advil" },
                new Brand { Id = 3, Name = "Allerkid" },
                new Brand { Id = 4, Name = "Alloxygen" },
                new Brand { Id = 5, Name = "Alnix" },
                new Brand { Id = 6, Name = "Alvedon" },
                new Brand { Id = 7, Name = "Ambrolex" },
                new Brand { Id = 8, Name = "Amoclav" },
                new Brand { Id = 9, Name = "Amoxil" },
                new Brand { Id = 10, Name = "Ampicin" },
                new Brand { Id = 11, Name = "Ansimar" },
                new Brand { Id = 12, Name = "Antiox" },
                new Brand { Id = 13, Name = "Asfrenon" },
                new Brand { Id = 14, Name = "Asfrenon Expt" },
                new Brand { Id = 15, Name = "Asmalin" },
                new Brand { Id = 16, Name = "Asmalin Broncho" },
                new Brand { Id = 17, Name = "Augmentin" },
                new Brand { Id = 18, Name = "Avamys" },
                new Brand { Id = 19, Name = "Azith" },
                new Brand { Id = 20, Name = "Bacidal" },
                new Brand { Id = 21, Name = "Bactroban" },
                new Brand { Id = 22, Name = "Bambec"},
                new Brand { Id = 23, Name = "Bioclauid" },
                new Brand { Id = 24, Name = "Biogesic" },
                new Brand { Id = 25, Name = "Bricanyl" },
                new Brand { Id = 26, Name = "Broncaire Expt" },
                new Brand { Id = 27, Name = "Bronchofen" },
                new Brand { Id = 28, Name = "Calmoseptine" },
                new Brand { Id = 29, Name = "Calpol" },
                new Brand { Id = 30, Name = "Ceclor" },
                new Brand { Id = 31, Name = "Cefalin" },
                new Brand { Id = 32, Name = "Ceporex" },
                new Brand { Id = 33, Name = "Cherifer" },
                new Brand { Id = 34, Name = "Chloromycetin" },
                new Brand { Id = 35, Name = "Clariget" },
                new Brand { Id = 36, Name = "Clarithro-Natrapharm Klaryz" },
                new Brand { Id = 37, Name = "Clarithro-natrapharm" },
                new Brand { Id = 38, Name = "Clarithrocid" },
                new Brand { Id = 39, Name = "Clotrasone" },
                new Brand { Id = 40, Name = "Combantrin" },
                new Brand { Id = 41, Name = "Combivent" },
                new Brand { Id = 42, Name = "Daktarin" },
                new Brand { Id = 43, Name = "Dalacin C" },
                new Brand { Id = 44, Name = "Dg" },
                new Brand { Id = 45, Name = "Dilatair" },
                new Brand { Id = 46, Name = "Dimetapp" },
                new Brand { Id = 47, Name = "Disudrin" },
                new Brand { Id = 48, Name = "Dolan" },
                new Brand { Id = 49, Name = "Dolfenal" },
                new Brand { Id = 50, Name = "Duavent" },
                new Brand { Id = 51, Name = "E Zinc" },
                new Brand { Id = 52, Name = "Elica" },
                new Brand { Id = 53, Name = "Erceflora" },
                new Brand { Id = 54, Name = "Ercefuryl" },
                new Brand { Id = 55, Name = "Essentiale Forte" },
                new Brand { Id = 56, Name = "Expel" },
                new Brand { Id = 57, Name = "Faspic" },
                new Brand { Id = 58, Name = "Flagyl" },
                new Brand { Id = 59, Name = "Flanax" },
                new Brand { Id = 60, Name = "Fluimucil" },
                new Brand { Id = 61, Name = "Fucidin" },
                new Brand { Id = 62, Name = "Fucidin-h" },
                new Brand { Id = 63, Name = "Fucithalmic" },
                new Brand { Id = 64, Name = "Furoxone" },
                new Brand { Id = 65, Name = "Garamycin" },
                new Brand { Id = 66, Name = "Gardan" },
                new Brand { Id = 67, Name = "Heraclene" },
                new Brand { Id = 68, Name = "Himox" },
                new Brand { Id = 69, Name = "Hisdec" },
                new Brand { Id = 70, Name = "Hydrite" },
                new Brand { Id = 71, Name = "Ilosone" },
                new Brand { Id = 72, Name = "Immunosine" },
                new Brand { Id = 73, Name = "Iterax" },
                new Brand { Id = 74, Name = "Jetepar" },
                new Brand { Id = 75, Name = "Kastair" },
                new Brand { Id = 76, Name = "Katrex" },
                new Brand { Id = 77, Name = "Klarizid" },
                new Brand { Id = 78, Name = "Klaz" },
                new Brand { Id = 79, Name = "Locetar" },
                new Brand { Id = 80, Name = "Loviscol" },
                new Brand { Id = 81, Name = "Maalox" },
                new Brand { Id = 82, Name = "Medicol" },
                new Brand { Id = 83, Name = "Meptin" },
                new Brand { Id = 84, Name = "Montemax" },
                new Brand { Id = 85, Name = "Montiget" },
                new Brand { Id = 86, Name = "Motilium" },
                new Brand { Id = 87, Name = "Movelax" },
                new Brand { Id = 88, Name = "Muconase" },
                new Brand { Id = 89, Name = "Mucosolvan" },
                new Brand { Id = 90, Name = "Myonal" },
                new Brand { Id = 91, Name = "Myremol" },
                new Brand { Id = 92, Name = "Napran" },
                new Brand { Id = 93, Name = "Naprex" },
                new Brand { Id = 94, Name = "Nasatapp" },
                new Brand { Id = 95, Name = "Nasathera" },
                new Brand { Id = 96, Name = "Nasoclear" },
                new Brand { Id = 97, Name = "Natravox" },
                new Brand { Id = 98, Name = "Neozep" },
                new Brand { Id = 99, Name = "Nuelin" },
                new Brand { Id = 100, Name = "Omepron" },
                new Brand { Id = 101, Name = "Opigesic" },
                new Brand { Id = 102, Name = "Optipred" },
                new Brand { Id = 103, Name = "Orastin" },
                new Brand { Id = 104, Name = "Pediachlor" },
                new Brand { Id = 105, Name = "Pediamox" },
                new Brand { Id = 106, Name = "Pediatapp" },
                new Brand { Id = 107, Name = "Penachlor" },
                new Brand { Id = 108, Name = "Pharex" },
                new Brand { Id = 109, Name = "Physiogel" },
                new Brand { Id = 110, Name = "Polypen" },
                new Brand { Id = 111, Name = "Ponstan" },
                new Brand { Id = 112, Name = "Poro" },
                new Brand { Id = 113, Name = "Pred 10" },
                new Brand { Id = 114, Name = "Pred 20" },
                new Brand { Id = 115, Name = "Propan Tlc" },
                new Brand { Id = 116, Name = "Prostaphlin-A" },
                new Brand { Id = 117, Name = "Provexcel" },
                new Brand { Id = 118, Name = "Prox-S" },
                new Brand { Id = 119, Name = "Pulmodual" },
                new Brand { Id = 120, Name = "Pulmoxcel" },
                new Brand { Id = 121, Name = "Restime" },
                new Brand { Id = 122, Name = "Ritemed" },
                new Brand { Id = 123, Name = "Rodazid" },
                new Brand { Id = 124, Name = "Romamed" },
                new Brand { Id = 125, Name = "Rotocin" },
                new Brand { Id = 126, Name = "Salinase" },
                new Brand { Id = 127, Name = "Sangobion" },
                new Brand { Id = 128, Name = "Selzef" },
                new Brand { Id = 129, Name = "Seretide" },
                new Brand { Id = 130, Name = "Singulair" },
                new Brand { Id = 131, Name = "Skelan" },
                new Brand { Id = 132, Name = "Solmux Broncho" },
                new Brand { Id = 133, Name = "Stafloxin" },
                new Brand { Id = 134, Name = "Sumapen" },
                new Brand { Id = 135, Name = "Tempra" },
                new Brand { Id = 136, Name = "Tergecet" },
                new Brand { Id = 137, Name = "Trizole" },
                new Brand { Id = 138, Name = "Ultraxime" },
                new Brand { Id = 139, Name = "Ventolin" },
                new Brand { Id = 140, Name = "Ventolin Expt" },
                new Brand { Id = 141, Name = "Virlix" },
                new Brand { Id = 142, Name = "Vometa" },
                new Brand { Id = 143, Name = "Xelent" },
                new Brand { Id = 144, Name = "Xinflex" },
                new Brand { Id = 145, Name = "Xyzal" },
                new Brand { Id = 146, Name = "Zeditapp" },
                new Brand { Id = 147, Name = "Zegen" },
                new Brand { Id = 148, Name = "Zenith" },
                new Brand { Id = 149, Name = "Zinnat" },
                new Brand { Id = 150, Name = "Zithromax" },
                new Brand { Id = 151, Name = "Zovirax" },
                new Brand { Id = 152, Name = "Zyrtec" });
        }

        private static void Medicines()
        {
            _builder.Entity<Medicine>().HasData(
                new Medicine { Id = 1, GenericName = "Cetirizine", Inscription = "Tab", Description = "10mg", BrandId = null },
                new Medicine { Id = 2, GenericName = "Amoxicillin", Inscription = "Cap", Description = "500mg", BrandId = null },
                new Medicine { Id = 3, GenericName = "Amoxicillin", Inscription = "Cap", Description = "250mg", BrandId = null },
                new Medicine { Id = 4, GenericName = "Co Amoxiclav", Inscription = "Tab", Description = "375mg", BrandId = null },
                new Medicine { Id = 5, GenericName = "Prednisolone", Inscription = "Tab", Description = "30mg", BrandId = null },
                new Medicine { Id = 6, GenericName = "Prednisolone", Inscription = "Tab", Description = "20mg", BrandId = null },
                new Medicine { Id = 7, GenericName = "Prednisolone", Inscription = "Tab", Description = "5mg", BrandId = null },
                new Medicine { Id = 8, GenericName = "Gentamicin IV", Inscription = "Amp", Description = "80mg/5ml", BrandId = null },
                new Medicine { Id = 9, GenericName = "Gentamicin IV", Inscription = "Amp", Description = "40mg/5ml", BrandId = null },
                new Medicine { Id = 10, GenericName = "Broncho Vaxom", Inscription = "Pedia Cap", Description = null, BrandId = null },
                new Medicine { Id = 11, GenericName = "Glycerin", Inscription = "Pediatric suppository", Description = null, BrandId = null },
                new Medicine { Id = 12, GenericName = "Glycerin", Inscription = "Pediatric suppository", Description = null, BrandId = null },
                new Medicine { Id = 13, GenericName = "Salbutamol", Inscription = "Tab", Description = "2mg", BrandId = 1 },
                new Medicine { Id = 14, GenericName = "Salbutamol", Inscription = "Syrup", Description = "2mg/5ml", BrandId = 1 },
                new Medicine { Id = 15, GenericName = "Ibuprofen", Inscription = "Susp", Description = "100mg/5ml", BrandId = 2 },
                new Medicine { Id = 16, GenericName = "Ibuprofen", Inscription = "Susp", Description = "200mg/5ml", BrandId = 2 },
                new Medicine { Id = 17, GenericName = "Ibuprofen", Inscription = "Cap", Description = "200mg", BrandId = 2 },
                new Medicine { Id = 18, GenericName = "Ibuprofen", Inscription = "Drops", Description = "100mg/2.5ml", BrandId = 2 },
                new Medicine { Id = 19, GenericName = "Cetirizine", Inscription = "Syrup", Description = "5mg/5ml", BrandId = 3 },
                new Medicine { Id = 20, GenericName = "Cetirizine", Inscription = "Drops", Description = "2.5mg/ml", BrandId = 3 },
                new Medicine { Id = 21, GenericName = "Terbutaline", Inscription = "Syrup", Description = "1.5mg/5ml", BrandId = null },
                new Medicine { Id = 22, GenericName = "Cetirizine", Inscription = "Tab", Description = "10mg", BrandId = 4 },
                new Medicine { Id = 23, GenericName = "Cetirizine", Inscription = "Syrup", Description = "5mg/5ml", BrandId = 4 },
                new Medicine { Id = 24, GenericName = "Cetirizine", Inscription = "Drops", Description = "2.5mg/ml", BrandId = 5 },
                new Medicine { Id = 25, GenericName = "Paracetamol", Inscription = "Tab", Description = "250mg", BrandId = 5 },
                new Medicine { Id = 26, GenericName = "Paracetamol", Inscription = "Tab", Description = "325mg", BrandId = 5 },
                new Medicine { Id = 27, GenericName = "Paracetamol", Inscription = "Tab", Description = "500mg", BrandId = 5 },
                new Medicine { Id = 28, GenericName = "Paracetamol", Inscription = "Syrup", Description = "120mg/5ml", BrandId = 6 },
                new Medicine { Id = 29, GenericName = "Paracetamol", Inscription = "Drops", Description = "100ml", BrandId = 6 },
                new Medicine { Id = 30, GenericName = "Ambroxol", Inscription = "Tab", Description = "30mg", BrandId = 7 },
                new Medicine { Id = 31, GenericName = "Ambroxol", Inscription = "Syrup", Description = "30mg/3ml", BrandId = 7 },
                new Medicine { Id = 32, GenericName = "Ambroxol", Inscription = "Syrup", Description = "15mg/5ml", BrandId = 7 },
                new Medicine { Id = 33, GenericName = "Ambroxol", Inscription = "Drops", Description = "7.5mg/ml", BrandId = 7 },
                new Medicine { Id = 34, GenericName = "Co Amoxiclav", Inscription = "Susp", Description = "457mg/5ml", BrandId = 8 },
                new Medicine { Id = 35, GenericName = "Co Amoxiclav", Inscription = "Susp", Description = "228mg/5ml", BrandId = 8 },
                new Medicine { Id = 36, GenericName = "Co Amoxiclav", Inscription = "Susp", Description = "156mg/5ml", BrandId = 8 },
                new Medicine { Id = 37, GenericName = "Co Amoxiclav", Inscription = "Susp", Description = "312mg/5ml", BrandId = 8 },
                new Medicine { Id = 38, GenericName = "Amoxicillin", Inscription = "Susp", Description = "250mg/5ml", BrandId = 9 },
                new Medicine { Id = 39, GenericName = "Amoxicillin", Inscription = "Drops", Description = "100mg/ml", BrandId = 9 },
                new Medicine { Id = 40, GenericName = "Amoxicillin", Inscription = "Susp", Description = "125mg/ml", BrandId = 9 },
                new Medicine { Id = 41, GenericName = "Ampicillin IV", Inscription = null, Description = "1mg", BrandId = 10 },
                new Medicine { Id = 42, GenericName = "Ampicillin IV", Inscription = null, Description = "500mg", BrandId = 10 },
                new Medicine { Id = 43, GenericName = "Ampicillin IV", Inscription = null, Description = "750mg", BrandId = 10 },
                new Medicine { Id = 44, GenericName = "Ampicillin IV", Inscription = null, Description = "250mg", BrandId = 10 },
                new Medicine { Id = 45, GenericName = "Doxofylline", Inscription = "Tab", Description = "100mg", BrandId = 11 },
                new Medicine { Id = 46, GenericName = "Doxofylline", Inscription = "Syrup", Description = "100mg/5ml", BrandId = 11 },
                new Medicine { Id = 47, GenericName = "Mebendazole", Inscription = "Tab", Description = "100mg", BrandId = 12 },
                new Medicine { Id = 48, GenericName = "Mebendazole", Inscription = "Susp", Description = "20mg/ml", BrandId = 12 },
                new Medicine { Id = 49, GenericName = "Mebendazole", Inscription = "Tab", Description = "500mg", BrandId = 12 },
                new Medicine { Id = 50, GenericName = "Mebendazole", Inscription = "Susp", Description = "50mg/ml", BrandId = 12 },
                new Medicine { Id = 51, GenericName = "Salbutamol", Inscription = "Syrup", Description = "2mg/5ml", BrandId = 13 },
                new Medicine { Id = 52, GenericName = "Salbutamol + Guaifenesin", Inscription = "Syrup", Description = null, BrandId = 14 },
                new Medicine { Id = 53, GenericName = "Salbutamol", Inscription = "MDI", Description = "100mgm/Inhalation", BrandId = 15 },
                new Medicine { Id = 54, GenericName = "Salbutamol", Inscription = "Nebule", Description = "2.5mg/2.5ml", BrandId = 15 },
                new Medicine { Id = 55, GenericName = "Salbutamol", Inscription = "Tab", Description = "2mg", BrandId = 15 },
                new Medicine { Id = 56, GenericName = "Salbutamol", Inscription = "Syrup", Description = "2mg/5ml", BrandId = 15 },
                new Medicine { Id = 57, GenericName = "Salbutamol + Guaifenesin", Inscription = "Syrup", Description = null, BrandId = 16 },
                new Medicine { Id = 58, GenericName = "Coamoxiclav", Inscription = "Tab", Description = "625mg", BrandId = 17 },
                new Medicine { Id = 59, GenericName = "Coamoxiclav", Inscription = "Susp", Description = "156mg/5ml", BrandId = 17 },
                new Medicine { Id = 60, GenericName = "Coamoxiclav", Inscription = "Susp", Description = "457mg/5ml", BrandId = 17 },
                new Medicine { Id = 61, GenericName = "Coamoxiclav", Inscription = "Susp", Description = "228mg/5ml", BrandId = 17 },
                new Medicine { Id = 62, GenericName = "Coamoxiclav", Inscription = "Susp", Description = "312mg/5ml", BrandId = 17 },                        
                new Medicine { Id = 63, GenericName = "Fluticasone Furoate", Inscription = "Nasal Spray", Description = "27.5mgm/spray", BrandId = 18 },
                new Medicine { Id = 64, GenericName = "Azithromycin", Inscription = "Tab", Description = "500mg", BrandId = 19 },
                new Medicine { Id = 65, GenericName = "Azithromycin", Inscription = "Tab", Description = "250mg", BrandId = 19 },
                new Medicine { Id = 66, GenericName = "Azithromycin", Inscription = "Susp", Description = "200mg/5ml", BrandId = 19 },
                new Medicine { Id = 67, GenericName = "Cotrimoxazole", Inscription = "Tab", Description = "4oomg/80mg", BrandId = 20 },
                new Medicine { Id = 68, GenericName = "Mupirocin", Inscription = "Tube", Description = "Cream", BrandId = 21 },
                new Medicine { Id = 69, GenericName = "Bambuterol", Inscription = "Syrup", Description = "1mg/1ml", BrandId = 22 },
                new Medicine { Id = 70, GenericName = "Bambuterol", Inscription = "Tab", Description = "10mg", BrandId = 22 },
                new Medicine { Id = 71, GenericName = "Co Amoxiclav", Inscription = "Susp", Description = "125mg/5ml", BrandId = 23 },
                new Medicine { Id = 72, GenericName = "Co Amoxiclav", Inscription = "Susp", Description = "250mg/5ml", BrandId = 23 },
                new Medicine { Id = 73, GenericName = "Paracetamol", Inscription = "Susp", Description = "120mg/5ml", BrandId = 24 },
                new Medicine { Id = 74, GenericName = "Paracetamol", Inscription = "Tab", Description = "500mg", BrandId = 24 },
                new Medicine { Id = 75, GenericName = "Paracetamol", Inscription = "Syrup", Description = "250mg/5ml", BrandId = 24 },
                new Medicine { Id = 76, GenericName = "Paracetamol", Inscription = "Tab", Description = "250mg", BrandId = 24 },
                new Medicine { Id = 77, GenericName = "Paracetamol", Inscription = "Tab", Description = "325mg", BrandId = 24 },
                new Medicine { Id = 78, GenericName = "Paracetamol", Inscription = "Drops", Description = "100mg/ml", BrandId = 24 },
                new Medicine { Id = 79, GenericName = "Terbutaline", Inscription = "Syrup", Description = "1.5mg/5ml", BrandId = 25 },
                new Medicine { Id = 80, GenericName = "Salbutamol + Guaifenesin", Inscription = "Syrup", Description = null, BrandId = 26 },
                new Medicine { Id = 81, GenericName = "Phenylephrine Hcl + Chlorpheniramine Maleate", Inscription = "Syrup", Description = "5mg///1mg/5ml", BrandId = 27 },
                new Medicine { Id = 82, GenericName = "Phenylephrine Hcl + Chlorpheniramine Maleate", Inscription = "Syrup", Description = null, BrandId = 27 },
                new Medicine { Id = 83, GenericName = "Phenylephrine Hcl + Chlorpheniramine Maleate", Inscription = "drops", Description = null, BrandId = 27 },
                new Medicine { Id = 84, GenericName = "Calmoseptine", Inscription = "Ointment", Description = "Sachet", BrandId = 28 },
                new Medicine { Id = 85, GenericName = "Paracetamol", Inscription = "Susp", Description = "250mg/5ml", BrandId = 29 },
                new Medicine { Id = 86, GenericName = "Paracetamol", Inscription = "Tab", Description = "250mg", BrandId = 29 },
                new Medicine { Id = 87, GenericName = "Paracetamol", Inscription = "Tab", Description = "500mg", BrandId = 29 },
                new Medicine { Id = 88, GenericName = "Paracetamol", Inscription = "Tab", Description = "325mg", BrandId = 29 },
                new Medicine { Id = 89, GenericName = "Paracetamol", Inscription = "Syrup", Description = "120mg/5ml", BrandId = 29 },
                new Medicine { Id = 90, GenericName = "Paracetamol", Inscription = "Drops", Description = "100mg/ml", BrandId = 29 },
                new Medicine { Id = 91, GenericName = "Cefaclor", Inscription = "Susp", Description = "250mg/5ml", BrandId = 30 },
                new Medicine { Id = 92, GenericName = "Cefaclor", Inscription = "Susp", Description = "125mg/5ml", BrandId = 30 },
                new Medicine { Id = 93, GenericName = "Cefaclor + Guaifenesin", Inscription = "Drops", Description = "50mg/ml", BrandId = 30 },
                new Medicine { Id = 94, GenericName = "Cefalexin", Inscription = "Cap", Description = "500mg", BrandId = 31 },
                new Medicine { Id = 95, GenericName = "Cefalexin", Inscription = "Susp", Description = "250mg/5ml", BrandId = 31 },
                new Medicine { Id = 96, GenericName = "Cefalexin", Inscription = "Susp", Description = "125mg/5ml", BrandId = 31 },
                new Medicine { Id = 97, GenericName = "Cefalexin", Inscription = "Drops", Description = "100mg/ml", BrandId = 31 },
                new Medicine { Id = 98, GenericName = "Cefalexin", Inscription = "Susp", Description = "250mg/5ml", BrandId = 32 },
                new Medicine { Id = 99, GenericName = "Cefalexin", Inscription = "Susp", Description = "125mg/5ml", BrandId = 32 },
                new Medicine { Id = 100, GenericName = "Cefalexin", Inscription = "Drops", Description = "100mg/ml", BrandId = 32 },
                new Medicine { Id = 101, GenericName = "Multivitamins", Inscription = "Drops", Description = null, BrandId = 33 },
                new Medicine { Id = 102, GenericName = "Chloramphenicol", Inscription = "Cap", Description = "500mg", BrandId = 34 },
                new Medicine { Id = 103, GenericName = "Chloramphenicol", Inscription = "Susp", Description = "125mg/5ml", BrandId = 34 },
                new Medicine { Id = 104, GenericName = "Chloramphenicol", Inscription = "Cap", Description = "250mg", BrandId = 34 },
                new Medicine { Id = 105, GenericName = "Clarithromycin", Inscription = "Susp", Description = "125mg/5ml", BrandId = 35 },
                new Medicine { Id = 106, GenericName = "Clarithromycin", Inscription = "Tab", Description = "125mg/5ml", BrandId = 36 },
                new Medicine { Id = 107, GenericName = "Clarithromycin", Inscription = "Tab", Description = "500mg", BrandId = 36 },
                new Medicine { Id = 108, GenericName = "Clarithromycin", Inscription = "Susp", Description = "250mg/5ml", BrandId = 36 },
                new Medicine { Id = 109, GenericName = "Clarithromycin", Inscription = "Susp", Description = "125mg/5ml", BrandId = 37 },
                new Medicine { Id = 110, GenericName = "Clarithromycin", Inscription = "Tab", Description = "250mg", BrandId = 38 },
                new Medicine { Id = 111, GenericName = "Clarithromycin", Inscription = "Tab", Description = "500mg", BrandId = 38 },
                new Medicine { Id = 112, GenericName = "Clarithromycin", Inscription = "Susp", Description = "250mg/5ml", BrandId = 38 },
                new Medicine { Id = 113, GenericName = "Clarithromycin", Inscription = "Susp", Description = "125mg/5ml", BrandId = 38 },
                new Medicine { Id = 114, GenericName = "Clotrimazole + Betamethasone", Inscription = "Cream", Description = "Tube", BrandId = 39 },
                new Medicine { Id = 115, GenericName = "Pyrantel Pamoate", Inscription = "Tab", Description = "125mg", BrandId = 40 },
                new Medicine { Id = 116, GenericName = "Pyrantel Pamoate", Inscription = "Susp", Description = "125mg/5ml", BrandId = 40 },
                new Medicine { Id = 117, GenericName = "Salbutamol + Ipratropium Bromide", Inscription = "Nebule", Description = null, BrandId = 41 },
                new Medicine { Id = 118, GenericName = "Miconazole", Inscription = "Oral Gel", Description = "Tube", BrandId = 42 },
                new Medicine { Id = 119, GenericName = "Clindamycin", Inscription = "Susp", Description = "75mg/5ml", BrandId = 43 },
                new Medicine { Id = 120, GenericName = "Dg Milk", Inscription = "Can", Description = "400mg", BrandId = 44 },
                new Medicine { Id = 121, GenericName = "Doxofylline", Inscription = "Syrup", Description = "100mg/5ml", BrandId = 45 },
                new Medicine { Id = 122, GenericName = "Doxofylline", Inscription = "Tab", Description = "100mg", BrandId = 45 },
                new Medicine { Id = 123, GenericName = "Brompheniramine Maleate + Phenylephrine", Inscription = "Drops", Description = null, BrandId = 46},
                new Medicine { Id = 124, GenericName = "Brompheniramine Maleate + Phenylephrine", Inscription = "Syrup", Description = null, BrandId = 46 },
                new Medicine { Id = 125, GenericName = "Phenylpropanolamine", Inscription = "Syrup", Description = null, BrandId = 47 },
                new Medicine { Id = 126, GenericName = "Phenylpropanolamine", Inscription = "Drops", Description = null, BrandId = 47 },
                new Medicine { Id = 127, GenericName = "Ibuprofen", Inscription = "Susp", Description = "200mg/5ml", BrandId = 48 },
                new Medicine { Id = 128, GenericName = "Ibuprofen", Inscription = "susp", Description = "100mg/5ml", BrandId = 48 },
                new Medicine { Id = 129, GenericName = "Ibuprofen", Inscription = "Drops", Description = "100mg/2.5ml", BrandId = 48 },
                new Medicine { Id = 130, GenericName = "Mefenamic Acid", Inscription = "Cap", Description = "250mg", BrandId = 49 },
                new Medicine { Id = 131, GenericName = "Mefenamic Acid", Inscription = "Cap", Description = "500mg", BrandId = 49 },
                new Medicine { Id = 132, GenericName = "Salbutamol + Ipratropium Bromide", Inscription = "Nebule", Description = null, BrandId = 50 },
                new Medicine { Id = 133, GenericName = "Zinc Sulfate", Inscription = "Syrup", Description = null, BrandId = 51 },
                new Medicine { Id = 134, GenericName = "Zinc Sulfate", Inscription = "Drops", Description = null, BrandId = 51 },
                new Medicine { Id = 135, GenericName = "Mometasone Furoate", Inscription = "Lotion", Description = null, BrandId = 52 },
                new Medicine { Id = 136, GenericName = "Mometasone Furoate", Inscription = "Cream", Description = null, BrandId = 52 },
                new Medicine { Id = 137, GenericName = "Bacillus Clausii", Inscription = "Oral Solution", Description = null, BrandId = 53 },
                new Medicine { Id = 138, GenericName = "Nifuroxazide", Inscription = "Susp", Description = "218mg/5ml", BrandId = 54 },
                new Medicine { Id = 139, GenericName = "Nifuroxazide", Inscription = "Cap", Description = "200mg", BrandId = 54 },            
                new Medicine { Id = 140, GenericName = "Phospholipids", Inscription = "Cap", Description = "300mg", BrandId = 55 },
                new Medicine { Id = 141, GenericName = "Ambroxol", Inscription = "Tab", Description = "300mg", BrandId = 56 },
                new Medicine { Id = 142, GenericName = "Ambroxol", Inscription = "Syrup", Description = "30mg/5ml", BrandId = 56 },
                new Medicine { Id = 143, GenericName = "Ambroxol", Inscription = "Drops", Description = "7.5mg/5ml", BrandId = 56 },
                new Medicine { Id = 144, GenericName = "Ambroxol", Inscription = "Syrup", Description = "15mg/2.5ml", BrandId = 56 },
                new Medicine { Id = 145, GenericName = "Ibuprofen", Inscription = "Cap", Description = "400mg", BrandId = 57 },
                new Medicine { Id = 146, GenericName = "Ibuprofen", Inscription = "Cap", Description = "200mg", BrandId = 57 },
                new Medicine { Id = 147, GenericName = "Metronidazole", Inscription = "Tab", Description = "500mg", BrandId = 58 },
                new Medicine { Id = 148, GenericName = "Metronidazole", Inscription = "Syrup", Description = "25mg/1ml", BrandId = 58 },
                new Medicine { Id = 149, GenericName = "Metronidazole", Inscription = null, Description = null, BrandId = 58 },
                new Medicine { Id = 150, GenericName = "Naproxen Sodium", Inscription = "Tab", Description = "550mg", BrandId = 59 },
                new Medicine { Id = 151, GenericName = "Naproxen Sodium", Inscription = "Tab", Description = "275mg", BrandId = 59 },
                new Medicine { Id = 152, GenericName = "Acetylcysteine", Inscription = "Sachet", Description = "1000mg", BrandId = 60 },
                new Medicine { Id = 153, GenericName = "Acetylcysteine", Inscription = "Syrup", Description = "100mg/5ml", BrandId = 60 },
                new Medicine { Id = 154, GenericName = "Acetylcysteine", Inscription = "Sachet", Description = "200mg", BrandId = 60 });
        }
    }
}
