using Microsoft.EntityFrameworkCore;
using SaintJudeHospital.Data.Entity;
using System;
using System.Collections.Generic;
using System.Text;

namespace SaintJudeHospital.Data.Seed
{
    internal class Brands
    {
        public static void Data(ModelBuilder builder)
        {
            builder.Entity<Brand>().HasData(
                new Brand { Id = 1, Name = "Activent" },
                new Brand { Id = 2, Name = "Advil" },
                new Brand { Id = 3, Name = "Allerkid" },
                new Brand { Id = 4, Name = "Alloxygen" },
                new Brand { Id = 5, Name = "Alnix" },
                new Brand { Id = 6, Name = "Alvedon" },
                new Brand { Id = 7, Name = "Ambrolex" },
                new Brand { Id = 8, Name = "Amoclav" },
                new Brand { Id = 9, Name = "Amoxil" },
                new Brand { Id = 10, Name = "Ampicin" },
                new Brand { Id = 11, Name = "Ansimar" },
                new Brand { Id = 12, Name = "Antiox" },
                new Brand { Id = 13, Name = "Asfrenon" },
                new Brand { Id = 14, Name = "Asfrenon Expt" },
                new Brand { Id = 15, Name = "Asmalin" },
                new Brand { Id = 16, Name = "Asmalin Broncho" },
                new Brand { Id = 17, Name = "Augmentin" },
                new Brand { Id = 18, Name = "Avamys" },
                new Brand { Id = 19, Name = "Azith" },
                new Brand { Id = 20, Name = "Bacidal" },
                new Brand { Id = 21, Name = "Bactroban" },
                new Brand { Id = 22, Name = "Bambec" },
                new Brand { Id = 23, Name = "Bioclauid" },
                new Brand { Id = 24, Name = "Biogesic" },
                new Brand { Id = 25, Name = "Bricanyl" },
                new Brand { Id = 26, Name = "Broncaire Expt" },
                new Brand { Id = 27, Name = "Bronchofen" },
                new Brand { Id = 28, Name = "Calmoseptine" },
                new Brand { Id = 29, Name = "Calpol" },
                new Brand { Id = 30, Name = "Ceclor" },
                new Brand { Id = 31, Name = "Cefalin" },
                new Brand { Id = 32, Name = "Ceporex" },
                new Brand { Id = 33, Name = "Cherifer" },
                new Brand { Id = 34, Name = "Chloromycetin" },
                new Brand { Id = 35, Name = "Clariget" },
                new Brand { Id = 36, Name = "Clarithro-Natrapharm Klaryz" },
                new Brand { Id = 37, Name = "Clarithro-natrapharm" },
                new Brand { Id = 38, Name = "Clarithrocid" },
                new Brand { Id = 39, Name = "Clotrasone" },
                new Brand { Id = 40, Name = "Combantrin" },
                new Brand { Id = 41, Name = "Combivent" },
                new Brand { Id = 42, Name = "Daktarin" },
                new Brand { Id = 43, Name = "Dalacin C" },
                new Brand { Id = 44, Name = "Dg" },
                new Brand { Id = 45, Name = "Dilatair" },
                new Brand { Id = 46, Name = "Dimetapp" },
                new Brand { Id = 47, Name = "Disudrin" },
                new Brand { Id = 48, Name = "Dolan" },
                new Brand { Id = 49, Name = "Dolfenal" },
                new Brand { Id = 50, Name = "Duavent" },
                new Brand { Id = 51, Name = "E Zinc" },
                new Brand { Id = 52, Name = "Elica" },
                new Brand { Id = 53, Name = "Erceflora" },
                new Brand { Id = 54, Name = "Ercefuryl" },
                new Brand { Id = 55, Name = "Essentiale Forte" },
                new Brand { Id = 56, Name = "Expel" },
                new Brand { Id = 57, Name = "Faspic" },
                new Brand { Id = 58, Name = "Flagyl" },
                new Brand { Id = 59, Name = "Flanax" },
                new Brand { Id = 60, Name = "Fluimucil" },
                new Brand { Id = 61, Name = "Fucidin" },
                new Brand { Id = 62, Name = "Fucidin-h" },
                new Brand { Id = 63, Name = "Fucithalmic" },
                new Brand { Id = 64, Name = "Furoxone" },
                new Brand { Id = 65, Name = "Garamycin" },
                new Brand { Id = 66, Name = "Gardan" },
                new Brand { Id = 67, Name = "Heraclene" },
                new Brand { Id = 68, Name = "Himox" },
                new Brand { Id = 69, Name = "Hisdec" },
                new Brand { Id = 70, Name = "Hydrite" },
                new Brand { Id = 71, Name = "Ilosone" },
                new Brand { Id = 72, Name = "Immunosine" },
                new Brand { Id = 73, Name = "Iterax" },
                new Brand { Id = 74, Name = "Jetepar" },
                new Brand { Id = 75, Name = "Kastair" },
                new Brand { Id = 76, Name = "Katrex" },
                new Brand { Id = 77, Name = "Klarizid" },
                new Brand { Id = 78, Name = "Klaz" },
                new Brand { Id = 79, Name = "Locetar" },
                new Brand { Id = 80, Name = "Loviscol" },
                new Brand { Id = 81, Name = "Maalox" },
                new Brand { Id = 82, Name = "Medicol" },
                new Brand { Id = 83, Name = "Meptin" },
                new Brand { Id = 84, Name = "Montemax" },
                new Brand { Id = 85, Name = "Montiget" },
                new Brand { Id = 86, Name = "Motilium" },
                new Brand { Id = 87, Name = "Movelax" },
                new Brand { Id = 88, Name = "Muconase" },
                new Brand { Id = 89, Name = "Mucosolvan" },
                new Brand { Id = 90, Name = "Myonal" },
                new Brand { Id = 91, Name = "Myremol" },
                new Brand { Id = 92, Name = "Napran" },
                new Brand { Id = 93, Name = "Naprex" },
                new Brand { Id = 94, Name = "Nasatapp" },
                new Brand { Id = 95, Name = "Nasathera" },
                new Brand { Id = 96, Name = "Nasoclear" },
                new Brand { Id = 97, Name = "Natravox" },
                new Brand { Id = 98, Name = "Neozep" },
                new Brand { Id = 99, Name = "Nuelin" },
                new Brand { Id = 100, Name = "Omepron" },
                new Brand { Id = 101, Name = "Opigesic" },
                new Brand { Id = 102, Name = "Optipred" },
                new Brand { Id = 103, Name = "Orastin" },
                new Brand { Id = 104, Name = "Pediachlor" },
                new Brand { Id = 105, Name = "Pediamox" },
                new Brand { Id = 106, Name = "Pediatapp" },
                new Brand { Id = 107, Name = "Penachlor" },
                new Brand { Id = 108, Name = "Pharex" },
                new Brand { Id = 109, Name = "Physiogel" },
                new Brand { Id = 110, Name = "Polypen" },
                new Brand { Id = 111, Name = "Ponstan" },
                new Brand { Id = 112, Name = "Poro" },
                new Brand { Id = 113, Name = "Pred 10" },
                new Brand { Id = 114, Name = "Pred 20" },
                new Brand { Id = 115, Name = "Propan Tlc" },
                new Brand { Id = 116, Name = "Prostaphlin-A" },
                new Brand { Id = 117, Name = "Provexcel" },
                new Brand { Id = 118, Name = "Prox-S" },
                new Brand { Id = 119, Name = "Pulmodual" },
                new Brand { Id = 120, Name = "Pulmoxcel" },
                new Brand { Id = 121, Name = "Restime" },
                new Brand { Id = 122, Name = "Ritemed" },
                new Brand { Id = 123, Name = "Rodazid" },
                new Brand { Id = 124, Name = "Romamed" },
                new Brand { Id = 125, Name = "Rotocin" },
                new Brand { Id = 126, Name = "Salinase" },
                new Brand { Id = 127, Name = "Sangobion" },
                new Brand { Id = 128, Name = "Selzef" },
                new Brand { Id = 129, Name = "Seretide" },
                new Brand { Id = 130, Name = "Singulair" },
                new Brand { Id = 131, Name = "Skelan" },
                new Brand { Id = 132, Name = "Solmux" },
                new Brand { Id = 133, Name = "Solmux Broncho" },
                new Brand { Id = 134, Name = "Stafloxin" },
                new Brand { Id = 135, Name = "Sumapen" },
                new Brand { Id = 136, Name = "Tempra" },
                new Brand { Id = 137, Name = "Tergecet" },
                new Brand { Id = 138, Name = "Trizole" },
                new Brand { Id = 139, Name = "Ultraxime" },
                new Brand { Id = 140, Name = "Ventolin" },
                new Brand { Id = 141, Name = "Ventolin Expt" },
                new Brand { Id = 142, Name = "Virlix" },
                new Brand { Id = 143, Name = "Vometa" },
                new Brand { Id = 144, Name = "Xelent" },
                new Brand { Id = 145, Name = "Xinflex" },
                new Brand { Id = 146, Name = "Xyzal" },
                new Brand { Id = 147, Name = "Zeditapp" },
                new Brand { Id = 148, Name = "Zegen" },
                new Brand { Id = 149, Name = "Zenith" },
                new Brand { Id = 150, Name = "Zinnat" },
                new Brand { Id = 151, Name = "Zithromax" },
                new Brand { Id = 152, Name = "Zovirax" },
                new Brand { Id = 153, Name = "Zyrtec" });
        }
    }
}
