// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SaintJudeHospital.Data.Entity;

namespace SaintJudeHospital.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20181127103152_add_initialization_data_on_brands_and_medicines")]
    partial class add_initialization_data_on_brands_and_medicines
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SaintJudeHospital.Data.Entity.Bill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Balance");

                    b.Property<int>("BillStatusId");

                    b.Property<int>("CheckupId");

                    b.Property<decimal>("ConsultationFee");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<decimal>("EarPiercingFee");

                    b.Property<decimal>("FollowUpFee");

                    b.Property<decimal>("NebulizationFee");

                    b.Property<decimal>("PPDFee");

                    b.Property<int>("PatientId");

                    b.Property<string>("PayProcess");

                    b.Property<decimal>("TotalPayment");

                    b.Property<string>("VaccineInfo");

                    b.HasKey("Id");

                    b.HasIndex("BillStatusId");

                    b.HasIndex("CheckupId");

                    b.HasIndex("PatientId");

                    b.ToTable("Bills");
                });

            modelBuilder.Entity("SaintJudeHospital.Data.Entity.BillStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("BillStatuses");
                });

            modelBuilder.Entity("SaintJudeHospital.Data.Entity.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new { Id = 1, Name = "Activent" },
                        new { Id = 2, Name = "Advil" },
                        new { Id = 3, Name = "Allerkid" },
                        new { Id = 4, Name = "Alloxygen" },
                        new { Id = 5, Name = "Alnix" },
                        new { Id = 6, Name = "Alvedon" },
                        new { Id = 7, Name = "Ambrolex" },
                        new { Id = 8, Name = "Amoclav" },
                        new { Id = 9, Name = "Amoxil" },
                        new { Id = 10, Name = "Ampicin" },
                        new { Id = 11, Name = "Ansimar" },
                        new { Id = 12, Name = "Antiox" },
                        new { Id = 13, Name = "Asfrenon" },
                        new { Id = 14, Name = "Asfrenon Expt" },
                        new { Id = 15, Name = "Asmalin" },
                        new { Id = 16, Name = "Asmalin Broncho" },
                        new { Id = 17, Name = "Augmentin" },
                        new { Id = 18, Name = "Avamys" },
                        new { Id = 19, Name = "Azith" },
                        new { Id = 20, Name = "Bacidal" },
                        new { Id = 21, Name = "Bactroban" },
                        new { Id = 22, Name = "Bambec" },
                        new { Id = 23, Name = "Bioclauid" },
                        new { Id = 24, Name = "Biogesic" },
                        new { Id = 25, Name = "Bricanyl" },
                        new { Id = 26, Name = "Broncaire Expt" },
                        new { Id = 27, Name = "Bronchofen" },
                        new { Id = 28, Name = "Calmoseptine" },
                        new { Id = 29, Name = "Calpol" },
                        new { Id = 30, Name = "Ceclor" },
                        new { Id = 31, Name = "Cefalin" },
                        new { Id = 32, Name = "Ceporex" },
                        new { Id = 33, Name = "Cherifer" },
                        new { Id = 34, Name = "Chloromycetin" },
                        new { Id = 35, Name = "Clariget" },
                        new { Id = 36, Name = "Clarithro-Natrapharm Klaryz" },
                        new { Id = 37, Name = "Clarithro-natrapharm" },
                        new { Id = 38, Name = "Clarithrocid" },
                        new { Id = 39, Name = "Clotrasone" },
                        new { Id = 40, Name = "Combantrin" },
                        new { Id = 41, Name = "Combivent" },
                        new { Id = 42, Name = "Daktarin" },
                        new { Id = 43, Name = "Dalacin C" },
                        new { Id = 44, Name = "Dg" },
                        new { Id = 45, Name = "Dilatair" },
                        new { Id = 46, Name = "Dimetapp" },
                        new { Id = 47, Name = "Disudrin" },
                        new { Id = 48, Name = "Dolan" },
                        new { Id = 49, Name = "Dolfenal" },
                        new { Id = 50, Name = "Duavent" },
                        new { Id = 51, Name = "E Zinc" },
                        new { Id = 52, Name = "Elica" },
                        new { Id = 53, Name = "Erceflora" },
                        new { Id = 54, Name = "Ercefuryl" },
                        new { Id = 55, Name = "Essentiale Forte" },
                        new { Id = 56, Name = "Expel" },
                        new { Id = 57, Name = "Faspic" },
                        new { Id = 58, Name = "Flagyl" },
                        new { Id = 59, Name = "Flanax" },
                        new { Id = 60, Name = "Fluimucil" },
                        new { Id = 61, Name = "Fucidin" },
                        new { Id = 62, Name = "Fucidin-h" },
                        new { Id = 63, Name = "Fucithalmic" },
                        new { Id = 64, Name = "Furoxone" },
                        new { Id = 65, Name = "Garamycin" },
                        new { Id = 66, Name = "Gardan" },
                        new { Id = 67, Name = "Heraclene" },
                        new { Id = 68, Name = "Himox" },
                        new { Id = 69, Name = "Hisdec" },
                        new { Id = 70, Name = "Hydrite" },
                        new { Id = 71, Name = "Ilosone" },
                        new { Id = 72, Name = "Immunosine" },
                        new { Id = 73, Name = "Iterax" },
                        new { Id = 74, Name = "Jetepar" },
                        new { Id = 75, Name = "Kastair" },
                        new { Id = 76, Name = "Katrex" },
                        new { Id = 77, Name = "Klarizid" },
                        new { Id = 78, Name = "Klaz" },
                        new { Id = 79, Name = "Locetar" },
                        new { Id = 80, Name = "Loviscol" },
                        new { Id = 81, Name = "Maalox" },
                        new { Id = 82, Name = "Medicol" },
                        new { Id = 83, Name = "Meptin" },
                        new { Id = 84, Name = "Montemax" },
                        new { Id = 85, Name = "Montiget" },
                        new { Id = 86, Name = "Motilium" },
                        new { Id = 87, Name = "Movelax" },
                        new { Id = 88, Name = "Muconase" },
                        new { Id = 89, Name = "Mucosolvan" },
                        new { Id = 90, Name = "Myonal" },
                        new { Id = 91, Name = "Myremol" },
                        new { Id = 92, Name = "Napran" },
                        new { Id = 93, Name = "Naprex" },
                        new { Id = 94, Name = "Nasatapp" },
                        new { Id = 95, Name = "Nasathera" },
                        new { Id = 96, Name = "Nasoclear" },
                        new { Id = 97, Name = "Natravox" },
                        new { Id = 98, Name = "Neozep" },
                        new { Id = 99, Name = "Nuelin" },
                        new { Id = 100, Name = "Omepron" },
                        new { Id = 101, Name = "Opigesic" },
                        new { Id = 102, Name = "Optipred" },
                        new { Id = 103, Name = "Orastin" },
                        new { Id = 104, Name = "Pediachlor" },
                        new { Id = 105, Name = "Pediamox" },
                        new { Id = 106, Name = "Pediatapp" },
                        new { Id = 107, Name = "Penachlor" },
                        new { Id = 108, Name = "Pharex" },
                        new { Id = 109, Name = "Physiogel" },
                        new { Id = 110, Name = "Polypen" },
                        new { Id = 111, Name = "Ponstan" },
                        new { Id = 112, Name = "Poro" },
                        new { Id = 113, Name = "Pred 10" },
                        new { Id = 114, Name = "Pred 20" },
                        new { Id = 115, Name = "Propan Tlc" },
                        new { Id = 116, Name = "Prostaphlin-A" },
                        new { Id = 117, Name = "Provexcel" },
                        new { Id = 118, Name = "Prox-S" },
                        new { Id = 119, Name = "Pulmodual" },
                        new { Id = 120, Name = "Pulmoxcel" },
                        new { Id = 121, Name = "Restime" },
                        new { Id = 122, Name = "Ritemed" },
                        new { Id = 123, Name = "Rodazid" },
                        new { Id = 124, Name = "Romamed" },
                        new { Id = 125, Name = "Rotocin" },
                        new { Id = 126, Name = "Salinase" },
                        new { Id = 127, Name = "Sangobion" },
                        new { Id = 128, Name = "Selzef" },
                        new { Id = 129, Name = "Seretide" },
                        new { Id = 130, Name = "Singulair" },
                        new { Id = 131, Name = "Skelan" },
                        new { Id = 132, Name = "Solmux" },
                        new { Id = 133, Name = "Solmux Broncho" },
                        new { Id = 134, Name = "Stafloxin" },
                        new { Id = 135, Name = "Sumapen" },
                        new { Id = 136, Name = "Tempra" },
                        new { Id = 137, Name = "Tergecet" },
                        new { Id = 138, Name = "Trizole" },
                        new { Id = 139, Name = "Ultraxime" },
                        new { Id = 140, Name = "Ventolin" },
                        new { Id = 141, Name = "Ventolin Expt" },
                        new { Id = 142, Name = "Virlix" },
                        new { Id = 143, Name = "Vometa" },
                        new { Id = 144, Name = "Xelent" },
                        new { Id = 145, Name = "Xinflex" },
                        new { Id = 146, Name = "Xyzal" },
                        new { Id = 147, Name = "Zeditapp" },
                        new { Id = 148, Name = "Zegen" },
                        new { Id = 149, Name = "Zenith" },
                        new { Id = 150, Name = "Zinnat" },
                        new { Id = 151, Name = "Zithromax" },
                        new { Id = 152, Name = "Zovirax" },
                        new { Id = 153, Name = "Zyrtec" }
                    );
                });

            modelBuilder.Entity("SaintJudeHospital.Data.Entity.Checkup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<string>("Assessment");

                    b.Property<string>("CivilStatus");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<string>("Diagnosis");

                    b.Property<string>("Gender");

                    b.Property<string>("HeadCircum");

                    b.Property<string>("Height");

                    b.Property<string>("Name");

                    b.Property<DateTime>("NextVisitDate");

                    b.Property<string>("Objective");

                    b.Property<string>("Prescription");

                    b.Property<string>("Subjective");

                    b.Property<string>("Temperature");

                    b.Property<string>("Weight");

                    b.HasKey("Id");

                    b.ToTable("Checkups");
                });

            modelBuilder.Entity("SaintJudeHospital.Data.Entity.Immunize", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Immunizes");

                    b.HasData(
                        new { Id = 1, Amount = 3000m, Name = "HEXA" },
                        new { Id = 2, Amount = 3200m, Name = "PCV 10" },
                        new { Id = 3, Amount = 750m, Name = "MEASLES" },
                        new { Id = 4, Amount = 1300m, Name = "HIB" },
                        new { Id = 5, Amount = 4000m, Name = "MENINGO" },
                        new { Id = 6, Amount = 1300m, Name = "TYPHOID" },
                        new { Id = 7, Amount = 1800m, Name = "HEP A" },
                        new { Id = 8, Amount = 700m, Name = "HEP B" },
                        new { Id = 9, Amount = 1600m, Name = "TETRAXIM" },
                        new { Id = 10, Amount = 1200m, Name = "MMR" },
                        new { Id = 11, Amount = 2200m, Name = "CHICKEN POX" },
                        new { Id = 12, Amount = 2500m, Name = "PENTA" },
                        new { Id = 13, Amount = 900m, Name = "BCG-1" },
                        new { Id = 14, Amount = 3000m, Name = "MMR-V" },
                        new { Id = 15, Amount = 1700m, Name = "PNEUMO-23" },
                        new { Id = 16, Amount = 1700m, Name = "RABIES" },
                        new { Id = 17, Amount = 3000m, Name = "ROTARIX" },
                        new { Id = 18, Amount = 2200m, Name = "ROTATEQ" },
                        new { Id = 19, Amount = 1000m, Name = "FLU" },
                        new { Id = 20, Amount = 4000m, Name = "PCV" },
                        new { Id = 21, Amount = 0m, Name = "BCG-2" }
                    );
                });

            modelBuilder.Entity("SaintJudeHospital.Data.Entity.InPatient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount");

                    b.Property<DateTime>("CreateDate");

                    b.Property<string>("Name");

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.ToTable("InPatients");
                });

            modelBuilder.Entity("SaintJudeHospital.Data.Entity.Laboratory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Laboratories");
                });

            modelBuilder.Entity("SaintJudeHospital.Data.Entity.MedicalCertificate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<string>("Diagnosis");

                    b.Property<string>("Operation");

                    b.Property<int>("PatientId");

                    b.Property<string>("Remarks");

                    b.Property<string>("Requestor");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("MedicalCertificates");
                });

            modelBuilder.Entity("SaintJudeHospital.Data.Entity.Medicine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BrandId");

                    b.Property<string>("Description");

                    b.Property<string>("GenericName");

                    b.Property<string>("Inscription");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("Medicines");

                    b.HasData(
                        new { Id = 1, Description = "10mg", GenericName = "Cetirizine", Inscription = "Tab" },
                        new { Id = 2, Description = "500mg", GenericName = "Amoxicillin", Inscription = "Cap" },
                        new { Id = 3, Description = "250mg", GenericName = "Amoxicillin", Inscription = "Cap" },
                        new { Id = 4, Description = "375mg", GenericName = "Co Amoxiclav", Inscription = "Tab" },
                        new { Id = 5, Description = "30mg", GenericName = "Prednisolone", Inscription = "Tab" },
                        new { Id = 6, Description = "20mg", GenericName = "Prednisolone", Inscription = "Tab" },
                        new { Id = 7, Description = "5mg", GenericName = "Prednisolone", Inscription = "Tab" },
                        new { Id = 8, Description = "80mg/5ml", GenericName = "Gentamicin IV", Inscription = "Amp" },
                        new { Id = 9, Description = "40mg/5ml", GenericName = "Gentamicin IV", Inscription = "Amp" },
                        new { Id = 10, GenericName = "Broncho Vaxom", Inscription = "Pedia Cap" },
                        new { Id = 11, GenericName = "Glycerin", Inscription = "Pediatric suppository" },
                        new { Id = 12, GenericName = "Glycerin", Inscription = "Pediatric suppository" },
                        new { Id = 13, BrandId = 1, Description = "2mg", GenericName = "Salbutamol", Inscription = "Tab" },
                        new { Id = 14, BrandId = 1, Description = "2mg/5ml", GenericName = "Salbutamol", Inscription = "Syrup" },
                        new { Id = 15, BrandId = 2, Description = "100mg/5ml", GenericName = "Ibuprofen", Inscription = "Susp" },
                        new { Id = 16, BrandId = 2, Description = "200mg/5ml", GenericName = "Ibuprofen", Inscription = "Susp" },
                        new { Id = 17, BrandId = 2, Description = "200mg", GenericName = "Ibuprofen", Inscription = "Cap" },
                        new { Id = 18, BrandId = 2, Description = "100mg/2.5ml", GenericName = "Ibuprofen", Inscription = "Drops" },
                        new { Id = 19, BrandId = 3, Description = "5mg/5ml", GenericName = "Cetirizine", Inscription = "Syrup" },
                        new { Id = 20, BrandId = 3, Description = "2.5mg/ml", GenericName = "Cetirizine", Inscription = "Drops" },
                        new { Id = 21, Description = "1.5mg/5ml", GenericName = "Terbutaline", Inscription = "Syrup" },
                        new { Id = 22, BrandId = 4, Description = "10mg", GenericName = "Cetirizine", Inscription = "Tab" },
                        new { Id = 23, BrandId = 4, Description = "5mg/5ml", GenericName = "Cetirizine", Inscription = "Syrup" },
                        new { Id = 24, BrandId = 5, Description = "2.5mg/ml", GenericName = "Cetirizine", Inscription = "Drops" },
                        new { Id = 25, BrandId = 5, Description = "250mg", GenericName = "Paracetamol", Inscription = "Tab" },
                        new { Id = 26, BrandId = 5, Description = "325mg", GenericName = "Paracetamol", Inscription = "Tab" },
                        new { Id = 27, BrandId = 5, Description = "500mg", GenericName = "Paracetamol", Inscription = "Tab" },
                        new { Id = 28, BrandId = 6, Description = "120mg/5ml", GenericName = "Paracetamol", Inscription = "Syrup" },
                        new { Id = 29, BrandId = 6, Description = "100ml", GenericName = "Paracetamol", Inscription = "Drops" },
                        new { Id = 30, BrandId = 7, Description = "30mg", GenericName = "Ambroxol", Inscription = "Tab" },
                        new { Id = 31, BrandId = 7, Description = "30mg/3ml", GenericName = "Ambroxol", Inscription = "Syrup" },
                        new { Id = 32, BrandId = 7, Description = "15mg/5ml", GenericName = "Ambroxol", Inscription = "Syrup" },
                        new { Id = 33, BrandId = 7, Description = "7.5mg/ml", GenericName = "Ambroxol", Inscription = "Drops" },
                        new { Id = 34, BrandId = 8, Description = "457mg/5ml", GenericName = "Co Amoxiclav", Inscription = "Susp" },
                        new { Id = 35, BrandId = 8, Description = "228mg/5ml", GenericName = "Co Amoxiclav", Inscription = "Susp" },
                        new { Id = 36, BrandId = 8, Description = "156mg/5ml", GenericName = "Co Amoxiclav", Inscription = "Susp" },
                        new { Id = 37, BrandId = 8, Description = "312mg/5ml", GenericName = "Co Amoxiclav", Inscription = "Susp" },
                        new { Id = 38, BrandId = 9, Description = "250mg/5ml", GenericName = "Amoxicillin", Inscription = "Susp" },
                        new { Id = 39, BrandId = 9, Description = "100mg/ml", GenericName = "Amoxicillin", Inscription = "Drops" },
                        new { Id = 40, BrandId = 9, Description = "125mg/ml", GenericName = "Amoxicillin", Inscription = "Susp" },
                        new { Id = 41, BrandId = 10, Description = "1mg", GenericName = "Ampicillin IV" },
                        new { Id = 42, BrandId = 10, Description = "500mg", GenericName = "Ampicillin IV" },
                        new { Id = 43, BrandId = 10, Description = "750mg", GenericName = "Ampicillin IV" },
                        new { Id = 44, BrandId = 10, Description = "250mg", GenericName = "Ampicillin IV" },
                        new { Id = 45, BrandId = 11, Description = "100mg", GenericName = "Doxofylline", Inscription = "Tab" },
                        new { Id = 46, BrandId = 11, Description = "100mg/5ml", GenericName = "Doxofylline", Inscription = "Syrup" },
                        new { Id = 47, BrandId = 12, Description = "100mg", GenericName = "Mebendazole", Inscription = "Tab" },
                        new { Id = 48, BrandId = 12, Description = "20mg/ml", GenericName = "Mebendazole", Inscription = "Susp" },
                        new { Id = 49, BrandId = 12, Description = "500mg", GenericName = "Mebendazole", Inscription = "Tab" },
                        new { Id = 50, BrandId = 12, Description = "50mg/ml", GenericName = "Mebendazole", Inscription = "Susp" },
                        new { Id = 51, BrandId = 13, Description = "2mg/5ml", GenericName = "Salbutamol", Inscription = "Syrup" },
                        new { Id = 52, BrandId = 14, GenericName = "Salbutamol + Guaifenesin", Inscription = "Syrup" },
                        new { Id = 53, BrandId = 15, Description = "100mgm/Inhalation", GenericName = "Salbutamol", Inscription = "MDI" },
                        new { Id = 54, BrandId = 15, Description = "2.5mg/2.5ml", GenericName = "Salbutamol", Inscription = "Nebule" },
                        new { Id = 55, BrandId = 15, Description = "2mg", GenericName = "Salbutamol", Inscription = "Tab" },
                        new { Id = 56, BrandId = 15, Description = "2mg/5ml", GenericName = "Salbutamol", Inscription = "Syrup" },
                        new { Id = 57, BrandId = 16, GenericName = "Salbutamol + Guaifenesin", Inscription = "Syrup" },
                        new { Id = 58, BrandId = 17, Description = "625mg", GenericName = "Coamoxiclav", Inscription = "Tab" },
                        new { Id = 59, BrandId = 17, Description = "156mg/5ml", GenericName = "Coamoxiclav", Inscription = "Susp" },
                        new { Id = 60, BrandId = 17, Description = "457mg/5ml", GenericName = "Coamoxiclav", Inscription = "Susp" },
                        new { Id = 61, BrandId = 17, Description = "228mg/5ml", GenericName = "Coamoxiclav", Inscription = "Susp" },
                        new { Id = 62, BrandId = 17, Description = "312mg/5ml", GenericName = "Coamoxiclav", Inscription = "Susp" },
                        new { Id = 63, BrandId = 18, Description = "27.5mgm/spray", GenericName = "Fluticasone Furoate", Inscription = "Nasal Spray" },
                        new { Id = 64, BrandId = 19, Description = "500mg", GenericName = "Azithromycin", Inscription = "Tab" },
                        new { Id = 65, BrandId = 19, Description = "250mg", GenericName = "Azithromycin", Inscription = "Tab" },
                        new { Id = 66, BrandId = 19, Description = "200mg/5ml", GenericName = "Azithromycin", Inscription = "Susp" },
                        new { Id = 67, BrandId = 20, Description = "4oomg/80mg", GenericName = "Cotrimoxazole", Inscription = "Tab" },
                        new { Id = 68, BrandId = 21, Description = "Cream", GenericName = "Mupirocin", Inscription = "Tube" },
                        new { Id = 69, BrandId = 22, Description = "1mg/1ml", GenericName = "Bambuterol", Inscription = "Syrup" },
                        new { Id = 70, BrandId = 22, Description = "10mg", GenericName = "Bambuterol", Inscription = "Tab" },
                        new { Id = 71, BrandId = 23, Description = "125mg/5ml", GenericName = "Co Amoxiclav", Inscription = "Susp" },
                        new { Id = 72, BrandId = 23, Description = "250mg/5ml", GenericName = "Co Amoxiclav", Inscription = "Susp" },
                        new { Id = 73, BrandId = 24, Description = "120mg/5ml", GenericName = "Paracetamol", Inscription = "Susp" },
                        new { Id = 74, BrandId = 24, Description = "500mg", GenericName = "Paracetamol", Inscription = "Tab" },
                        new { Id = 75, BrandId = 24, Description = "250mg/5ml", GenericName = "Paracetamol", Inscription = "Syrup" },
                        new { Id = 76, BrandId = 24, Description = "250mg", GenericName = "Paracetamol", Inscription = "Tab" },
                        new { Id = 77, BrandId = 24, Description = "325mg", GenericName = "Paracetamol", Inscription = "Tab" },
                        new { Id = 78, BrandId = 24, Description = "100mg/ml", GenericName = "Paracetamol", Inscription = "Drops" },
                        new { Id = 79, BrandId = 25, Description = "1.5mg/5ml", GenericName = "Terbutaline", Inscription = "Syrup" },
                        new { Id = 80, BrandId = 26, GenericName = "Salbutamol + Guaifenesin", Inscription = "Syrup" },
                        new { Id = 81, BrandId = 27, Description = "5mg///1mg/5ml", GenericName = "Phenylephrine Hcl + Chlorpheniramine Maleate", Inscription = "Syrup" },
                        new { Id = 82, BrandId = 27, GenericName = "Phenylephrine Hcl + Chlorpheniramine Maleate", Inscription = "Syrup" },
                        new { Id = 83, BrandId = 27, GenericName = "Phenylephrine Hcl + Chlorpheniramine Maleate", Inscription = "drops" },
                        new { Id = 84, BrandId = 28, Description = "Sachet", GenericName = "Calmoseptine", Inscription = "Ointment" },
                        new { Id = 85, BrandId = 29, Description = "250mg/5ml", GenericName = "Paracetamol", Inscription = "Susp" },
                        new { Id = 86, BrandId = 29, Description = "250mg", GenericName = "Paracetamol", Inscription = "Tab" },
                        new { Id = 87, BrandId = 29, Description = "500mg", GenericName = "Paracetamol", Inscription = "Tab" },
                        new { Id = 88, BrandId = 29, Description = "325mg", GenericName = "Paracetamol", Inscription = "Tab" },
                        new { Id = 89, BrandId = 29, Description = "120mg/5ml", GenericName = "Paracetamol", Inscription = "Syrup" },
                        new { Id = 90, BrandId = 29, Description = "100mg/ml", GenericName = "Paracetamol", Inscription = "Drops" },
                        new { Id = 91, BrandId = 30, Description = "250mg/5ml", GenericName = "Cefaclor", Inscription = "Susp" },
                        new { Id = 92, BrandId = 30, Description = "125mg/5ml", GenericName = "Cefaclor", Inscription = "Susp" },
                        new { Id = 93, BrandId = 30, Description = "50mg/ml", GenericName = "Cefaclor + Guaifenesin", Inscription = "Drops" },
                        new { Id = 94, BrandId = 31, Description = "500mg", GenericName = "Cefalexin", Inscription = "Cap" },
                        new { Id = 95, BrandId = 31, Description = "250mg/5ml", GenericName = "Cefalexin", Inscription = "Susp" },
                        new { Id = 96, BrandId = 31, Description = "125mg/5ml", GenericName = "Cefalexin", Inscription = "Susp" },
                        new { Id = 97, BrandId = 31, Description = "100mg/ml", GenericName = "Cefalexin", Inscription = "Drops" },
                        new { Id = 98, BrandId = 32, Description = "250mg/5ml", GenericName = "Cefalexin", Inscription = "Susp" },
                        new { Id = 99, BrandId = 32, Description = "125mg/5ml", GenericName = "Cefalexin", Inscription = "Susp" },
                        new { Id = 100, BrandId = 32, Description = "100mg/ml", GenericName = "Cefalexin", Inscription = "Drops" },
                        new { Id = 101, BrandId = 33, GenericName = "Multivitamins", Inscription = "Drops" },
                        new { Id = 102, BrandId = 34, Description = "500mg", GenericName = "Chloramphenicol", Inscription = "Cap" },
                        new { Id = 103, BrandId = 34, Description = "125mg/5ml", GenericName = "Chloramphenicol", Inscription = "Susp" },
                        new { Id = 104, BrandId = 34, Description = "250mg", GenericName = "Chloramphenicol", Inscription = "Cap" },
                        new { Id = 105, BrandId = 35, Description = "125mg/5ml", GenericName = "Clarithromycin", Inscription = "Susp" },
                        new { Id = 106, BrandId = 36, Description = "125mg/5ml", GenericName = "Clarithromycin", Inscription = "Tab" },
                        new { Id = 107, BrandId = 36, Description = "500mg", GenericName = "Clarithromycin", Inscription = "Tab" },
                        new { Id = 108, BrandId = 36, Description = "250mg/5ml", GenericName = "Clarithromycin", Inscription = "Susp" },
                        new { Id = 109, BrandId = 37, Description = "125mg/5ml", GenericName = "Clarithromycin", Inscription = "Susp" },
                        new { Id = 110, BrandId = 38, Description = "250mg", GenericName = "Clarithromycin", Inscription = "Tab" },
                        new { Id = 111, BrandId = 38, Description = "500mg", GenericName = "Clarithromycin", Inscription = "Tab" },
                        new { Id = 112, BrandId = 38, Description = "250mg/5ml", GenericName = "Clarithromycin", Inscription = "Susp" },
                        new { Id = 113, BrandId = 38, Description = "125mg/5ml", GenericName = "Clarithromycin", Inscription = "Susp" },
                        new { Id = 114, BrandId = 39, Description = "Tube", GenericName = "Clotrimazole + Betamethasone", Inscription = "Cream" },
                        new { Id = 115, BrandId = 40, Description = "125mg", GenericName = "Pyrantel Pamoate", Inscription = "Tab" },
                        new { Id = 116, BrandId = 40, Description = "125mg/5ml", GenericName = "Pyrantel Pamoate", Inscription = "Susp" },
                        new { Id = 117, BrandId = 41, GenericName = "Salbutamol + Ipratropium Bromide", Inscription = "Nebule" },
                        new { Id = 118, BrandId = 42, Description = "Tube", GenericName = "Miconazole", Inscription = "Oral Gel" },
                        new { Id = 119, BrandId = 43, Description = "75mg/5ml", GenericName = "Clindamycin", Inscription = "Susp" },
                        new { Id = 120, BrandId = 44, Description = "400mg", GenericName = "Dg Milk", Inscription = "Can" },
                        new { Id = 121, BrandId = 45, Description = "100mg/5ml", GenericName = "Doxofylline", Inscription = "Syrup" },
                        new { Id = 122, BrandId = 45, Description = "100mg", GenericName = "Doxofylline", Inscription = "Tab" },
                        new { Id = 123, BrandId = 46, GenericName = "Brompheniramine Maleate + Phenylephrine", Inscription = "Drops" },
                        new { Id = 124, BrandId = 46, GenericName = "Brompheniramine Maleate + Phenylephrine", Inscription = "Syrup" },
                        new { Id = 125, BrandId = 47, GenericName = "Phenylpropanolamine", Inscription = "Syrup" },
                        new { Id = 126, BrandId = 47, GenericName = "Phenylpropanolamine", Inscription = "Drops" },
                        new { Id = 127, BrandId = 48, Description = "200mg/5ml", GenericName = "Ibuprofen", Inscription = "Susp" },
                        new { Id = 128, BrandId = 48, Description = "100mg/5ml", GenericName = "Ibuprofen", Inscription = "susp" },
                        new { Id = 129, BrandId = 48, Description = "100mg/2.5ml", GenericName = "Ibuprofen", Inscription = "Drops" },
                        new { Id = 130, BrandId = 49, Description = "250mg", GenericName = "Mefenamic Acid", Inscription = "Cap" },
                        new { Id = 131, BrandId = 49, Description = "500mg", GenericName = "Mefenamic Acid", Inscription = "Cap" },
                        new { Id = 132, BrandId = 50, GenericName = "Salbutamol + Ipratropium Bromide", Inscription = "Nebule" },
                        new { Id = 133, BrandId = 51, GenericName = "Zinc Sulfate", Inscription = "Syrup" },
                        new { Id = 134, BrandId = 51, GenericName = "Zinc Sulfate", Inscription = "Drops" },
                        new { Id = 135, BrandId = 52, GenericName = "Mometasone Furoate", Inscription = "Lotion" },
                        new { Id = 136, BrandId = 52, GenericName = "Mometasone Furoate", Inscription = "Cream" },
                        new { Id = 137, BrandId = 53, GenericName = "Bacillus Clausii", Inscription = "Oral Solution" },
                        new { Id = 138, BrandId = 54, Description = "218mg/5ml", GenericName = "Nifuroxazide", Inscription = "Susp" },
                        new { Id = 139, BrandId = 54, Description = "200mg", GenericName = "Nifuroxazide", Inscription = "Cap" },
                        new { Id = 140, BrandId = 55, Description = "300mg", GenericName = "Phospholipids", Inscription = "Cap" },
                        new { Id = 141, BrandId = 56, Description = "300mg", GenericName = "Ambroxol", Inscription = "Tab" },
                        new { Id = 142, BrandId = 56, Description = "30mg/5ml", GenericName = "Ambroxol", Inscription = "Syrup" },
                        new { Id = 143, BrandId = 56, Description = "7.5mg/5ml", GenericName = "Ambroxol", Inscription = "Drops" },
                        new { Id = 144, BrandId = 56, Description = "15mg/2.5ml", GenericName = "Ambroxol", Inscription = "Syrup" },
                        new { Id = 145, BrandId = 57, Description = "400mg", GenericName = "Ibuprofen", Inscription = "Cap" },
                        new { Id = 146, BrandId = 57, Description = "200mg", GenericName = "Ibuprofen", Inscription = "Cap" },
                        new { Id = 147, BrandId = 58, Description = "500mg", GenericName = "Metronidazole", Inscription = "Tab" },
                        new { Id = 148, BrandId = 58, Description = "25mg/1ml", GenericName = "Metronidazole", Inscription = "Syrup" },
                        new { Id = 149, BrandId = 58, GenericName = "Metronidazole" },
                        new { Id = 150, BrandId = 59, Description = "550mg", GenericName = "Naproxen Sodium", Inscription = "Tab" },
                        new { Id = 151, BrandId = 59, Description = "275mg", GenericName = "Naproxen Sodium", Inscription = "Tab" },
                        new { Id = 152, BrandId = 60, Description = "1000mg", GenericName = "Acetylcysteine", Inscription = "Sachet" },
                        new { Id = 153, BrandId = 60, Description = "100mg/5ml", GenericName = "Acetylcysteine", Inscription = "Syrup" },
                        new { Id = 154, BrandId = 60, Description = "200mg", GenericName = "Acetylcysteine", Inscription = "Sachet" },
                        new { Id = 155, BrandId = 61, Description = "Tube", GenericName = "Fusidate Sodium", Inscription = "Ointment" },
                        new { Id = 156, BrandId = 62, Description = "Tube", GenericName = "Fucidic Acid + Hydrocortisone", Inscription = "Ointment" },
                        new { Id = 157, BrandId = 63, Description = "Tube", GenericName = "Fucidic Acid", Inscription = "Eyedrops" },
                        new { Id = 158, BrandId = 64, Description = "100mg", GenericName = "Furazolidone", Inscription = "Tab" },
                        new { Id = 159, BrandId = 64, Description = "16.7mg/5ml", GenericName = "Furazolidone", Inscription = "Susp" },
                        new { Id = 160, BrandId = 65, GenericName = "Gentamycin", Inscription = "Eyedrops" },
                        new { Id = 161, BrandId = 66, Description = "500mg", GenericName = "Mefenamic Acid", Inscription = "Cap" },
                        new { Id = 162, BrandId = 66, Description = "250mg", GenericName = "Mefenamic Acid", Inscription = "Cap" },
                        new { Id = 163, BrandId = 67, Description = "1mg/1ml", GenericName = "Dibencozide", Inscription = "Cap" },
                        new { Id = 164, BrandId = 68, Description = "500mg", GenericName = "Amoxicillin", Inscription = "Cap" },
                        new { Id = 165, BrandId = 68, Description = "250mg/5ml", GenericName = "Amoxicillin", Inscription = "Susp" },
                        new { Id = 166, BrandId = 68, Description = "125mg/5ml", GenericName = "Amoxicillin", Inscription = "Susp" },
                        new { Id = 167, BrandId = 68, Description = "100mg/ml", GenericName = "Amoxicillin", Inscription = "Drops" },
                        new { Id = 168, BrandId = 69, GenericName = "Brompheniramine Maleate + Phenylpropanolamine", Inscription = "Syrup" },
                        new { Id = 169, BrandId = 69, GenericName = "Brompheniramine Maleate + Phenylpropanolamine", Inscription = "Drops" },
                        new { Id = 170, BrandId = 70, GenericName = "Oral Rehydration Solution", Inscription = "Sachet" },
                        new { Id = 171, BrandId = 71, Description = "250mg/5ml", GenericName = "Erythromycin", Inscription = "Susp" },
                        new { Id = 172, BrandId = 71, Description = "100mg/ml", GenericName = "Erythromycin", Inscription = "Drops" },
                        new { Id = 173, BrandId = 72, Description = "Bot", GenericName = "Inosiplex", Inscription = "Syrup" },
                        new { Id = 174, BrandId = 73, Description = "25mg", GenericName = "Hydroxyzine diHCI", Inscription = "Tab" },
                        new { Id = 175, BrandId = 73, Description = "2mg/ml", GenericName = "Hydroxyzine diHCI", Inscription = "Syrup" },
                        new { Id = 176, BrandId = 73, Description = "10mg", GenericName = "Hydroxyzine diHCI", Inscription = "Tab" },
                        new { Id = 177, BrandId = 74, GenericName = "Betaine Glucuronate Plus", Inscription = "Syrup" },
                        new { Id = 178, BrandId = 74, GenericName = "Betaine Glucuronate Plus", Inscription = "Cap" },
                        new { Id = 179, BrandId = 75, Description = "4mg", GenericName = "Montelukast", Inscription = "Tab" },
                        new { Id = 180, BrandId = 75, Description = "10mg", GenericName = "Montelukast", Inscription = "Tab" },
                        new { Id = 181, BrandId = 75, Description = "5mg", GenericName = "Montelukast", Inscription = "Tab" },
                        new { Id = 182, BrandId = 76, Description = "200mg/40mg/5ml", GenericName = "Cotrimoxazole", Inscription = "Bot" },
                        new { Id = 183, BrandId = 77, Description = "500mg", GenericName = "Clarithromycin", Inscription = "Tab" },
                        new { Id = 184, BrandId = 77, Description = "125mg/5ml", GenericName = "Clarithromycin", Inscription = "Susp" },
                        new { Id = 185, BrandId = 77, Description = "250mg", GenericName = "Clarithromycin", Inscription = "Tab" },
                        new { Id = 186, BrandId = 77, Description = "250mg/5ml", GenericName = "Clarithromycin", Inscription = "Susp" },
                        new { Id = 187, BrandId = 78, Description = "500mg", GenericName = "Clarithromycin", Inscription = "Tab" },
                        new { Id = 188, BrandId = 78, Description = "250mg/5ml", GenericName = "Clarithromycin", Inscription = "Susp" },
                        new { Id = 189, BrandId = 78, Description = "125mg/5ml", GenericName = "Clarithromycin", Inscription = "Susp" },
                        new { Id = 190, BrandId = 78, Description = "250mg", GenericName = "Clarithromycin", Inscription = "Tab" },
                        new { Id = 191, BrandId = 79, GenericName = "Amorolfine", Inscription = "Nail Lacquer" },
                        new { Id = 192, BrandId = 80, Description = "100mg/5ml", GenericName = "Carbocisteine", Inscription = "Syrup" },
                        new { Id = 193, BrandId = 80, Description = "50mg/ml", GenericName = "Carbocisteine", Inscription = "Drops" },
                        new { Id = 194, BrandId = 81, GenericName = "Aluminum Magnesium Hydroxide", Inscription = "Tab" },
                        new { Id = 195, BrandId = 81, GenericName = "Aluminum Magnesium Hydroxide", Inscription = "Susp" },
                        new { Id = 196, BrandId = 82, Description = "200mg", GenericName = "Ibuprofen", Inscription = "Cap" },
                        new { Id = 197, BrandId = 83, Description = "25mgm", GenericName = "Procaterol", Inscription = "Tab" },
                        new { Id = 198, BrandId = 83, Description = "50mgm", GenericName = "Procaterol", Inscription = "Tab" },
                        new { Id = 199, BrandId = 83, Description = "5mgm/ml", GenericName = "Procaterol", Inscription = "Syrup" },
                        new { Id = 200, BrandId = 84, Description = "5mg", GenericName = "Montelukast", Inscription = "Tab" },
                        new { Id = 201, BrandId = 84, Description = "10mg", GenericName = "Montelukast", Inscription = "Tab" },
                        new { Id = 202, BrandId = 84, Description = "4mg", GenericName = "Montelukast", Inscription = "Tab" },
                        new { Id = 203, BrandId = 85, Description = "5mg", GenericName = "Montelukast", Inscription = "Tab" },
                        new { Id = 204, BrandId = 85, Description = "10mg", GenericName = "Montelukast", Inscription = "Tab" },
                        new { Id = 205, BrandId = 85, Description = "4mg", GenericName = "Montelukast", Inscription = "Tab" },
                        new { Id = 206, BrandId = 85, Description = "4mg", GenericName = "Montelukast", Inscription = "Granules" },
                        new { Id = 207, BrandId = 86, Description = "10mg", GenericName = "Domperidone", Inscription = "Tab" },
                        new { Id = 208, BrandId = 87, Description = "3.3g/5ml", GenericName = "Lactulose", Inscription = "Syrup" },
                        new { Id = 209, BrandId = 88, GenericName = "Sodium Chloride", Inscription = "Nasal drops" },
                        new { Id = 210, BrandId = 88, GenericName = "Sodium Chloride", Inscription = "Nasal spray" },
                        new { Id = 211, BrandId = 89, Description = "7.5mg/ml", GenericName = "Ambroxol", Inscription = "Drops" },
                        new { Id = 212, BrandId = 90, Description = "50mg", GenericName = "Eperisone HCI", Inscription = "Tab" },
                        new { Id = 213, BrandId = 91, Description = "120mg/5ml", GenericName = "Paracetamol", Inscription = "Syrup" },
                        new { Id = 214, BrandId = 91, Description = "250mg/5ml", GenericName = "Paracetamol", Inscription = "Syrup" },
                        new { Id = 215, BrandId = 91, Description = "100ml", GenericName = "Paracetamol", Inscription = "Drops" },
                        new { Id = 216, BrandId = 92, Description = "100ml", GenericName = "Paracetamol", Inscription = "Drops" },
                        new { Id = 217, BrandId = 92, Description = "250mg/5ml", GenericName = "Paracetamol", Inscription = "Syrup" },
                        new { Id = 218, BrandId = 93, Description = "250mg/5ml", GenericName = "Paracetamol", Inscription = "Syrup" },
                        new { Id = 219, BrandId = 93, Description = "100mg/ml", GenericName = "Paracetamol", Inscription = "Drops" },
                        new { Id = 220, BrandId = 94, GenericName = "Brompheniramine Maleate + Phenylpropanolamine", Inscription = "Syrup" },
                        new { Id = 221, BrandId = 94, GenericName = "Brompheniramine Maleate + Phenylpropanolamine", Inscription = "Drops" },
                        new { Id = 222, BrandId = 95, Description = "250mg/12.5mg", GenericName = "Paracetamol + Phenylpropanolamine", Inscription = "Syrup" },
                        new { Id = 223, BrandId = 95, Description = "325mg/25mg", GenericName = "Paracetamol + Phenylpropanolamine", Inscription = "Cap" },
                        new { Id = 224, BrandId = 96, GenericName = "Sodium Chloride", Inscription = "Nasal spray" },
                        new { Id = 225, BrandId = 96, GenericName = "Sodium Chloride", Inscription = "Nasal drops" },
                        new { Id = 226, BrandId = 97, Description = "125mg/5ml", GenericName = "Co Amoxiclav", Inscription = "Susp" },
                        new { Id = 227, BrandId = 97, Description = "250mg/5ml", GenericName = "Co Amoxiclav", Inscription = "Susp" },
                        new { Id = 228, BrandId = 98, GenericName = "Phenylephrine Hcl + Chlorpheniramine Maleate", Inscription = "Syrup" },
                        new { Id = 229, BrandId = 98, GenericName = "Phenylephrine Hcl + Chlorpheniramine Maleate", Inscription = "Drops" },
                        new { Id = 230, BrandId = 99, Description = "26.7mg/5ml", GenericName = "Theophylline", Inscription = "Syrup" },
                        new { Id = 231, BrandId = 100, Description = "20 Mg", GenericName = "Omeprazole", Inscription = "Cap" },
                        new { Id = 232, BrandId = 101, Description = "125mg", GenericName = "Paracetamol", Inscription = "Suppository" },
                        new { Id = 233, BrandId = 101, Description = "250mg/5ml", GenericName = "Paracetamol", Inscription = "Suppository" },
                        new { Id = 234, BrandId = 102, Description = "20mg/5ml", GenericName = "Prednisolone", Inscription = "Syrup" },
                        new { Id = 235, BrandId = 103, Description = "100,000 Iu", GenericName = "Nystatin", Inscription = "Susp" },
                        new { Id = 236, BrandId = 104, Description = "125mg/5ml", GenericName = "Chloramphenicol", Inscription = "Susp" },
                        new { Id = 237, BrandId = 104, Description = "250mg/5ml", GenericName = "Chloramphenicol", Inscription = "Cap" },
                        new { Id = 238, BrandId = 104, Description = "500mg", GenericName = "Chloramphenicol", Inscription = "Cap" },
                        new { Id = 239, BrandId = 105, Description = "250mg/5ml", GenericName = "Amoxicillin", Inscription = "Susp" },
                        new { Id = 240, BrandId = 105, Description = "125mg/5ml", GenericName = "Amoxicillin", Inscription = "Susp" },
                        new { Id = 241, BrandId = 105, Description = "100mg/ml", GenericName = "Amoxicillin", Inscription = "Drops" },
                        new { Id = 242, BrandId = 106, GenericName = "Brompheniramine Maleate + Phenylpropanolamine", Inscription = "Syrup" },
                        new { Id = 243, BrandId = 106, GenericName = "Brompheniramine Maleate + Phenylpropanolamine", Inscription = "Drops" },
                        new { Id = 244, BrandId = 107, Description = "125mg/5ml", GenericName = "Chloramphenicol", Inscription = "Syrup" },
                        new { Id = 245, BrandId = 107, Description = "250mg", GenericName = "Chloramphenicol", Inscription = "Cap" },
                        new { Id = 246, BrandId = 107, Description = "500mg", GenericName = "Chloramphenicol", Inscription = "Cap" },
                        new { Id = 247, BrandId = 108, Description = "250mg/5ml", GenericName = "Cloxacillin", Inscription = "Susp" },
                        new { Id = 248, BrandId = 108, Description = "250mg/5ml", GenericName = "Cloxacillin", Inscription = "Susp" },
                        new { Id = 249, BrandId = 108, Description = "125mg/5ml", GenericName = "Cloxacillin", Inscription = "Susp" },
                        new { Id = 250, BrandId = 109, GenericName = "Physiogel ", Inscription = "Skin Cleanser" },
                        new { Id = 251, BrandId = 109, GenericName = "Physiogel ", Inscription = "Ai Lotion" },
                        new { Id = 252, BrandId = 110, Description = "1gm", GenericName = "Ampicillin IV" },
                        new { Id = 253, BrandId = 110, Description = "750mg", GenericName = "Ampicillin IV" },
                        new { Id = 254, BrandId = 110, Description = "500mg", GenericName = "Ampicillin IV" },
                        new { Id = 255, BrandId = 110, Description = "250mg", GenericName = "Ampicillin IV" },
                        new { Id = 256, BrandId = 111, Description = "500mg", GenericName = "Mefenamic Acid", Inscription = "Cap" },
                        new { Id = 257, BrandId = 111, Description = "50mg/5ml", GenericName = "Mefenamic Acid", Inscription = "Susp" },
                        new { Id = 258, BrandId = 111, Description = "250mg", GenericName = "Mefenamic Acid", Inscription = "Cap" },
                        new { Id = 259, BrandId = 112, Description = "125mg", GenericName = "Paracetamol", Inscription = "Suppository" },
                        new { Id = 260, BrandId = 112, Description = "250mg", GenericName = "Paracetamol", Inscription = "Suppository" },
                        new { Id = 261, BrandId = 113, GenericName = "Prednisone" },
                        new { Id = 262, BrandId = 113, Description = "10mg/5ml", GenericName = "Prednisone", Inscription = "Syrup" },
                        new { Id = 263, BrandId = 114, Description = "20mg/5ml", GenericName = "Prednisolone", Inscription = "Syrup" },
                        new { Id = 264, BrandId = 115, GenericName = "Multivitamins", Inscription = "Syrup" },
                        new { Id = 265, BrandId = 116, Description = "250mg/5ml", GenericName = "Cloxacillin", Inscription = "Susp" },
                        new { Id = 266, BrandId = 116, Description = "250mg/5ml", GenericName = "Cloxacillin", Inscription = "Susp" },
                        new { Id = 267, BrandId = 116, Description = "125mg/5ml", GenericName = "Cloxacillin", Inscription = "Susp" },
                        new { Id = 268, BrandId = 117, Description = "2.5mg/2.5ml", GenericName = "Salbutamol", Inscription = "Nebule" },
                        new { Id = 269, BrandId = 118, Description = "2mg", GenericName = "Salbutamol", Inscription = "Tab" },
                        new { Id = 270, BrandId = 118, Description = "2mg/5ml", GenericName = "Salbutamol", Inscription = "Syrup" },
                        new { Id = 271, BrandId = 119, GenericName = "Salbutamol + Ipratropium Bromide", Inscription = "Nebule" },
                        new { Id = 272, BrandId = 120, Description = "1.5mg/5ml", GenericName = "Terbutaline ", Inscription = "Syrup" },
                        new { Id = 273, BrandId = 121, GenericName = "Simethicone", Inscription = "Drops" },
                        new { Id = 274, BrandId = 122, Description = "250mg/5ml", GenericName = "Cloxacillin", Inscription = "Susp" },
                        new { Id = 275, BrandId = 122, Description = "250mg/5ml", GenericName = "Cloxacillin", Inscription = "Susp" },
                        new { Id = 276, BrandId = 122, Description = "125mg/5ml", GenericName = "Cloxacillin", Inscription = "Susp" },
                        new { Id = 277, BrandId = 123, Description = "125mg/5ml", GenericName = "Metronidazole", Inscription = "Syrup" },
                        new { Id = 278, BrandId = 124, Description = "20mg/5ml", GenericName = "Prednisolone", Inscription = "Syrup" },
                        new { Id = 279, BrandId = 125, Description = "250mg", GenericName = "Ampicillin IV" },
                        new { Id = 280, BrandId = 125, Description = "1gm", GenericName = "Ampicillin IV" },
                        new { Id = 281, BrandId = 125, Description = "750mg", GenericName = "Ampicillin IV" },
                        new { Id = 282, BrandId = 125, Description = "500mg", GenericName = "Ampicillin IV" },
                        new { Id = 283, BrandId = 126, GenericName = "Sodium Chloride", Inscription = "Nasal spray" },
                        new { Id = 284, BrandId = 126, GenericName = "Sodium Chloride", Inscription = "Nasal drops" },
                        new { Id = 285, BrandId = 127, GenericName = "Ferrous Gluconate", Inscription = "Syrup" },
                        new { Id = 286, BrandId = 128, Description = "250mg/5ml", GenericName = "Cefalexin", Inscription = "Susp" },
                        new { Id = 287, BrandId = 128, Description = "125mg/5ml", GenericName = "Cefalexin", Inscription = "Susp" },
                        new { Id = 288, BrandId = 128, Description = "100mg/ml", GenericName = "Cefalexin", Inscription = "Drops" },
                        new { Id = 289, BrandId = 129, Description = "25/250", GenericName = "Salmeterol + Fluticasone Propionate", Inscription = "MDI" },
                        new { Id = 290, BrandId = 129, Description = "25/125", GenericName = "Salmeterol + Fluticasone Propionate", Inscription = "MDI" },
                        new { Id = 291, BrandId = 129, Description = "25/50", GenericName = "Salmeterol + Fluticasone Propionate", Inscription = "MDI" },
                        new { Id = 292, BrandId = 130, Description = "10mg", GenericName = "Montelukast", Inscription = "Tab" },
                        new { Id = 293, BrandId = 130, Description = "5mg", GenericName = "Montelukast", Inscription = "Tab" },
                        new { Id = 294, BrandId = 130, Description = "4mg", GenericName = "Montelukast", Inscription = "Tab" },
                        new { Id = 295, BrandId = 130, Description = "4mg", GenericName = "Montelukast", Inscription = "Glanules" },
                        new { Id = 296, BrandId = 131, Description = "550mg", GenericName = "Naproxen Sodium", Inscription = "Tab" },
                        new { Id = 297, BrandId = 131, Description = "275mg", GenericName = "Naproxen Sodium", Inscription = "Tab" },
                        new { Id = 298, BrandId = 132, Description = "100mg/5ml", GenericName = "Carbocisteine", Inscription = "Syrup" },
                        new { Id = 299, BrandId = 132, Description = "50mg/ml", GenericName = "Carbocisteine", Inscription = "Drops" },
                        new { Id = 300, BrandId = 133, GenericName = "Salbutamol + Guaifenesin", Inscription = "Syrup" },
                        new { Id = 301, BrandId = 134, Description = "500mg", GenericName = "Fluocloxacillin", Inscription = "Cap" },
                        new { Id = 302, BrandId = 134, Description = "250mg", GenericName = "Fluocloxacillin", Inscription = "Cap" },
                        new { Id = 303, BrandId = 134, Description = "125mg/5ml", GenericName = "Fluocloxacillin", Inscription = "Susp" },
                        new { Id = 304, BrandId = 135, Description = "250mg", GenericName = "Phenoxymethylpenicillin K", Inscription = "Cap" },
                        new { Id = 305, BrandId = 135, Description = "500mg", GenericName = "Phenoxymethylpenicillin K", Inscription = "Cap" },
                        new { Id = 306, BrandId = 136, Description = "250mg/5ml", GenericName = "Paracetamol", Inscription = "Susp" },
                        new { Id = 307, BrandId = 136, Description = "120mg/5ml", GenericName = "Paracetamol", Inscription = "Syrup" },
                        new { Id = 308, BrandId = 136, Description = "250mg", GenericName = "Paracetamol", Inscription = "Tab" },
                        new { Id = 309, BrandId = 136, Description = "250mg/5ml", GenericName = "Paracetamol", Inscription = "Syrup" },
                        new { Id = 310, BrandId = 136, Description = "500mg", GenericName = "Paracetamol", Inscription = "Tab" },
                        new { Id = 311, BrandId = 136, Description = "325mg", GenericName = "Paracetamol", Inscription = "Tab" },
                        new { Id = 312, BrandId = 136, Description = "100mg/ml", GenericName = "Paracetamol", Inscription = "Drops" },
                        new { Id = 313, BrandId = 137, Description = "100mg", GenericName = "Cefixime", Inscription = "Cap" },
                        new { Id = 314, BrandId = 137, Description = "100mg/5ml", GenericName = "Cefixime", Inscription = "Susp" },
                        new { Id = 315, BrandId = 137, Description = "200mg", GenericName = "Cefixime", Inscription = "Cap" },
                        new { Id = 316, BrandId = 137, Description = "20mg/ml", GenericName = "Cefixime", Inscription = "Drops" },
                        new { Id = 317, BrandId = 138, Description = "400mg/80/5ml", GenericName = "Cotrimoxazole", Inscription = "Susp" },
                        new { Id = 318, BrandId = 139, Description = "200mg", GenericName = "Cefixime", Inscription = "Cap" },
                        new { Id = 319, BrandId = 139, Description = "20mg/ml", GenericName = "Cefixime", Inscription = "Drops" },
                        new { Id = 320, BrandId = 139, Description = "100mg/5ml", GenericName = "Cefixime", Inscription = "Drops" },
                        new { Id = 321, BrandId = 139, Description = "100mg", GenericName = "Cefixime", Inscription = "Cap" },
                        new { Id = 322, BrandId = 140, Description = "2.5mg/2.5ml", GenericName = "Salbutamol", Inscription = "Nebule" },
                        new { Id = 323, BrandId = 140, Description = "100mgm/Inhalation", GenericName = "Salbutamol", Inscription = "MDI" },
                        new { Id = 324, BrandId = 140, Description = "2mg", GenericName = "Salbutamol", Inscription = "Tab" },
                        new { Id = 325, BrandId = 141, GenericName = "Salbutamol + Guaifenesin", Inscription = "Syrup" },
                        new { Id = 326, BrandId = 142, Description = "10mg/ml", GenericName = "Cetirizine", Inscription = "Drops" },
                        new { Id = 327, BrandId = 142, Description = "1mg/ml", GenericName = "Cetirizine", Inscription = "Solution" },
                        new { Id = 328, BrandId = 143, Description = "5mg/ml", GenericName = "Domperidone", Inscription = "Drops" },
                        new { Id = 329, BrandId = 143, Description = "5mg/5ml", GenericName = "Domperidone", Inscription = "Syrup" },
                        new { Id = 330, BrandId = 144, Description = "125mg/5ml", GenericName = "Cefaclor", Inscription = "Susp" },
                        new { Id = 331, BrandId = 144, Description = "250mg/5ml", GenericName = "Cefaclor", Inscription = "Susp" },
                        new { Id = 332, BrandId = 144, Description = "50mg/ml", GenericName = "Cefaclor", Inscription = "Drops" },
                        new { Id = 333, BrandId = 145, Description = "250mg/5ml", GenericName = "Cefalexin", Inscription = "Susp" },
                        new { Id = 334, BrandId = 145, Description = "125mg/5ml", GenericName = "Cefalexin", Inscription = "Susp" },
                        new { Id = 335, BrandId = 145, Description = "100mg/ml", GenericName = "Cefalexin", Inscription = "Drops" },
                        new { Id = 336, BrandId = 146, Description = "5mg/ml", GenericName = "Levocetirizine Diltci", Inscription = "Syrup" },
                        new { Id = 337, BrandId = 146, Description = "5mg", GenericName = "Levocetirizine Diltci", Inscription = "Tab" },
                        new { Id = 338, BrandId = 146, Description = "5mg/ml", GenericName = "Levocetirizine Diltci", Inscription = "Drops" },
                        new { Id = 339, BrandId = 147, GenericName = "Brompheniramine Maleate + Phenylpropanolamine", Inscription = "Drops" },
                        new { Id = 340, BrandId = 147, GenericName = "Brompheniramine Maleate + Phenylpropanolamine", Inscription = "Syrup" },
                        new { Id = 341, BrandId = 148, Description = "250mg", GenericName = "Cefuroxime", Inscription = "Cap" },
                        new { Id = 342, BrandId = 149, Description = "500mg", GenericName = "Azithromycin", Inscription = "Tab" },
                        new { Id = 343, BrandId = 149, Description = "250mg", GenericName = "Azithromycin", Inscription = "Tab" },
                        new { Id = 344, BrandId = 149, Description = "200mg/5ml", GenericName = "Azithromycin", Inscription = "Susp" },
                        new { Id = 345, BrandId = 150, Description = "250mg/5ml", GenericName = "Cefuroxime", Inscription = "Susp" },
                        new { Id = 346, BrandId = 150, Description = "125mg/5ml", GenericName = "Cefuroxime", Inscription = "Susp" },
                        new { Id = 347, BrandId = 151, Description = "500mg", GenericName = "Azithromycin", Inscription = "Tab" },
                        new { Id = 348, BrandId = 151, Description = "200mg/5ml", GenericName = "Azithromycin", Inscription = "Susp" },
                        new { Id = 349, BrandId = 152, Description = "250mg", GenericName = "Azithromycin", Inscription = "Tab" },
                        new { Id = 350, BrandId = 152, Description = "400mg", GenericName = "Acyclovir", Inscription = "Tab" },
                        new { Id = 351, BrandId = 152, Description = "200mg", GenericName = "Acyclovir", Inscription = "Tab" },
                        new { Id = 352, BrandId = 153, Description = "10mg/ml", GenericName = "Cetirizine", Inscription = "Drops" },
                        new { Id = 353, BrandId = 153, Description = "1mg/ml", GenericName = "Cetirizine", Inscription = "Solution" },
                        new { Id = 354, BrandId = 89, Description = "30mg", GenericName = "Ambroxol", Inscription = "Tab" },
                        new { Id = 355, BrandId = 89, Description = "30mg/5ml", GenericName = "Ambroxol", Inscription = "Syrup" },
                        new { Id = 356, BrandId = 89, Description = "15mg/5ml", GenericName = "Ambroxol", Inscription = "Syrup" }
                    );
                });

            modelBuilder.Entity("SaintJudeHospital.Data.Entity.Parent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Occupation");

                    b.HasKey("Id");

                    b.ToTable("Parents");
                });

            modelBuilder.Entity("SaintJudeHospital.Data.Entity.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<int>("Age");

                    b.Property<string>("CivilStatus");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<string>("FirstName");

                    b.Property<string>("Gender");

                    b.Property<string>("LastName");

                    b.Property<int?>("Parent1Id");

                    b.Property<int?>("Parent2Id");

                    b.Property<int?>("ParentId1");

                    b.Property<int?>("ParentId2");

                    b.Property<int>("PatientStatusId");

                    b.HasKey("Id");

                    b.HasIndex("Parent1Id");

                    b.HasIndex("Parent2Id");

                    b.HasIndex("PatientStatusId");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("SaintJudeHospital.Data.Entity.PatientStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("PatientStatuses");
                });

            modelBuilder.Entity("SaintJudeHospital.Data.Entity.Role", b =>
                {
                    b.Property<int>("RoleId");

                    b.Property<string>("Name");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new { RoleId = 1, Name = "Administrator" },
                        new { RoleId = 2, Name = "StandardUser" }
                    );
                });

            modelBuilder.Entity("SaintJudeHospital.Data.Entity.Symtom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Symtoms");

                    b.HasData(
                        new { Id = 1, Name = "Bleeding" },
                        new { Id = 2, Name = "Bruise" },
                        new { Id = 3, Name = "Cough" },
                        new { Id = 4, Name = "Bites" },
                        new { Id = 5, Name = "Fever" },
                        new { Id = 6, Name = "Cold" },
                        new { Id = 7, Name = "Difficulty in swallowing" },
                        new { Id = 8, Name = "Ear discharge" },
                        new { Id = 9, Name = "Ear ache/pain" },
                        new { Id = 10, Name = "Constipation" },
                        new { Id = 11, Name = "Diarrhea" },
                        new { Id = 12, Name = "Hair fall" },
                        new { Id = 13, Name = "Abdominal pain" },
                        new { Id = 14, Name = "Deformity" },
                        new { Id = 15, Name = "Headache" },
                        new { Id = 16, Name = "Infected wounds" },
                        new { Id = 17, Name = "Itchness" },
                        new { Id = 18, Name = "Loss of consciousness" },
                        new { Id = 19, Name = "Mass" },
                        new { Id = 20, Name = "Joint pain" },
                        new { Id = 21, Name = "Muscle pain" },
                        new { Id = 22, Name = "Skin lesions" },
                        new { Id = 23, Name = "Trauma" },
                        new { Id = 24, Name = "Pain urination" },
                        new { Id = 25, Name = "Rushes" },
                        new { Id = 26, Name = "Less appetite" },
                        new { Id = 27, Name = "LBM" },
                        new { Id = 28, Name = "Vomiting" },
                        new { Id = 29, Name = "Dysuria" },
                        new { Id = 30, Name = "Rashes" },
                        new { Id = 31, Name = "Dysphagia" },
                        new { Id = 32, Name = "Vaginal Discharge" },
                        new { Id = 33, Name = "Urticarial rash" },
                        new { Id = 34, Name = "Eye discharge" },
                        new { Id = 35, Name = "Chest gurgling" },
                        new { Id = 36, Name = "Epistaxis" },
                        new { Id = 37, Name = "Pustules" },
                        new { Id = 38, Name = "Nasal congestion" }
                    );
                });

            modelBuilder.Entity("SaintJudeHospital.Data.Entity.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Password");

                    b.Property<int>("RoleId");

                    b.Property<string>("Username");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new { UserId = 1, FirstName = "Carl", LastName = "Tanilon", Password = "1234", RoleId = 1, Username = "carl" }
                    );
                });

            modelBuilder.Entity("SaintJudeHospital.Data.Entity.Vaccine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Booster");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int>("Dose");

                    b.Property<string>("Name");

                    b.Property<int>("Price");

                    b.Property<int>("VaccineTypeId");

                    b.HasKey("Id");

                    b.HasIndex("VaccineTypeId");

                    b.ToTable("Vaccines");
                });

            modelBuilder.Entity("SaintJudeHospital.Data.Entity.VaccinePatient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CheckupId");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int>("PatientId");

                    b.Property<int>("VaccineId");

                    b.HasKey("Id");

                    b.HasIndex("CheckupId");

                    b.HasIndex("PatientId");

                    b.HasIndex("VaccineId");

                    b.ToTable("VaccinePatients");
                });

            modelBuilder.Entity("SaintJudeHospital.Data.Entity.VaccineType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("VaccineTypes");
                });

            modelBuilder.Entity("SaintJudeHospital.Data.Entity.Bill", b =>
                {
                    b.HasOne("SaintJudeHospital.Data.Entity.BillStatus", "BillStatus")
                        .WithMany()
                        .HasForeignKey("BillStatusId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SaintJudeHospital.Data.Entity.Checkup", "Checkup")
                        .WithMany()
                        .HasForeignKey("CheckupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SaintJudeHospital.Data.Entity.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SaintJudeHospital.Data.Entity.MedicalCertificate", b =>
                {
                    b.HasOne("SaintJudeHospital.Data.Entity.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SaintJudeHospital.Data.Entity.Medicine", b =>
                {
                    b.HasOne("SaintJudeHospital.Data.Entity.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId");
                });

            modelBuilder.Entity("SaintJudeHospital.Data.Entity.Patient", b =>
                {
                    b.HasOne("SaintJudeHospital.Data.Entity.Parent", "Parent1")
                        .WithMany()
                        .HasForeignKey("Parent1Id");

                    b.HasOne("SaintJudeHospital.Data.Entity.Parent", "Parent2")
                        .WithMany()
                        .HasForeignKey("Parent2Id");

                    b.HasOne("SaintJudeHospital.Data.Entity.PatientStatus", "PatientStatus")
                        .WithMany()
                        .HasForeignKey("PatientStatusId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SaintJudeHospital.Data.Entity.User", b =>
                {
                    b.HasOne("SaintJudeHospital.Data.Entity.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SaintJudeHospital.Data.Entity.Vaccine", b =>
                {
                    b.HasOne("SaintJudeHospital.Data.Entity.VaccineType", "VaccineType")
                        .WithMany()
                        .HasForeignKey("VaccineTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SaintJudeHospital.Data.Entity.VaccinePatient", b =>
                {
                    b.HasOne("SaintJudeHospital.Data.Entity.Checkup", "Chekup")
                        .WithMany()
                        .HasForeignKey("CheckupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SaintJudeHospital.Data.Entity.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SaintJudeHospital.Data.Entity.Vaccine", "Vaccine")
                        .WithMany()
                        .HasForeignKey("VaccineId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
