// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SaintJudeHospital.Data.Entity;

namespace SaintJudeHospital.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20190806135901_rename_middleinitial_to_middlename_in_parent_and_patient_table")]
    partial class rename_middleinitial_to_middlename_in_parent_and_patient_table
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("SaintJudeHospital.Data.Entity.Bill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BillStatusId");

                    b.Property<int>("CheckupId");

                    b.Property<decimal>("ConsultationFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<decimal>("EarPiercingFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FollowUpFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NebulizationFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PPDFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PatientId");

                    b.Property<string>("PayProcess");

                    b.Property<decimal>("TotalPayment")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("VaccineInfo");

                    b.HasKey("Id");

                    b.HasIndex("BillStatusId");

                    b.HasIndex("CheckupId");

                    b.HasIndex("PatientId");

                    b.ToTable("Bills");
                });

            modelBuilder.Entity("SaintJudeHospital.Data.Entity.BillStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("BillStatuses");
                });

            modelBuilder.Entity("SaintJudeHospital.Data.Entity.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new { Id = 1, Name = "Activent" },
                        new { Id = 2, Name = "Advil" },
                        new { Id = 3, Name = "Allerkid" },
                        new { Id = 4, Name = "Alloxygen" },
                        new { Id = 5, Name = "Alnix" },
                        new { Id = 6, Name = "Alvedon" },
                        new { Id = 7, Name = "Ambrolex" },
                        new { Id = 8, Name = "Amoclav" },
                        new { Id = 9, Name = "Amoxil" },
                        new { Id = 10, Name = "Ampicin" },
                        new { Id = 11, Name = "Ansimar" },
                        new { Id = 12, Name = "Antiox" },
                        new { Id = 13, Name = "Asfrenon" },
                        new { Id = 14, Name = "Asfrenon Expt" },
                        new { Id = 15, Name = "Asmalin" },
                        new { Id = 16, Name = "Asmalin Broncho" },
                        new { Id = 17, Name = "Augmentin" },
                        new { Id = 18, Name = "Avamys" },
                        new { Id = 19, Name = "Azith" },
                        new { Id = 20, Name = "Bacidal" },
                        new { Id = 21, Name = "Bactroban" },
                        new { Id = 22, Name = "Bambec" },
                        new { Id = 23, Name = "Bioclauid" },
                        new { Id = 24, Name = "Biogesic" },
                        new { Id = 25, Name = "Bricanyl" },
                        new { Id = 26, Name = "Broncaire Expt" },
                        new { Id = 27, Name = "Bronchofen" },
                        new { Id = 28, Name = "Calmoseptine" },
                        new { Id = 29, Name = "Calpol" },
                        new { Id = 30, Name = "Ceclor" },
                        new { Id = 31, Name = "Cefalin" },
                        new { Id = 32, Name = "Ceporex" },
                        new { Id = 33, Name = "Cherifer" },
                        new { Id = 34, Name = "Chloromycetin" },
                        new { Id = 35, Name = "Clariget" },
                        new { Id = 36, Name = "Clarithro-Natrapharm Klaryz" },
                        new { Id = 37, Name = "Clarithro-natrapharm" },
                        new { Id = 38, Name = "Clarithrocid" },
                        new { Id = 39, Name = "Clotrasone" },
                        new { Id = 40, Name = "Combantrin" },
                        new { Id = 41, Name = "Combivent" },
                        new { Id = 42, Name = "Daktarin" },
                        new { Id = 43, Name = "Dalacin C" },
                        new { Id = 44, Name = "Dg" },
                        new { Id = 45, Name = "Dilatair" },
                        new { Id = 46, Name = "Dimetapp" },
                        new { Id = 47, Name = "Disudrin" },
                        new { Id = 48, Name = "Dolan" },
                        new { Id = 49, Name = "Dolfenal" },
                        new { Id = 50, Name = "Duavent" },
                        new { Id = 51, Name = "E Zinc" },
                        new { Id = 52, Name = "Elica" },
                        new { Id = 53, Name = "Erceflora" },
                        new { Id = 54, Name = "Ercefuryl" },
                        new { Id = 55, Name = "Essentiale Forte" },
                        new { Id = 56, Name = "Expel" },
                        new { Id = 57, Name = "Faspic" },
                        new { Id = 58, Name = "Flagyl" },
                        new { Id = 59, Name = "Flanax" },
                        new { Id = 60, Name = "Fluimucil" },
                        new { Id = 61, Name = "Fucidin" },
                        new { Id = 62, Name = "Fucidin-h" },
                        new { Id = 63, Name = "Fucithalmic" },
                        new { Id = 64, Name = "Furoxone" },
                        new { Id = 65, Name = "Garamycin" },
                        new { Id = 66, Name = "Gardan" },
                        new { Id = 67, Name = "Heraclene" },
                        new { Id = 68, Name = "Himox" },
                        new { Id = 69, Name = "Hisdec" },
                        new { Id = 70, Name = "Hydrite" },
                        new { Id = 71, Name = "Ilosone" },
                        new { Id = 72, Name = "Immunosine" },
                        new { Id = 73, Name = "Iterax" },
                        new { Id = 74, Name = "Jetepar" },
                        new { Id = 75, Name = "Kastair" },
                        new { Id = 76, Name = "Katrex" },
                        new { Id = 77, Name = "Klarizid" },
                        new { Id = 78, Name = "Klaz" },
                        new { Id = 79, Name = "Locetar" },
                        new { Id = 80, Name = "Loviscol" },
                        new { Id = 81, Name = "Maalox" },
                        new { Id = 82, Name = "Medicol" },
                        new { Id = 83, Name = "Meptin" },
                        new { Id = 84, Name = "Montemax" },
                        new { Id = 85, Name = "Montiget" },
                        new { Id = 86, Name = "Motilium" },
                        new { Id = 87, Name = "Movelax" },
                        new { Id = 88, Name = "Muconase" },
                        new { Id = 89, Name = "Mucosolvan" },
                        new { Id = 90, Name = "Myonal" },
                        new { Id = 91, Name = "Myremol" },
                        new { Id = 92, Name = "Napran" },
                        new { Id = 93, Name = "Naprex" },
                        new { Id = 94, Name = "Nasatapp" },
                        new { Id = 95, Name = "Nasathera" },
                        new { Id = 96, Name = "Nasoclear" },
                        new { Id = 97, Name = "Natravox" },
                        new { Id = 98, Name = "Neozep" },
                        new { Id = 99, Name = "Nuelin" },
                        new { Id = 100, Name = "Omepron" },
                        new { Id = 101, Name = "Opigesic" },
                        new { Id = 102, Name = "Optipred" },
                        new { Id = 103, Name = "Orastin" },
                        new { Id = 104, Name = "Pediachlor" },
                        new { Id = 105, Name = "Pediamox" },
                        new { Id = 106, Name = "Pediatapp" },
                        new { Id = 107, Name = "Penachlor" },
                        new { Id = 108, Name = "Pharex" },
                        new { Id = 109, Name = "Physiogel" },
                        new { Id = 110, Name = "Polypen" },
                        new { Id = 111, Name = "Ponstan" },
                        new { Id = 112, Name = "Poro" },
                        new { Id = 113, Name = "Pred 10" },
                        new { Id = 114, Name = "Pred 20" },
                        new { Id = 115, Name = "Propan Tlc" },
                        new { Id = 116, Name = "Prostaphlin-A" },
                        new { Id = 117, Name = "Provexcel" },
                        new { Id = 118, Name = "Prox-S" },
                        new { Id = 119, Name = "Pulmodual" },
                        new { Id = 120, Name = "Pulmoxcel" },
                        new { Id = 121, Name = "Restime" },
                        new { Id = 122, Name = "Ritemed" },
                        new { Id = 123, Name = "Rodazid" },
                        new { Id = 124, Name = "Romamed" },
                        new { Id = 125, Name = "Rotocin" },
                        new { Id = 126, Name = "Salinase" },
                        new { Id = 127, Name = "Sangobion" },
                        new { Id = 128, Name = "Selzef" },
                        new { Id = 129, Name = "Seretide" },
                        new { Id = 130, Name = "Singulair" },
                        new { Id = 131, Name = "Skelan" },
                        new { Id = 132, Name = "Solmux" },
                        new { Id = 133, Name = "Solmux Broncho" },
                        new { Id = 134, Name = "Stafloxin" },
                        new { Id = 135, Name = "Sumapen" },
                        new { Id = 136, Name = "Tempra" },
                        new { Id = 137, Name = "Tergecet" },
                        new { Id = 138, Name = "Trizole" },
                        new { Id = 139, Name = "Ultraxime" },
                        new { Id = 140, Name = "Ventolin" },
                        new { Id = 141, Name = "Ventolin Expt" },
                        new { Id = 142, Name = "Virlix" },
                        new { Id = 143, Name = "Vometa" },
                        new { Id = 144, Name = "Xelent" },
                        new { Id = 145, Name = "Xinflex" },
                        new { Id = 146, Name = "Xyzal" },
                        new { Id = 147, Name = "Zeditapp" },
                        new { Id = 148, Name = "Zegen" },
                        new { Id = 149, Name = "Zenith" },
                        new { Id = 150, Name = "Zinnat" },
                        new { Id = 151, Name = "Zithromax" },
                        new { Id = 152, Name = "Zovirax" },
                        new { Id = 153, Name = "Zyrtec" }
                    );
                });

            modelBuilder.Entity("SaintJudeHospital.Data.Entity.Checkup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<string>("Assessment");

                    b.Property<string>("CivilStatus");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<string>("Diagnosis");

                    b.Property<string>("Gender");

                    b.Property<string>("HeadCircum");

                    b.Property<string>("Height");

                    b.Property<string>("Name");

                    b.Property<DateTime>("NextVisitDate");

                    b.Property<string>("Objective");

                    b.Property<string>("Prescription");

                    b.Property<string>("Subjective");

                    b.Property<string>("Temperature");

                    b.Property<string>("Weight");

                    b.HasKey("Id");

                    b.ToTable("Checkups");
                });

            modelBuilder.Entity("SaintJudeHospital.Data.Entity.Generic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Generics");

                    b.HasData(
                        new { Id = 1, Name = "Acetylcysteine" },
                        new { Id = 2, Name = "Acyclovir" },
                        new { Id = 3, Name = "Aluminum Magnesium Hydroxide" },
                        new { Id = 4, Name = "Ambroxol" },
                        new { Id = 5, Name = "Amorolfine" },
                        new { Id = 6, Name = "Amoxicillin" },
                        new { Id = 7, Name = "Ampicillin IV" },
                        new { Id = 8, Name = "Azithromycin" },
                        new { Id = 9, Name = "Bacillus Clausii" },
                        new { Id = 10, Name = "Bambuterol" },
                        new { Id = 11, Name = "Betaine Glucuronate Plus" },
                        new { Id = 12, Name = "Brompheniramine Maleate + Phenylephrine" },
                        new { Id = 13, Name = "Brompheniramine Maleate + Phenylpropanolamine" },
                        new { Id = 14, Name = "Broncho Vaxom" },
                        new { Id = 15, Name = "Calmoseptine" },
                        new { Id = 16, Name = "Carbocisteine" },
                        new { Id = 17, Name = "Cefaclor" },
                        new { Id = 18, Name = "Cefaclor + Guaifenesin" },
                        new { Id = 19, Name = "Cefalexin" },
                        new { Id = 20, Name = "Cefixime" },
                        new { Id = 21, Name = "Cefuroxime" },
                        new { Id = 22, Name = "Cetirizine" },
                        new { Id = 23, Name = "Chloramphenicol" },
                        new { Id = 24, Name = "Clarithromycin" },
                        new { Id = 25, Name = "Clindamycin" },
                        new { Id = 26, Name = "Clotrimazole + Betamethasone" },
                        new { Id = 27, Name = "Cloxacillin" },
                        new { Id = 28, Name = "Co Amoxiclav" },
                        new { Id = 29, Name = "Cotrimoxazole" },
                        new { Id = 30, Name = "Dg Milk" },
                        new { Id = 31, Name = "Dibencozide" },
                        new { Id = 32, Name = "Domperidone" },
                        new { Id = 33, Name = "Doxofylline" },
                        new { Id = 34, Name = "Eperisone HCI" },
                        new { Id = 35, Name = "Erythromycin" },
                        new { Id = 36, Name = "Ferrous Gluconate" },
                        new { Id = 37, Name = "Fluocloxacillin" },
                        new { Id = 38, Name = "Fluticasone Furoate" },
                        new { Id = 39, Name = "Fucidic Acid" },
                        new { Id = 40, Name = "Fucidic Acid + Hydrocortisone" },
                        new { Id = 41, Name = "Furazolidone" },
                        new { Id = 42, Name = "Fusidate Sodium" },
                        new { Id = 43, Name = "Gentamicin IV" },
                        new { Id = 44, Name = "Gentamycin" },
                        new { Id = 45, Name = "Glycerin" },
                        new { Id = 46, Name = "Hydroxyzine diHCI" },
                        new { Id = 47, Name = "Ibuprofen" },
                        new { Id = 48, Name = "Inosiplex" },
                        new { Id = 49, Name = "Lactulose" },
                        new { Id = 50, Name = "Levocetirizine Diltci" },
                        new { Id = 51, Name = "Mebendazole" },
                        new { Id = 52, Name = "Mefenamic Acid" },
                        new { Id = 53, Name = "Metronidazole" },
                        new { Id = 54, Name = "Miconazole" },
                        new { Id = 55, Name = "Mometasone Furoate" },
                        new { Id = 56, Name = "Montelukast" },
                        new { Id = 57, Name = "Multivitamins" },
                        new { Id = 58, Name = "Mupirocin" },
                        new { Id = 59, Name = "Naproxen Sodium" },
                        new { Id = 60, Name = "Nifuroxazide" },
                        new { Id = 61, Name = "Nystatin" },
                        new { Id = 62, Name = "Omeprazole" },
                        new { Id = 63, Name = "Oral Rehydration Solution" },
                        new { Id = 64, Name = "Paracetamol" },
                        new { Id = 65, Name = "Paracetamol + Phenylpropanolamine" },
                        new { Id = 66, Name = "Phenoxymethylpenicillin K" },
                        new { Id = 67, Name = "Phenylephrine Hcl + Chlorpheniramine Maleate" },
                        new { Id = 68, Name = "Phenylpropanolamine" },
                        new { Id = 69, Name = "Phospholipids" },
                        new { Id = 70, Name = "Physiogel" },
                        new { Id = 71, Name = "Prednisolone" },
                        new { Id = 72, Name = "Prednisone" },
                        new { Id = 73, Name = "Procaterol" },
                        new { Id = 74, Name = "Pyrantel Pamoate" },
                        new { Id = 75, Name = "Salbutamol" },
                        new { Id = 76, Name = "Salbutamol + Guaifenesin" },
                        new { Id = 77, Name = "Salbutamol + Ipratropium Bromide" },
                        new { Id = 78, Name = "Salmeterol + Fluticasone Propionate" },
                        new { Id = 79, Name = "Simethicone" },
                        new { Id = 80, Name = "Sodium Chloride" },
                        new { Id = 81, Name = "Terbutaline" },
                        new { Id = 82, Name = "Theophylline" },
                        new { Id = 83, Name = "Zinc Sulfate" }
                    );
                });

            modelBuilder.Entity("SaintJudeHospital.Data.Entity.Immunize", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Immunizes");

                    b.HasData(
                        new { Id = 1, Amount = 3000m, Name = "HEXA" },
                        new { Id = 2, Amount = 3200m, Name = "PCV 10" },
                        new { Id = 3, Amount = 750m, Name = "MEASLES" },
                        new { Id = 4, Amount = 1300m, Name = "HIB" },
                        new { Id = 5, Amount = 4000m, Name = "MENINGO" },
                        new { Id = 6, Amount = 1300m, Name = "TYPHOID" },
                        new { Id = 7, Amount = 1800m, Name = "HEP A" },
                        new { Id = 8, Amount = 700m, Name = "HEP B" },
                        new { Id = 9, Amount = 1600m, Name = "TETRAXIM" },
                        new { Id = 10, Amount = 1200m, Name = "MMR" },
                        new { Id = 11, Amount = 2200m, Name = "CHICKEN POX" },
                        new { Id = 12, Amount = 2500m, Name = "PENTA" },
                        new { Id = 13, Amount = 900m, Name = "BCG-1" },
                        new { Id = 14, Amount = 3000m, Name = "MMR-V" },
                        new { Id = 15, Amount = 1700m, Name = "PNEUMO-23" },
                        new { Id = 16, Amount = 1700m, Name = "RABIES" },
                        new { Id = 17, Amount = 3000m, Name = "ROTARIX" },
                        new { Id = 18, Amount = 2200m, Name = "ROTATEQ" },
                        new { Id = 19, Amount = 1000m, Name = "FLU" },
                        new { Id = 20, Amount = 4000m, Name = "PCV" },
                        new { Id = 21, Amount = 0m, Name = "BCG-2" }
                    );
                });

            modelBuilder.Entity("SaintJudeHospital.Data.Entity.InPatient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreateDate");

                    b.Property<string>("Name");

                    b.Property<string>("Type");

                    b.HasKey("Id");

                    b.ToTable("InPatients");
                });

            modelBuilder.Entity("SaintJudeHospital.Data.Entity.Inscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Inscriptions");

                    b.HasData(
                        new { Id = 1, Name = "Ai Lotion" },
                        new { Id = 2, Name = "Amp" },
                        new { Id = 3, Name = "Campsuele" },
                        new { Id = 4, Name = "Cream" },
                        new { Id = 5, Name = "Drops" },
                        new { Id = 6, Name = "Eyedrops" },
                        new { Id = 7, Name = "Granules" },
                        new { Id = 8, Name = "Lotion" },
                        new { Id = 9, Name = "MDI" },
                        new { Id = 10, Name = "Nail Lacquer" },
                        new { Id = 11, Name = "Nasal Drops" },
                        new { Id = 12, Name = "Nebule" },
                        new { Id = 13, Name = "Ointment" },
                        new { Id = 14, Name = "Oral Gel" },
                        new { Id = 15, Name = "Oral Solution" },
                        new { Id = 16, Name = "Pediatric Capsule" },
                        new { Id = 17, Name = "Pediatric Suppository" },
                        new { Id = 18, Name = "Sachet" },
                        new { Id = 19, Name = "Skin Cleanser" },
                        new { Id = 20, Name = "Solution" },
                        new { Id = 21, Name = "Suppository" },
                        new { Id = 22, Name = "Suspension" },
                        new { Id = 23, Name = "Syrup" },
                        new { Id = 24, Name = "Tablet" },
                        new { Id = 25, Name = "Tube" },
                        new { Id = 26, Name = "Bottle" },
                        new { Id = 27, Name = "Nasal Spray" },
                        new { Id = 28, Name = "Can" }
                    );
                });

            modelBuilder.Entity("SaintJudeHospital.Data.Entity.Laboratory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Laboratories");

                    b.HasData(
                        new { Id = 1, Name = "75 gms.OGTT" },
                        new { Id = 2, Name = "Acid Fast Bacili Staining(AFB)" },
                        new { Id = 3, Name = "24 Urine Cortisol" },
                        new { Id = 4, Name = "50 gms.OGTT" },
                        new { Id = 5, Name = "* Alpha - fetoprotein(AFP)" },
                        new { Id = 6, Name = "* Amylase(Urine)" },
                        new { Id = 7, Name = "* Amylase(Blood)" },
                        new { Id = 8, Name = "2 HPPBS" },
                        new { Id = 9, Name = "* Acid Phosphatase(ACP)" },
                        new { Id = 10, Name = "Acid Phosphatase(Prostatic ACP)" },
                        new { Id = 11, Name = "100 gms.OGTT" },
                        new { Id = 12, Name = "Albumin / Globulin(Alb / Glob)" },
                        new { Id = 13, Name = "* ANA(Screening and Panel)" },
                        new { Id = 14, Name = "* Anti - HAV lgM" },
                        new { Id = 15, Name = "Alkaline Phosphatase(ALP)" },
                        new { Id = 16, Name = "* Anti - HBc lgM" },
                        new { Id = 17, Name = "* Anti - Hav Total" },
                        new { Id = 18, Name = "* Anti - HBe" },
                        new { Id = 19, Name = "* Anti - HBc Total" },
                        new { Id = 20, Name = "* Anti - streptolysin O Titer(ASO Titer)" },
                        new { Id = 21, Name = "* Anti - HCV(Screening)" },
                        new { Id = 22, Name = "* Anti - H.Pylori" },
                        new { Id = 23, Name = "* Anti - HCV EIA" },
                        new { Id = 24, Name = "* Anti - HBs(Semi - QUanti)" },
                        new { Id = 25, Name = "* Anti - HBs Titer" },
                        new { Id = 26, Name = "Beta - HCG / Dilution(Urine)" },
                        new { Id = 27, Name = "* Beta - HCG(Blood)" },
                        new { Id = 28, Name = "Biliribin - Direct / Indirect(DB / IB)" },
                        new { Id = 29, Name = "* Biopsy(Small)" },
                        new { Id = 30, Name = "Blood Urea Nitrogen(BUN)" },
                        new { Id = 31, Name = "Blood Indices" },
                        new { Id = 32, Name = "Blood Typing(BT)" },
                        new { Id = 33, Name = "* Biopsy(Lagre)" },
                        new { Id = 34, Name = "Bilirubin - Total(TB)" },
                        new { Id = 35, Name = "Blood Uric Acid(BUA)" },
                        new { Id = 36, Name = "* C3 700 - W / I" },
                        new { Id = 37, Name = "* Carcino - embryonic Ag(CEA)" },
                        new { Id = 38, Name = "Calcium(Urine Ca++)" },
                        new { Id = 39, Name = "* C4 750 - W / I" },
                        new { Id = 40, Name = "* CA 19.9" },
                        new { Id = 41, Name = "* CA 15.3" },
                        new { Id = 42, Name = "* CA 125" },
                        new { Id = 43, Name = "* C - Reactive Protein(CRP)" },
                        new { Id = 44, Name = "Calcium(Blood Ca++)" },
                        new { Id = 45, Name = "* Cortisol" },
                        new { Id = 46, Name = "* Cholinesterase - Serum" },
                        new { Id = 47, Name = "Complete Blood Count(CBC)" },
                        new { Id = 48, Name = "* Creatine Kinase(CK - MB)" },
                        new { Id = 49, Name = "Creatinine Total(Urine)" },
                        new { Id = 50, Name = "Cerebrospinal Fluid Routine(CSF)" },
                        new { Id = 51, Name = "Chloride(CI -)" },
                        new { Id = 52, Name = "Chlamydia w / Check - up" },
                        new { Id = 53, Name = "Cholesterol - Total" },
                        new { Id = 54, Name = "Cholesterol(HDL / VLD / LDL)" },
                        new { Id = 55, Name = "Cholinesterase - RBC" },
                        new { Id = 56, Name = "Creatinine(Blood)" },
                        new { Id = 57, Name = "Dengue NS1 Ag" },
                        new { Id = 58, Name = "* DsDNA" },
                        new { Id = 59, Name = "Erythrocyte Sedimentation Rate(ESR)" },
                        new { Id = 60, Name = "* Estradiol" },
                        new { Id = 61, Name = "Free Thyroxine(FT4)" },
                        new { Id = 62, Name = "* Free Triiodothyronine(FT3)" },
                        new { Id = 63, Name = "Gamma - GT(GGT)" },
                        new { Id = 64, Name = "* Ferritin" },
                        new { Id = 65, Name = "Clotting Time - Bleeding Time(CT - BT)" },
                        new { Id = 66, Name = "Fasting Blood Sugar(FBS)" },
                        new { Id = 67, Name = "Eosinophils" },
                        new { Id = 68, Name = "Hepatitis B Profile" },
                        new { Id = 69, Name = "Ketones" },
                        new { Id = 70, Name = "KOH" },
                        new { Id = 71, Name = "Hemoglucotest(HGT)" },
                        new { Id = 72, Name = "Hematocrit(Hct)" },
                        new { Id = 73, Name = "Gonorrhea w / Check - up" },
                        new { Id = 74, Name = "* Lactate Dehydrogenase(LDH)" },
                        new { Id = 75, Name = "L.E.Preparation" },
                        new { Id = 76, Name = "Lipid Profile" },
                        new { Id = 77, Name = "Liver Profile" },
                        new { Id = 78, Name = "* Luteinizing Hormone(LH)" },
                        new { Id = 79, Name = "* Magnesium(Mg + 2)" },
                        new { Id = 80, Name = "MCA" },
                        new { Id = 81, Name = "Micral Test" },
                        new { Id = 82, Name = "Glycosylated Hemoglobin(HbA1C)" },
                        new { Id = 83, Name = "Gram Staining(G / S)" },
                        new { Id = 84, Name = "Hemoglobin(Hgb)" },
                        new { Id = 85, Name = "HBsAg(Screening)" },
                        new { Id = 86, Name = "* HBsAg(EIA)" },
                        new { Id = 87, Name = "* HBeAg" },
                        new { Id = 88, Name = "Pregnancy Test(PT)" },
                        new { Id = 89, Name = "Potassium(Urine K +)" },
                        new { Id = 90, Name = "Peripheral Smear" },
                        new { Id = 91, Name = "Platelet Count(Plt.Ct.)" },
                        new { Id = 92, Name = "* Phosphorus(Inorg)" },
                        new { Id = 93, Name = "Newborn Screening(NBS)" },
                        new { Id = 94, Name = "Osmotic Fragility" },
                        new { Id = 95, Name = "Pap smear w / check up" },
                        new { Id = 96, Name = "* Parathyroid Hormone(PTH)" },
                        new { Id = 97, Name = "Pleural Routine" },
                        new { Id = 98, Name = "Potassium(Blood K +)" },
                        new { Id = 99, Name = "Occult Blood" },
                        new { Id = 100, Name = "Malarial Smear" },
                        new { Id = 101, Name = "* Testosterone" },
                        new { Id = 102, Name = "* Thyroglobulin" },
                        new { Id = 103, Name = "Thyroid Panel" },
                        new { Id = 104, Name = "Thyroid - stimulating Hormone(TSH)" },
                        new { Id = 105, Name = "Thyroxine(T4)" },
                        new { Id = 106, Name = "SGOT / ASAT" },
                        new { Id = 107, Name = "Random Blood Sugar(RBS)" },
                        new { Id = 108, Name = "SGPT / ALAT" },
                        new { Id = 109, Name = "* Rheumatoid Factor(RA / RF)" },
                        new { Id = 110, Name = "Stool Exam(S / E)" },
                        new { Id = 111, Name = "Sodium(Urine Na +)" },
                        new { Id = 112, Name = "Sodium(Blood Na +)" },
                        new { Id = 113, Name = "* Progesterone" },
                        new { Id = 114, Name = "Prostate - Specific Ag(PSA Qualitative)" },
                        new { Id = 115, Name = "* Prolcatin" },
                        new { Id = 116, Name = "* Prostate - Specific Ag(PSA Quantitative)" },
                        new { Id = 117, Name = "Protein Albumin(Urine)" },
                        new { Id = 118, Name = "Reticulocyte Count(Retic.Ct.)" },
                        new { Id = 119, Name = "Triiodothyronine(T3)" },
                        new { Id = 120, Name = "Triglycerides" },
                        new { Id = 121, Name = "TPHA" },
                        new { Id = 122, Name = "Total Protein(TP)" },
                        new { Id = 123, Name = "* Total CPK NAC" },
                        new { Id = 124, Name = "Semen Analysis" },
                        new { Id = 125, Name = "PTPA - Protime / Prothrombin Time" },
                        new { Id = 126, Name = "Wet Mount" },
                        new { Id = 127, Name = "Thphidot" },
                        new { Id = 128, Name = "White Blood Cell Differential Count(WBC Diff.Count)" },
                        new { Id = 129, Name = "Widal 5 Ags" },
                        new { Id = 130, Name = "Uric Acid(Urine" },
                        new { Id = 131, Name = "White Blood Cell Count(WBC Ct.)" },
                        new { Id = 132, Name = "* Urobilinogen" },
                        new { Id = 133, Name = "VDRL" },
                        new { Id = 134, Name = "Urinalysis(U / A)" },
                        new { Id = 135, Name = "* Troponin I(Trop.I)" },
                        new { Id = 136, Name = "* Troponin T(Trop.T)" },
                        new { Id = 137, Name = "Tuberculosis Ab(TB Ab)" }
                    );
                });

            modelBuilder.Entity("SaintJudeHospital.Data.Entity.MedicalCertificate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<string>("Diagnosis");

                    b.Property<string>("Operation");

                    b.Property<int>("PatientId");

                    b.Property<string>("Remarks");

                    b.Property<string>("Requestor");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("MedicalCertificates");
                });

            modelBuilder.Entity("SaintJudeHospital.Data.Entity.Medicine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BrandId");

                    b.Property<string>("Description");

                    b.Property<int>("GenericId");

                    b.Property<int?>("InscriptionId");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("GenericId");

                    b.HasIndex("InscriptionId");

                    b.ToTable("Medicines");

                    b.HasData(
                        new { Id = 1, Description = "10mg", GenericId = 22, InscriptionId = 24 },
                        new { Id = 2, Description = "500mg", GenericId = 6, InscriptionId = 3 },
                        new { Id = 3, Description = "250mg", GenericId = 6, InscriptionId = 3 },
                        new { Id = 4, Description = "375mg", GenericId = 28, InscriptionId = 24 },
                        new { Id = 5, Description = "30mg", GenericId = 71, InscriptionId = 24 },
                        new { Id = 6, Description = "20mg", GenericId = 71, InscriptionId = 24 },
                        new { Id = 7, Description = "5mg", GenericId = 71, InscriptionId = 24 },
                        new { Id = 8, Description = "80mg/5ml", GenericId = 43, InscriptionId = 2 },
                        new { Id = 9, Description = "40mg/5ml", GenericId = 43, InscriptionId = 2 },
                        new { Id = 10, GenericId = 14, InscriptionId = 16 },
                        new { Id = 11, GenericId = 45, InscriptionId = 17 },
                        new { Id = 12, BrandId = 1, Description = "2mg", GenericId = 75, InscriptionId = 24 },
                        new { Id = 13, BrandId = 1, Description = "2mg/5ml", GenericId = 75, InscriptionId = 23 },
                        new { Id = 14, BrandId = 2, Description = "100mg/5ml", GenericId = 47, InscriptionId = 22 },
                        new { Id = 15, BrandId = 2, Description = "200mg/5ml", GenericId = 47, InscriptionId = 22 },
                        new { Id = 16, BrandId = 2, Description = "200mg", GenericId = 47, InscriptionId = 3 },
                        new { Id = 17, BrandId = 2, Description = "100mg/2.5ml", GenericId = 47, InscriptionId = 5 },
                        new { Id = 18, BrandId = 3, Description = "5mg/5ml", GenericId = 22, InscriptionId = 23 },
                        new { Id = 19, BrandId = 3, Description = "2.5mg/ml", GenericId = 22, InscriptionId = 5 },
                        new { Id = 20, Description = "1.5mg/5ml", GenericId = 81, InscriptionId = 23 },
                        new { Id = 21, BrandId = 4, Description = "10mg", GenericId = 22, InscriptionId = 24 },
                        new { Id = 22, BrandId = 4, Description = "5mg/5ml", GenericId = 22, InscriptionId = 23 },
                        new { Id = 23, BrandId = 5, Description = "2.5mg/ml", GenericId = 22, InscriptionId = 5 },
                        new { Id = 24, BrandId = 5, Description = "250mg", GenericId = 64, InscriptionId = 24 },
                        new { Id = 25, BrandId = 5, Description = "325mg", GenericId = 64, InscriptionId = 24 },
                        new { Id = 26, BrandId = 5, Description = "500mg", GenericId = 64, InscriptionId = 24 },
                        new { Id = 27, BrandId = 6, Description = "120mg/5ml", GenericId = 64, InscriptionId = 23 },
                        new { Id = 28, BrandId = 6, Description = "100ml", GenericId = 64, InscriptionId = 5 },
                        new { Id = 29, BrandId = 7, Description = "30mg", GenericId = 4, InscriptionId = 24 },
                        new { Id = 30, BrandId = 7, Description = "30mg/3ml", GenericId = 4, InscriptionId = 23 },
                        new { Id = 31, BrandId = 7, Description = "15mg/5ml", GenericId = 4, InscriptionId = 23 },
                        new { Id = 32, BrandId = 7, Description = "7.5mg/ml", GenericId = 4, InscriptionId = 5 },
                        new { Id = 33, BrandId = 8, Description = "457mg/5ml", GenericId = 28, InscriptionId = 22 },
                        new { Id = 34, BrandId = 8, Description = "228mg/5ml", GenericId = 28, InscriptionId = 22 },
                        new { Id = 35, BrandId = 8, Description = "156mg/5ml", GenericId = 28, InscriptionId = 22 },
                        new { Id = 36, BrandId = 8, Description = "312mg/5ml", GenericId = 28, InscriptionId = 22 },
                        new { Id = 37, BrandId = 9, Description = "250mg/5ml", GenericId = 6, InscriptionId = 22 },
                        new { Id = 38, BrandId = 9, Description = "100mg/ml", GenericId = 6, InscriptionId = 5 },
                        new { Id = 39, BrandId = 9, Description = "125mg/ml", GenericId = 6, InscriptionId = 22 },
                        new { Id = 40, BrandId = 10, Description = "1mg", GenericId = 7 },
                        new { Id = 41, BrandId = 10, Description = "500mg", GenericId = 7 },
                        new { Id = 42, BrandId = 10, Description = "750mg", GenericId = 7 },
                        new { Id = 43, BrandId = 10, Description = "250mg", GenericId = 7 },
                        new { Id = 44, BrandId = 11, Description = "100mg", GenericId = 33, InscriptionId = 24 },
                        new { Id = 45, BrandId = 11, Description = "100mg/5ml", GenericId = 33, InscriptionId = 23 },
                        new { Id = 46, BrandId = 12, Description = "100mg", GenericId = 51, InscriptionId = 24 },
                        new { Id = 47, BrandId = 12, Description = "20mg/ml", GenericId = 51, InscriptionId = 22 },
                        new { Id = 48, BrandId = 12, Description = "500mg", GenericId = 51, InscriptionId = 24 },
                        new { Id = 49, BrandId = 12, Description = "50mg/ml", GenericId = 51, InscriptionId = 22 },
                        new { Id = 50, BrandId = 13, Description = "2mg/5ml", GenericId = 75, InscriptionId = 23 },
                        new { Id = 51, BrandId = 14, GenericId = 76, InscriptionId = 23 },
                        new { Id = 52, BrandId = 15, Description = "100mgm/Inhalation", GenericId = 75, InscriptionId = 9 },
                        new { Id = 53, BrandId = 15, Description = "2.5mg/2.5ml", GenericId = 75, InscriptionId = 12 },
                        new { Id = 54, BrandId = 15, Description = "2mg", GenericId = 75, InscriptionId = 24 },
                        new { Id = 55, BrandId = 15, Description = "2mg/5ml", GenericId = 75, InscriptionId = 23 },
                        new { Id = 56, BrandId = 16, GenericId = 76, InscriptionId = 23 },
                        new { Id = 57, BrandId = 17, Description = "625mg", GenericId = 28, InscriptionId = 24 },
                        new { Id = 58, BrandId = 17, Description = "156mg/5ml", GenericId = 28, InscriptionId = 22 },
                        new { Id = 59, BrandId = 17, Description = "457mg/5ml", GenericId = 28, InscriptionId = 22 },
                        new { Id = 60, BrandId = 17, Description = "228mg/5ml", GenericId = 28, InscriptionId = 22 },
                        new { Id = 61, BrandId = 17, Description = "312mg/5ml", GenericId = 28, InscriptionId = 22 },
                        new { Id = 62, BrandId = 18, Description = "27.5mgm/spray", GenericId = 38, InscriptionId = 27 },
                        new { Id = 63, BrandId = 19, Description = "500mg", GenericId = 8, InscriptionId = 24 },
                        new { Id = 64, BrandId = 19, Description = "250mg", GenericId = 8, InscriptionId = 24 },
                        new { Id = 65, BrandId = 19, Description = "200mg/5ml", GenericId = 8, InscriptionId = 22 },
                        new { Id = 66, BrandId = 20, Description = "4oomg/80mg", GenericId = 29, InscriptionId = 24 },
                        new { Id = 67, BrandId = 21, Description = "Cream", GenericId = 58, InscriptionId = 25 },
                        new { Id = 68, BrandId = 22, Description = "1mg/1ml", GenericId = 10, InscriptionId = 23 },
                        new { Id = 69, BrandId = 22, Description = "10mg", GenericId = 10, InscriptionId = 24 },
                        new { Id = 70, BrandId = 23, Description = "125mg/5ml", GenericId = 28, InscriptionId = 22 },
                        new { Id = 71, BrandId = 23, Description = "250mg/5ml", GenericId = 28, InscriptionId = 22 },
                        new { Id = 72, BrandId = 24, Description = "120mg/5ml", GenericId = 64, InscriptionId = 22 },
                        new { Id = 73, BrandId = 24, Description = "500mg", GenericId = 64, InscriptionId = 24 },
                        new { Id = 74, BrandId = 24, Description = "250mg/5ml", GenericId = 64, InscriptionId = 23 },
                        new { Id = 75, BrandId = 24, Description = "250mg", GenericId = 64, InscriptionId = 24 },
                        new { Id = 76, BrandId = 24, Description = "325mg", GenericId = 64, InscriptionId = 24 },
                        new { Id = 77, BrandId = 24, Description = "100mg/ml", GenericId = 64, InscriptionId = 5 },
                        new { Id = 78, BrandId = 25, Description = "1.5mg/5ml", GenericId = 81, InscriptionId = 23 },
                        new { Id = 79, BrandId = 26, GenericId = 76, InscriptionId = 23 },
                        new { Id = 80, BrandId = 27, Description = "5mg/1mg/5ml", GenericId = 67, InscriptionId = 23 },
                        new { Id = 81, BrandId = 27, GenericId = 67, InscriptionId = 23 },
                        new { Id = 82, BrandId = 27, GenericId = 67, InscriptionId = 5 },
                        new { Id = 83, BrandId = 28, Description = "Sachet", GenericId = 15, InscriptionId = 13 },
                        new { Id = 84, BrandId = 29, Description = "250mg/5ml", GenericId = 64, InscriptionId = 22 },
                        new { Id = 85, BrandId = 29, Description = "250mg", GenericId = 64, InscriptionId = 24 },
                        new { Id = 86, BrandId = 29, Description = "500mg", GenericId = 64, InscriptionId = 24 },
                        new { Id = 87, BrandId = 29, Description = "325mg", GenericId = 64, InscriptionId = 24 },
                        new { Id = 88, BrandId = 29, Description = "120mg/5ml", GenericId = 64, InscriptionId = 23 },
                        new { Id = 89, BrandId = 29, Description = "100mg/ml", GenericId = 64, InscriptionId = 5 },
                        new { Id = 90, BrandId = 30, Description = "250mg/5ml", GenericId = 17, InscriptionId = 22 },
                        new { Id = 91, BrandId = 30, Description = "125mg/5ml", GenericId = 17, InscriptionId = 22 },
                        new { Id = 92, BrandId = 30, Description = "50mg/ml", GenericId = 18, InscriptionId = 5 },
                        new { Id = 93, BrandId = 31, Description = "500mg", GenericId = 19, InscriptionId = 3 },
                        new { Id = 94, BrandId = 31, Description = "250mg/5ml", GenericId = 19, InscriptionId = 22 },
                        new { Id = 95, BrandId = 31, Description = "125mg/5ml", GenericId = 19, InscriptionId = 22 },
                        new { Id = 96, BrandId = 31, Description = "100mg/ml", GenericId = 19, InscriptionId = 5 },
                        new { Id = 97, BrandId = 32, Description = "250mg/5ml", GenericId = 19, InscriptionId = 22 },
                        new { Id = 98, BrandId = 32, Description = "125mg/5ml", GenericId = 19, InscriptionId = 22 },
                        new { Id = 99, BrandId = 32, Description = "100mg/ml", GenericId = 19, InscriptionId = 5 },
                        new { Id = 100, BrandId = 33, GenericId = 57, InscriptionId = 5 },
                        new { Id = 101, BrandId = 34, Description = "500mg", GenericId = 23, InscriptionId = 3 },
                        new { Id = 102, BrandId = 34, Description = "125mg/5ml", GenericId = 23, InscriptionId = 22 },
                        new { Id = 103, BrandId = 34, Description = "250mg", GenericId = 23, InscriptionId = 3 },
                        new { Id = 104, BrandId = 35, Description = "125mg/5ml", GenericId = 24, InscriptionId = 22 },
                        new { Id = 105, BrandId = 36, Description = "125mg/5ml", GenericId = 24, InscriptionId = 24 },
                        new { Id = 106, BrandId = 36, Description = "500mg", GenericId = 24, InscriptionId = 24 },
                        new { Id = 107, BrandId = 36, Description = "250mg/5ml", GenericId = 24, InscriptionId = 22 },
                        new { Id = 108, BrandId = 37, Description = "125mg/5ml", GenericId = 24, InscriptionId = 22 },
                        new { Id = 109, BrandId = 38, Description = "250mg", GenericId = 24, InscriptionId = 24 },
                        new { Id = 110, BrandId = 38, Description = "500mg", GenericId = 24, InscriptionId = 24 },
                        new { Id = 111, BrandId = 38, Description = "250mg/5ml", GenericId = 24, InscriptionId = 22 },
                        new { Id = 112, BrandId = 38, Description = "125mg/5ml", GenericId = 24, InscriptionId = 22 },
                        new { Id = 113, BrandId = 39, Description = "Tube", GenericId = 26, InscriptionId = 4 },
                        new { Id = 114, BrandId = 40, Description = "125mg", GenericId = 74, InscriptionId = 24 },
                        new { Id = 115, BrandId = 40, Description = "125mg/5ml", GenericId = 74, InscriptionId = 22 },
                        new { Id = 116, BrandId = 41, GenericId = 77, InscriptionId = 12 },
                        new { Id = 117, BrandId = 42, Description = "Tube", GenericId = 54, InscriptionId = 14 },
                        new { Id = 118, BrandId = 43, Description = "75mg/5ml", GenericId = 25, InscriptionId = 22 },
                        new { Id = 119, BrandId = 44, Description = "400mg", GenericId = 30, InscriptionId = 28 },
                        new { Id = 120, BrandId = 45, Description = "100mg/5ml", GenericId = 33, InscriptionId = 23 },
                        new { Id = 121, BrandId = 45, Description = "100mg", GenericId = 33, InscriptionId = 24 },
                        new { Id = 122, BrandId = 46, GenericId = 13, InscriptionId = 5 },
                        new { Id = 123, BrandId = 46, GenericId = 13, InscriptionId = 23 },
                        new { Id = 124, BrandId = 47, GenericId = 68, InscriptionId = 23 },
                        new { Id = 125, BrandId = 47, GenericId = 68, InscriptionId = 5 },
                        new { Id = 126, BrandId = 48, Description = "200mg/5ml", GenericId = 47, InscriptionId = 22 },
                        new { Id = 127, BrandId = 48, Description = "100mg/5ml", GenericId = 47, InscriptionId = 22 },
                        new { Id = 128, BrandId = 48, Description = "100mg/2.5ml", GenericId = 47, InscriptionId = 5 },
                        new { Id = 129, BrandId = 49, Description = "250mg", GenericId = 52, InscriptionId = 3 },
                        new { Id = 130, BrandId = 49, Description = "500mg", GenericId = 52, InscriptionId = 3 },
                        new { Id = 131, BrandId = 50, GenericId = 77, InscriptionId = 12 },
                        new { Id = 132, BrandId = 51, GenericId = 83, InscriptionId = 23 },
                        new { Id = 133, BrandId = 51, GenericId = 83, InscriptionId = 5 },
                        new { Id = 134, BrandId = 52, GenericId = 55, InscriptionId = 8 },
                        new { Id = 135, BrandId = 52, GenericId = 55, InscriptionId = 4 },
                        new { Id = 136, BrandId = 53, GenericId = 9, InscriptionId = 15 },
                        new { Id = 137, BrandId = 54, Description = "218mg/5ml", GenericId = 60, InscriptionId = 22 },
                        new { Id = 138, BrandId = 54, Description = "200mg", GenericId = 60, InscriptionId = 3 },
                        new { Id = 139, BrandId = 55, Description = "300mg", GenericId = 69, InscriptionId = 3 },
                        new { Id = 140, BrandId = 56, Description = "300mg", GenericId = 4, InscriptionId = 24 },
                        new { Id = 141, BrandId = 56, Description = "30mg/5ml", GenericId = 4, InscriptionId = 23 },
                        new { Id = 142, BrandId = 56, Description = "7.5mg/5ml", GenericId = 4, InscriptionId = 5 },
                        new { Id = 143, BrandId = 56, Description = "15mg/2.5ml", GenericId = 4, InscriptionId = 23 },
                        new { Id = 144, BrandId = 57, Description = "400mg", GenericId = 47, InscriptionId = 3 },
                        new { Id = 145, BrandId = 57, Description = "200mg", GenericId = 47, InscriptionId = 3 },
                        new { Id = 146, BrandId = 58, Description = "500mg", GenericId = 53, InscriptionId = 24 },
                        new { Id = 147, BrandId = 58, Description = "25mg/1ml", GenericId = 53, InscriptionId = 23 },
                        new { Id = 148, BrandId = 58, GenericId = 53 },
                        new { Id = 149, BrandId = 59, Description = "550mg", GenericId = 59, InscriptionId = 24 },
                        new { Id = 150, BrandId = 59, Description = "275mg", GenericId = 59, InscriptionId = 24 },
                        new { Id = 151, BrandId = 60, Description = "1000mg", GenericId = 1, InscriptionId = 18 },
                        new { Id = 152, BrandId = 60, Description = "100mg/5ml", GenericId = 1, InscriptionId = 23 },
                        new { Id = 153, BrandId = 60, Description = "200mg", GenericId = 1, InscriptionId = 18 },
                        new { Id = 154, BrandId = 61, Description = "Tube", GenericId = 42, InscriptionId = 13 },
                        new { Id = 155, BrandId = 62, Description = "Tube", GenericId = 40, InscriptionId = 13 },
                        new { Id = 156, BrandId = 63, Description = "Tube", GenericId = 39, InscriptionId = 6 },
                        new { Id = 157, BrandId = 64, Description = "100mg", GenericId = 41, InscriptionId = 24 },
                        new { Id = 158, BrandId = 64, Description = "16.7mg/5ml", GenericId = 41, InscriptionId = 22 },
                        new { Id = 159, BrandId = 65, GenericId = 44, InscriptionId = 6 },
                        new { Id = 160, BrandId = 66, Description = "500mg", GenericId = 52, InscriptionId = 3 },
                        new { Id = 161, BrandId = 66, Description = "250mg", GenericId = 52, InscriptionId = 3 },
                        new { Id = 162, BrandId = 67, Description = "1mg/1ml", GenericId = 31, InscriptionId = 3 },
                        new { Id = 163, BrandId = 68, Description = "500mg", GenericId = 6, InscriptionId = 3 },
                        new { Id = 164, BrandId = 68, Description = "250mg/5ml", GenericId = 6, InscriptionId = 22 },
                        new { Id = 165, BrandId = 68, Description = "100mg/ml", GenericId = 6, InscriptionId = 5 },
                        new { Id = 166, BrandId = 69, GenericId = 13, InscriptionId = 23 },
                        new { Id = 167, BrandId = 69, GenericId = 13, InscriptionId = 5 },
                        new { Id = 168, BrandId = 70, GenericId = 63, InscriptionId = 18 },
                        new { Id = 169, BrandId = 71, Description = "250mg/5ml", GenericId = 35, InscriptionId = 22 },
                        new { Id = 170, BrandId = 71, Description = "100mg/ml", GenericId = 35, InscriptionId = 5 },
                        new { Id = 171, BrandId = 72, Description = "Bot", GenericId = 48, InscriptionId = 23 },
                        new { Id = 172, BrandId = 73, Description = "25mg", GenericId = 46, InscriptionId = 24 },
                        new { Id = 173, BrandId = 73, Description = "2mg/ml", GenericId = 46, InscriptionId = 23 },
                        new { Id = 174, BrandId = 73, Description = "10mg", GenericId = 46, InscriptionId = 24 },
                        new { Id = 175, BrandId = 74, GenericId = 11, InscriptionId = 23 },
                        new { Id = 176, BrandId = 74, GenericId = 11, InscriptionId = 3 },
                        new { Id = 177, BrandId = 75, Description = "4mg", GenericId = 56, InscriptionId = 24 },
                        new { Id = 178, BrandId = 75, Description = "10mg", GenericId = 56, InscriptionId = 24 },
                        new { Id = 179, BrandId = 75, Description = "5mg", GenericId = 56, InscriptionId = 24 },
                        new { Id = 180, BrandId = 76, Description = "200mg/40mg/5ml", GenericId = 29, InscriptionId = 26 },
                        new { Id = 181, BrandId = 77, Description = "500mg", GenericId = 24, InscriptionId = 24 },
                        new { Id = 182, BrandId = 77, Description = "125mg/5ml", GenericId = 24, InscriptionId = 22 },
                        new { Id = 183, BrandId = 77, Description = "250mg", GenericId = 24, InscriptionId = 24 },
                        new { Id = 184, BrandId = 77, Description = "250mg/5ml", GenericId = 24, InscriptionId = 22 },
                        new { Id = 185, BrandId = 78, Description = "500mg", GenericId = 24, InscriptionId = 24 },
                        new { Id = 186, BrandId = 78, Description = "250mg/5ml", GenericId = 24, InscriptionId = 22 },
                        new { Id = 187, BrandId = 78, Description = "125mg/5ml", GenericId = 24, InscriptionId = 22 },
                        new { Id = 188, BrandId = 78, Description = "250mg", GenericId = 24, InscriptionId = 24 },
                        new { Id = 189, BrandId = 79, GenericId = 5, InscriptionId = 10 },
                        new { Id = 190, BrandId = 80, Description = "100mg/5ml", GenericId = 16, InscriptionId = 23 },
                        new { Id = 191, BrandId = 80, Description = "50mg/ml", GenericId = 16, InscriptionId = 5 },
                        new { Id = 192, BrandId = 81, GenericId = 3, InscriptionId = 24 },
                        new { Id = 193, BrandId = 81, GenericId = 3, InscriptionId = 22 },
                        new { Id = 194, BrandId = 82, Description = "200mg", GenericId = 47, InscriptionId = 3 },
                        new { Id = 195, BrandId = 83, Description = "25mgm", GenericId = 73, InscriptionId = 24 },
                        new { Id = 196, BrandId = 83, Description = "50mgm", GenericId = 73, InscriptionId = 24 },
                        new { Id = 197, BrandId = 83, Description = "5mgm/ml", GenericId = 73, InscriptionId = 23 },
                        new { Id = 198, BrandId = 84, Description = "5mg", GenericId = 56, InscriptionId = 24 },
                        new { Id = 199, BrandId = 84, Description = "10mg", GenericId = 56, InscriptionId = 24 },
                        new { Id = 200, BrandId = 84, Description = "4mg", GenericId = 56, InscriptionId = 24 },
                        new { Id = 201, BrandId = 85, Description = "5mg", GenericId = 56, InscriptionId = 24 },
                        new { Id = 202, BrandId = 85, Description = "10mg", GenericId = 56, InscriptionId = 24 },
                        new { Id = 203, BrandId = 85, Description = "4mg", GenericId = 56, InscriptionId = 24 },
                        new { Id = 204, BrandId = 85, Description = "4mg", GenericId = 56, InscriptionId = 7 },
                        new { Id = 205, BrandId = 86, Description = "10mg", GenericId = 32, InscriptionId = 24 },
                        new { Id = 206, BrandId = 87, Description = "3.3g/5ml", GenericId = 49, InscriptionId = 23 },
                        new { Id = 207, BrandId = 88, GenericId = 80, InscriptionId = 11 },
                        new { Id = 208, BrandId = 88, GenericId = 80, InscriptionId = 27 },
                        new { Id = 209, BrandId = 89, Description = "7.5mg/ml", GenericId = 4, InscriptionId = 5 },
                        new { Id = 210, BrandId = 90, Description = "50mg", GenericId = 34, InscriptionId = 24 },
                        new { Id = 211, BrandId = 91, Description = "120mg/5ml", GenericId = 64, InscriptionId = 23 },
                        new { Id = 212, BrandId = 91, Description = "250mg/5ml", GenericId = 64, InscriptionId = 23 },
                        new { Id = 213, BrandId = 91, Description = "100ml", GenericId = 64, InscriptionId = 5 },
                        new { Id = 214, BrandId = 92, Description = "100ml", GenericId = 64, InscriptionId = 5 },
                        new { Id = 215, BrandId = 92, Description = "250mg/5ml", GenericId = 64, InscriptionId = 23 },
                        new { Id = 216, BrandId = 93, Description = "250mg/5ml", GenericId = 64, InscriptionId = 23 },
                        new { Id = 217, BrandId = 93, Description = "100mg/ml", GenericId = 64, InscriptionId = 5 },
                        new { Id = 218, BrandId = 94, GenericId = 13, InscriptionId = 23 },
                        new { Id = 219, BrandId = 94, GenericId = 13, InscriptionId = 5 },
                        new { Id = 220, BrandId = 95, Description = "250mg/12.5mg", GenericId = 65, InscriptionId = 23 },
                        new { Id = 221, BrandId = 95, Description = "325mg/25mg", GenericId = 65, InscriptionId = 3 },
                        new { Id = 222, BrandId = 96, GenericId = 80, InscriptionId = 27 },
                        new { Id = 223, BrandId = 96, GenericId = 80, InscriptionId = 11 },
                        new { Id = 224, BrandId = 97, Description = "125mg/5ml", GenericId = 28, InscriptionId = 22 },
                        new { Id = 225, BrandId = 97, Description = "250mg/5ml", GenericId = 28, InscriptionId = 22 },
                        new { Id = 226, BrandId = 98, GenericId = 67, InscriptionId = 23 },
                        new { Id = 227, BrandId = 98, GenericId = 67, InscriptionId = 5 },
                        new { Id = 228, BrandId = 99, Description = "26.7mg/5ml", GenericId = 82, InscriptionId = 23 },
                        new { Id = 229, BrandId = 100, Description = "20 Mg", GenericId = 62, InscriptionId = 3 },
                        new { Id = 230, BrandId = 101, Description = "125mg", GenericId = 64, InscriptionId = 21 },
                        new { Id = 231, BrandId = 101, Description = "250mg/5ml", GenericId = 64, InscriptionId = 21 },
                        new { Id = 232, BrandId = 102, Description = "20mg/5ml", GenericId = 71, InscriptionId = 23 },
                        new { Id = 233, BrandId = 103, Description = "100,000 Iu", GenericId = 61, InscriptionId = 22 },
                        new { Id = 234, BrandId = 104, Description = "125mg/5ml", GenericId = 23, InscriptionId = 22 },
                        new { Id = 235, BrandId = 104, Description = "250mg/5ml", GenericId = 23, InscriptionId = 3 },
                        new { Id = 236, BrandId = 104, Description = "500mg", GenericId = 23, InscriptionId = 3 },
                        new { Id = 237, BrandId = 105, Description = "250mg/5ml", GenericId = 6, InscriptionId = 22 },
                        new { Id = 238, BrandId = 105, Description = "125mg/5ml", GenericId = 6, InscriptionId = 22 },
                        new { Id = 239, BrandId = 105, Description = "100mg/ml", GenericId = 6, InscriptionId = 5 },
                        new { Id = 240, BrandId = 106, GenericId = 13, InscriptionId = 23 },
                        new { Id = 241, BrandId = 106, GenericId = 13, InscriptionId = 5 },
                        new { Id = 242, BrandId = 107, Description = "125mg/5ml", GenericId = 23, InscriptionId = 23 },
                        new { Id = 243, BrandId = 107, Description = "250mg", GenericId = 23, InscriptionId = 3 },
                        new { Id = 244, BrandId = 107, Description = "500mg", GenericId = 23, InscriptionId = 3 },
                        new { Id = 245, BrandId = 108, Description = "250mg/5ml", GenericId = 27, InscriptionId = 22 },
                        new { Id = 246, BrandId = 108, Description = "250mg/5ml", GenericId = 27, InscriptionId = 22 },
                        new { Id = 247, BrandId = 108, Description = "125mg/5ml", GenericId = 27, InscriptionId = 22 },
                        new { Id = 248, BrandId = 109, GenericId = 70, InscriptionId = 19 },
                        new { Id = 249, BrandId = 109, GenericId = 70, InscriptionId = 1 },
                        new { Id = 250, BrandId = 110, Description = "1gm", GenericId = 7 },
                        new { Id = 251, BrandId = 110, Description = "750mg", GenericId = 7 },
                        new { Id = 252, BrandId = 110, Description = "500mg", GenericId = 7 },
                        new { Id = 253, BrandId = 110, Description = "250mg", GenericId = 7 },
                        new { Id = 254, BrandId = 111, Description = "500mg", GenericId = 52, InscriptionId = 3 },
                        new { Id = 255, BrandId = 111, Description = "50mg/5ml", GenericId = 52, InscriptionId = 22 },
                        new { Id = 256, BrandId = 111, Description = "250mg", GenericId = 52, InscriptionId = 3 },
                        new { Id = 257, BrandId = 112, Description = "125mg", GenericId = 64, InscriptionId = 21 },
                        new { Id = 258, BrandId = 112, Description = "250mg", GenericId = 64, InscriptionId = 21 },
                        new { Id = 259, BrandId = 113, GenericId = 72 },
                        new { Id = 260, BrandId = 113, Description = "10mg/5ml", GenericId = 72, InscriptionId = 23 },
                        new { Id = 261, BrandId = 114, Description = "20mg/5ml", GenericId = 71, InscriptionId = 23 },
                        new { Id = 262, BrandId = 115, GenericId = 57, InscriptionId = 23 },
                        new { Id = 263, BrandId = 116, Description = "250mg/5ml", GenericId = 27, InscriptionId = 22 },
                        new { Id = 264, BrandId = 116, Description = "250mg/5ml", GenericId = 27, InscriptionId = 22 },
                        new { Id = 265, BrandId = 116, Description = "125mg/5ml", GenericId = 27, InscriptionId = 22 },
                        new { Id = 266, BrandId = 117, Description = "2.5mg/2.5ml", GenericId = 75, InscriptionId = 12 },
                        new { Id = 267, BrandId = 118, Description = "2mg", GenericId = 75, InscriptionId = 24 },
                        new { Id = 268, BrandId = 118, Description = "2mg/5ml", GenericId = 75, InscriptionId = 23 },
                        new { Id = 269, BrandId = 119, GenericId = 77, InscriptionId = 12 },
                        new { Id = 270, BrandId = 120, Description = "1.5mg/5ml", GenericId = 81, InscriptionId = 23 },
                        new { Id = 271, BrandId = 121, GenericId = 79, InscriptionId = 5 },
                        new { Id = 272, BrandId = 122, Description = "250mg/5ml", GenericId = 27, InscriptionId = 22 },
                        new { Id = 273, BrandId = 122, Description = "250mg/5ml", GenericId = 27, InscriptionId = 22 },
                        new { Id = 274, BrandId = 122, Description = "125mg/5ml", GenericId = 27, InscriptionId = 22 },
                        new { Id = 275, BrandId = 123, Description = "125mg/5ml", GenericId = 51, InscriptionId = 23 },
                        new { Id = 276, BrandId = 124, Description = "20mg/5ml", GenericId = 71, InscriptionId = 23 },
                        new { Id = 277, BrandId = 125, Description = "250mg", GenericId = 7 },
                        new { Id = 278, BrandId = 125, Description = "1gm", GenericId = 7 },
                        new { Id = 279, BrandId = 125, Description = "750mg", GenericId = 7 },
                        new { Id = 280, BrandId = 125, Description = "500mg", GenericId = 7 },
                        new { Id = 281, BrandId = 126, GenericId = 80, InscriptionId = 27 },
                        new { Id = 282, BrandId = 126, GenericId = 80, InscriptionId = 11 },
                        new { Id = 283, BrandId = 127, GenericId = 36, InscriptionId = 23 },
                        new { Id = 284, BrandId = 128, Description = "250mg/5ml", GenericId = 19, InscriptionId = 22 },
                        new { Id = 285, BrandId = 128, Description = "125mg/5ml", GenericId = 19, InscriptionId = 22 },
                        new { Id = 286, BrandId = 128, Description = "100mg/ml", GenericId = 19, InscriptionId = 5 },
                        new { Id = 287, BrandId = 129, Description = "25/250", GenericId = 78, InscriptionId = 9 },
                        new { Id = 288, BrandId = 129, Description = "25/125", GenericId = 78, InscriptionId = 9 },
                        new { Id = 289, BrandId = 129, Description = "25/50", GenericId = 78, InscriptionId = 9 },
                        new { Id = 290, BrandId = 130, Description = "10mg", GenericId = 56, InscriptionId = 24 },
                        new { Id = 291, BrandId = 130, Description = "5mg", GenericId = 56, InscriptionId = 24 },
                        new { Id = 292, BrandId = 130, Description = "4mg", GenericId = 56, InscriptionId = 24 },
                        new { Id = 293, BrandId = 130, Description = "4mg", GenericId = 56, InscriptionId = 7 },
                        new { Id = 294, BrandId = 131, Description = "550mg", GenericId = 59, InscriptionId = 24 },
                        new { Id = 295, BrandId = 131, Description = "275mg", GenericId = 59, InscriptionId = 24 },
                        new { Id = 296, BrandId = 132, Description = "100mg/5ml", GenericId = 16, InscriptionId = 23 },
                        new { Id = 297, BrandId = 132, Description = "50mg/ml", GenericId = 16, InscriptionId = 5 },
                        new { Id = 298, BrandId = 133, GenericId = 76, InscriptionId = 23 },
                        new { Id = 299, BrandId = 134, Description = "500mg", GenericId = 37, InscriptionId = 3 },
                        new { Id = 300, BrandId = 134, Description = "250mg", GenericId = 37, InscriptionId = 3 },
                        new { Id = 301, BrandId = 134, Description = "125mg/5ml", GenericId = 37, InscriptionId = 22 },
                        new { Id = 302, BrandId = 135, Description = "250mg", GenericId = 66, InscriptionId = 3 },
                        new { Id = 303, BrandId = 135, Description = "500mg", GenericId = 66, InscriptionId = 3 },
                        new { Id = 304, BrandId = 136, Description = "250mg/5ml", GenericId = 64, InscriptionId = 22 },
                        new { Id = 305, BrandId = 136, Description = "120mg/5ml", GenericId = 64, InscriptionId = 23 },
                        new { Id = 306, BrandId = 136, Description = "250mg", GenericId = 64, InscriptionId = 24 },
                        new { Id = 307, BrandId = 136, Description = "250mg/5ml", GenericId = 64, InscriptionId = 23 },
                        new { Id = 308, BrandId = 136, Description = "500mg", GenericId = 64, InscriptionId = 24 },
                        new { Id = 309, BrandId = 136, Description = "325mg", GenericId = 64, InscriptionId = 24 },
                        new { Id = 310, BrandId = 136, Description = "100mg/ml", GenericId = 64, InscriptionId = 5 },
                        new { Id = 311, BrandId = 137, Description = "100mg", GenericId = 20, InscriptionId = 3 },
                        new { Id = 312, BrandId = 137, Description = "100mg/5ml", GenericId = 20, InscriptionId = 22 },
                        new { Id = 313, BrandId = 137, Description = "200mg", GenericId = 20, InscriptionId = 3 },
                        new { Id = 314, BrandId = 137, Description = "20mg/ml", GenericId = 20, InscriptionId = 5 },
                        new { Id = 315, BrandId = 138, Description = "400mg/80/5ml", GenericId = 29, InscriptionId = 22 },
                        new { Id = 316, BrandId = 139, Description = "200mg", GenericId = 20, InscriptionId = 3 },
                        new { Id = 317, BrandId = 139, Description = "20mg/ml", GenericId = 20, InscriptionId = 5 },
                        new { Id = 318, BrandId = 139, Description = "100mg/5ml", GenericId = 20, InscriptionId = 5 },
                        new { Id = 319, BrandId = 139, Description = "100mg", GenericId = 20, InscriptionId = 3 },
                        new { Id = 320, BrandId = 140, Description = "2.5mg/2.5ml", GenericId = 75, InscriptionId = 12 },
                        new { Id = 321, BrandId = 140, Description = "100mgm/Inhalation", GenericId = 75, InscriptionId = 9 },
                        new { Id = 322, BrandId = 140, Description = "2mg", GenericId = 75, InscriptionId = 24 },
                        new { Id = 323, BrandId = 141, GenericId = 76, InscriptionId = 23 },
                        new { Id = 324, BrandId = 142, Description = "10mg/ml", GenericId = 22, InscriptionId = 5 },
                        new { Id = 325, BrandId = 142, Description = "1mg/ml", GenericId = 22, InscriptionId = 20 },
                        new { Id = 326, BrandId = 143, Description = "5mg/ml", GenericId = 32, InscriptionId = 5 },
                        new { Id = 327, BrandId = 143, Description = "5mg/5ml", GenericId = 32, InscriptionId = 23 },
                        new { Id = 328, BrandId = 144, Description = "125mg/5ml", GenericId = 17, InscriptionId = 22 },
                        new { Id = 329, BrandId = 144, Description = "250mg/5ml", GenericId = 17, InscriptionId = 22 },
                        new { Id = 330, BrandId = 144, Description = "50mg/ml", GenericId = 17, InscriptionId = 5 },
                        new { Id = 331, BrandId = 145, Description = "250mg/5ml", GenericId = 19, InscriptionId = 22 },
                        new { Id = 332, BrandId = 145, Description = "125mg/5ml", GenericId = 19, InscriptionId = 22 },
                        new { Id = 333, BrandId = 145, Description = "100mg/ml", GenericId = 19, InscriptionId = 5 },
                        new { Id = 334, BrandId = 146, Description = "5mg/ml", GenericId = 50, InscriptionId = 23 },
                        new { Id = 335, BrandId = 146, Description = "5mg", GenericId = 50, InscriptionId = 24 },
                        new { Id = 336, BrandId = 146, Description = "5mg/ml", GenericId = 50, InscriptionId = 5 },
                        new { Id = 337, BrandId = 147, GenericId = 13, InscriptionId = 5 },
                        new { Id = 338, BrandId = 147, GenericId = 13, InscriptionId = 23 },
                        new { Id = 339, BrandId = 148, Description = "250mg", GenericId = 21, InscriptionId = 3 },
                        new { Id = 340, BrandId = 149, Description = "500mg", GenericId = 8, InscriptionId = 24 },
                        new { Id = 341, BrandId = 149, Description = "250mg", GenericId = 8, InscriptionId = 24 },
                        new { Id = 342, BrandId = 149, Description = "200mg/5ml", GenericId = 8, InscriptionId = 22 },
                        new { Id = 343, BrandId = 150, Description = "250mg/5ml", GenericId = 21, InscriptionId = 22 },
                        new { Id = 344, BrandId = 150, Description = "125mg/5ml", GenericId = 21, InscriptionId = 22 },
                        new { Id = 345, BrandId = 151, Description = "500mg", GenericId = 8, InscriptionId = 24 },
                        new { Id = 346, BrandId = 151, Description = "200mg/5ml", GenericId = 8, InscriptionId = 22 },
                        new { Id = 347, BrandId = 152, Description = "250mg", GenericId = 8, InscriptionId = 24 },
                        new { Id = 348, BrandId = 152, Description = "400mg", GenericId = 2, InscriptionId = 24 },
                        new { Id = 349, BrandId = 152, Description = "200mg", GenericId = 2, InscriptionId = 24 },
                        new { Id = 350, BrandId = 153, Description = "10mg/ml", GenericId = 22, InscriptionId = 5 },
                        new { Id = 351, BrandId = 153, Description = "1mg/ml", GenericId = 22, InscriptionId = 20 },
                        new { Id = 352, BrandId = 89, Description = "30mg", GenericId = 4, InscriptionId = 24 },
                        new { Id = 353, BrandId = 89, Description = "30mg/5ml", GenericId = 4, InscriptionId = 23 },
                        new { Id = 354, BrandId = 89, Description = "15mg/5ml", GenericId = 4, InscriptionId = 23 }
                    );
                });

            modelBuilder.Entity("SaintJudeHospital.Data.Entity.Parent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("MiddleName");

                    b.Property<string>("Occupation");

                    b.HasKey("Id");

                    b.ToTable("Parents");
                });

            modelBuilder.Entity("SaintJudeHospital.Data.Entity.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address");

                    b.Property<int>("Age");

                    b.Property<string>("CivilStatus");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<string>("EmailAddress");

                    b.Property<string>("FirstName");

                    b.Property<string>("Gender");

                    b.Property<string>("HomePhoneNumber");

                    b.Property<string>("LastName");

                    b.Property<string>("MiddleName");

                    b.Property<int?>("Parent1Id");

                    b.Property<int?>("Parent2Id");

                    b.Property<int?>("ParentId1");

                    b.Property<int?>("ParentId2");

                    b.Property<int>("PatientStatusId");

                    b.Property<string>("PersonalPhoneNumber");

                    b.HasKey("Id");

                    b.HasIndex("Parent1Id");

                    b.HasIndex("Parent2Id");

                    b.HasIndex("PatientStatusId");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("SaintJudeHospital.Data.Entity.PatientPhotos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsDeleted");

                    b.Property<bool>("IsPrimary");

                    b.Property<string>("Path");

                    b.Property<int?>("PatientId");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("PatientPhotos");
                });

            modelBuilder.Entity("SaintJudeHospital.Data.Entity.PatientStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("PatientStatuses");
                });

            modelBuilder.Entity("SaintJudeHospital.Data.Entity.Symtom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Symtoms");

                    b.HasData(
                        new { Id = 1, Name = "Bleeding" },
                        new { Id = 2, Name = "Bruise" },
                        new { Id = 3, Name = "Cough" },
                        new { Id = 4, Name = "Bites" },
                        new { Id = 5, Name = "Fever" },
                        new { Id = 6, Name = "Cold" },
                        new { Id = 7, Name = "Difficulty in swallowing" },
                        new { Id = 8, Name = "Ear discharge" },
                        new { Id = 9, Name = "Ear ache/pain" },
                        new { Id = 10, Name = "Constipation" },
                        new { Id = 11, Name = "Diarrhea" },
                        new { Id = 12, Name = "Hair fall" },
                        new { Id = 13, Name = "Abdominal pain" },
                        new { Id = 14, Name = "Deformity" },
                        new { Id = 15, Name = "Headache" },
                        new { Id = 16, Name = "Infected wounds" },
                        new { Id = 17, Name = "Itchness" },
                        new { Id = 18, Name = "Loss of consciousness" },
                        new { Id = 19, Name = "Mass" },
                        new { Id = 20, Name = "Joint pain" },
                        new { Id = 21, Name = "Muscle pain" },
                        new { Id = 22, Name = "Skin lesions" },
                        new { Id = 23, Name = "Trauma" },
                        new { Id = 24, Name = "Pain urination" },
                        new { Id = 25, Name = "Rushes" },
                        new { Id = 26, Name = "Less appetite" },
                        new { Id = 27, Name = "LBM" },
                        new { Id = 28, Name = "Vomiting" },
                        new { Id = 29, Name = "Dysuria" },
                        new { Id = 30, Name = "Rashes" },
                        new { Id = 31, Name = "Dysphagia" },
                        new { Id = 32, Name = "Vaginal Discharge" },
                        new { Id = 33, Name = "Urticarial rash" },
                        new { Id = 34, Name = "Eye discharge" },
                        new { Id = 35, Name = "Chest gurgling" },
                        new { Id = 36, Name = "Epistaxis" },
                        new { Id = 37, Name = "Pustules" },
                        new { Id = 38, Name = "Nasal congestion" }
                    );
                });

            modelBuilder.Entity("SaintJudeHospital.Data.Entity.Vaccine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Booster");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int>("Dose");

                    b.Property<string>("Name");

                    b.Property<int>("Price");

                    b.Property<int>("VaccineTypeId");

                    b.HasKey("Id");

                    b.HasIndex("VaccineTypeId");

                    b.ToTable("Vaccines");
                });

            modelBuilder.Entity("SaintJudeHospital.Data.Entity.VaccinePatient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CheckupId");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int>("PatientId");

                    b.Property<int>("VaccineId");

                    b.HasKey("Id");

                    b.HasIndex("CheckupId");

                    b.HasIndex("PatientId");

                    b.HasIndex("VaccineId");

                    b.ToTable("VaccinePatients");
                });

            modelBuilder.Entity("SaintJudeHospital.Data.Entity.VaccineType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("VaccineTypes");
                });

            modelBuilder.Entity("SaintJudeHospital.Data.Indentity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<int?>("CreateBy");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<string>("FirstName");

                    b.Property<bool>("IsDelete");

                    b.Property<string>("LastName");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SaintJudeHospital.Data.Indentity.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SaintJudeHospital.Data.Indentity.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SaintJudeHospital.Data.Indentity.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SaintJudeHospital.Data.Indentity.ApplicationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SaintJudeHospital.Data.Entity.Bill", b =>
                {
                    b.HasOne("SaintJudeHospital.Data.Entity.BillStatus", "BillStatus")
                        .WithMany()
                        .HasForeignKey("BillStatusId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SaintJudeHospital.Data.Entity.Checkup", "Checkup")
                        .WithMany()
                        .HasForeignKey("CheckupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SaintJudeHospital.Data.Entity.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SaintJudeHospital.Data.Entity.MedicalCertificate", b =>
                {
                    b.HasOne("SaintJudeHospital.Data.Entity.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SaintJudeHospital.Data.Entity.Medicine", b =>
                {
                    b.HasOne("SaintJudeHospital.Data.Entity.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId");

                    b.HasOne("SaintJudeHospital.Data.Entity.Generic", "Generic")
                        .WithMany()
                        .HasForeignKey("GenericId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SaintJudeHospital.Data.Entity.Inscription", "Inscription")
                        .WithMany()
                        .HasForeignKey("InscriptionId");
                });

            modelBuilder.Entity("SaintJudeHospital.Data.Entity.Patient", b =>
                {
                    b.HasOne("SaintJudeHospital.Data.Entity.Parent", "Parent1")
                        .WithMany()
                        .HasForeignKey("Parent1Id");

                    b.HasOne("SaintJudeHospital.Data.Entity.Parent", "Parent2")
                        .WithMany()
                        .HasForeignKey("Parent2Id");

                    b.HasOne("SaintJudeHospital.Data.Entity.PatientStatus", "PatientStatus")
                        .WithMany()
                        .HasForeignKey("PatientStatusId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SaintJudeHospital.Data.Entity.PatientPhotos", b =>
                {
                    b.HasOne("SaintJudeHospital.Data.Entity.Patient", "Patient")
                        .WithMany("PatientPhotos")
                        .HasForeignKey("PatientId");
                });

            modelBuilder.Entity("SaintJudeHospital.Data.Entity.Vaccine", b =>
                {
                    b.HasOne("SaintJudeHospital.Data.Entity.VaccineType", "VaccineType")
                        .WithMany()
                        .HasForeignKey("VaccineTypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SaintJudeHospital.Data.Entity.VaccinePatient", b =>
                {
                    b.HasOne("SaintJudeHospital.Data.Entity.Checkup", "Chekup")
                        .WithMany()
                        .HasForeignKey("CheckupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SaintJudeHospital.Data.Entity.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SaintJudeHospital.Data.Entity.Vaccine", "Vaccine")
                        .WithMany()
                        .HasForeignKey("VaccineId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
